### PR TITLE
changed HTML and CSS

### PR DESCRIPTION
**Pull request by Lilith9**
Here's my advice with greetings from super snowy Bavaria

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @Lilith9,

This is a great start! However, there are a few changes that we'll need to make before we can merge this in.

1. We would like for you to include a link to your advice page in the index.html file. 
2. Your advice file is currently in the main directory. Instead, we would like for it to reside in the `advice` folder that we've provided in this project.
3. It looks like you added an `img` folder and an image file to this project. We want to keep this repo as clean as possible so we'd like for you to remove both the folder and the file. If you want to include an image on your page, you'll need to host it elsewhere and then use the link as the src.

If you could make those changes, all you have to do is run a slightly different git command (`git add -A`), commit, and push and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @Lilith9,

You are definitely not the only one! :D 

First of all, thanks for making that change! It looks like in the process, you added another 105-practice folder inside of that folder. We'll need to make sure that we remove that and then run our slightly different git command again (`git add -A`), then commit and push.

xoxo,
Sharon

**Comment by Lilith9** [comment]
Hey Sharon,

unbelievable…even more embarrassed ;)

So, I just pushed my next try - intensely hoping that this time everything is gonna be ok!
Sorry to cause you so much trouble!

xoxo,
Melanie

**Comment by redrambles** [comment]
Hey @Lilith9,

Sorry for the delay! Thanks for making that last change - your code is all merged in!!! Yay! :)

Cheers,
Ann :)

**Comment by Lilith9** [comment]
Hey Ann,

thank you! I finally got it right...What a relief!

All the best,
Melanie 



Von meinem iPhone gesendet

**Pull request merged**
