### PR TITLE
Anna S link added

### PR DESCRIPTION
**Pull request by annastoj**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @annastoj !

This is great!! The only thing is that you accidentally deleted another student's file from the advice folder called `advice-anna.html` and we are going to want that back. (You can see the diff of your pull request [here](https://github.com/skillcrush/105-practice/pull/1598/files) if you are curious.)

Once you add the file back, please add the change with `git add -A`, commit as per usual and push up your `advice` branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code. Let us know if you have any questions!

Cheers,
Ann :)

**Comment by acodeinprogress** [comment]
Hey @annastoj,

Congratulations on making your first pull request!

I see that you deleted the file called advice-anna.html. Since we want to preserve everyone's work, you'll need to add that file back in before we can get this merged in.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @annastoj,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Comment by annastoj** [comment]
I am so sorry Sharon. I somehow missed this email and switched tracks so i
didn't get a notification. I will redo this portion of the assignment.
Yikes!

**Pull request closed without merging**
