### PR TITLE
added courtneyschild advice page

### PR DESCRIPTION
**Pull request by canvasbycourt**

### CODE REVIEW

**Comment by canvasbycourt** [comment]
Some advice I'd like to share!

**Comment by redrambles** [comment]
Hey @canvasbycourt !

Ok! We got the link to your advice file in the main index.html file - awesome! We still need your advice file inside the /advice folder, though - as well as your css inside the /css folder. Perhaps there are a few files that still need to be added, committed and pushed? Once you push to your 105-courtneys-child branch, this pull request will be automatically updated, and then we should be able to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by canvasbycourt** [comment]
Okay, I believe I added the files you need. Did this work?

**Comment by acodeinprogress** [comment]
Hey @canvasbycourt,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
