### PR TITLE
Experiments

### PR DESCRIPTION
**Pull request by mcgowanl**
Hope you smile a little!!

### CODE REVIEW

**Comment by redrambles** [comment]
I did! Hahaha - love it! :)

The only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. If you're not sure how to do this, feel free to take a look at other students links for reference. :)

Once you add your link, add and commit your changes and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by mcgowanl** [comment]
Did I do it right????? (Fingers are soooooo crossed right now!!)

**Comment by redrambles** [comment]
Hey there!

Ok! So you added a file called 'css/style.css' which we don't need. So let's remove that file, but keep the other two! (advice/advice-lmcg.html and css/advice-lmcg.css). 

Once that is done, open up the main index.html file. You will see a long list of links - each student added their own, which points to their advice file. We want you to add your link as well! Most students add theirs to the top or the bottom of the list, but you can add it anywhere you like.

Once you have made these changes, please add with `git add -A` and then commit `git commit -m "your message here"` and then push up your branch once more: `git push origin experiments` - and we should be all set to merge in your code! You got this!

As always - please reach out if you have any questions!

Cheers,
Ann :)

**Comment by mcgowanl** [comment]
Hi Ann - 

Thank you for your help!!
Adding the link had me all messed up for some reason???
I kept right clicking to try to add and that of course wasn't working.
When I read your notes this morning it dawned on me what I need to do with the main index.html file...so thank you so much!!

Laura

**Comment by acodeinprogress** [comment]
Hey @mcgowanl,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

xoxo,
Sharon

**Pull request merged**
