### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by Blueant528**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hi @Blueant528,

Congrats on making your first pull request!

It looks like you made a small change to the <h1> in the index.html file that we would like for you to change back.

The other issue is that in the process of fixing some merge conflicts, you left the merge conflict markers in the index.html.

You'll need to remove those merge conflict markers and restore the <h1> back to its original text before we can merge this in.

Once you make those changes, you can add, commit, and push your work and we can incorporate your code into the project.

xoxo,
Sharon

**Comment by Blueant528** [comment]
Ty Sharon 
Removed the conflict markers and push it up.  Are those fixed in your end?

As far as the little change I made in the index.html file that I need to fix, I have no idea what I did, can you point me in the right direction?

Thank You

**Comment by redrambles** [comment]
Hey @Blueant528 !

Yes - the conflicts are fixed on our end, thank you! What we are referring to in terms of the change in the index.html file - is the change from 'newbies' to 'new people'. We would like to keep 'newbies'. :) Here is a link to the changes proposed by your pull request - if you scroll down you will see the index.html file and the `<h1>` change that we are referring to: https://github.com/skillcrush/105-practice/pull/1376/files

Once that is changed back to what it was - please save the file - add and commit the change and push up your `advice` branch once more, which will automatically update this pull request - and then we should be all set to merge in your code.

Keep us posted!

Cheers,
Ann :)

**Comment by Blueant528** [comment]
Thank You for pointing me in the right direction.  Hopefully this be all set now

**Comment by redrambles** [comment]
Hey @Blueant528,

Thanks for making those changes! You did a great job and your code is all merged in! Yay!

Cheers,
Ann :)

**Pull request merged**
