### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by carolnourse**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @carolnourse !

This is really great! The only thing that we need from you is to clean up the merge conflicts markers that were left being in the index.html page. [See here.](https://github.com/skillcrush/105-practice/pull/894/files#diff-eacf331f0ffc35d4b482f1d15a887d3bR635-R638)

Once you've made that edit, add and commit the change and then push up your advice branch once more which will automatically update this pull request. 

Then we should be all set to merge in your code! Let us know if you have any questions. :)

Cheers,
Ann :)

**Comment by carolnourse** [comment]
Hi Ann

I’m not sure what I’ve done there! I think I’ve fixed it now - at least it is showing with my new commit message in Github.

Sorry for the hassle, Ann :)



Not to worry, I don’t mind if you reject the

On 3 Feb 2020, at 17:53, Ann Cascarano <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @carolnourse<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcarolnourse&data=02%7C01%7C%7C7b77a793c0384e60190108d7a8d1fadd%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637163492111958465&sdata=U5MI4cKJ1a40%2BtAFfGLL7WrLS7K2Z2TktAYuIDHSdsA%3D&reserved=0> !

This is really great! The only thing that we need from you is to clean up the merge conflicts markers that were left being in the index.html page. See here.<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fskillcrush%2F105-practice%2Fpull%2F894%2Ffiles%23diff-eacf331f0ffc35d4b482f1d15a887d3bR635-R638&data=02%7C01%7C%7C7b77a793c0384e60190108d7a8d1fadd%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637163492111968488&sdata=PWj2MvfSw3OuvZ7fTiP61ha7rxD9W5h3IwdNn2%2BdYkw%3D&reserved=0>

Once you've made that edit, add and commit the change and then push up your advice branch once more which will automatically update this pull request.

Then we should be all set to merge in your code! Let us know if you have any questions. :)

Cheers,
Ann :)

**Comment by redrambles** [comment]
Hey @carolnourse,

Thanks for making those changes! Your code is all merged in. :)

Cheers,
Ann :)

**Comment by carolnourse** [comment]
Fabulous! Thanks Ann.

Sent from my iPhone

On 5 Feb 2020, at 18:33, Ann Cascarano <notifications@github.com> wrote:

﻿

Hey @carolnourse<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcarolnourse&data=02%7C01%7C%7C675988028f3341f009d008d7aa69eb39%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637165244196106611&sdata=l7uqcMhU%2BgKh0qzTRNzTPPkY4CBqm%2BIgl5f0nj7TDTM%3D&reserved=0>,

Thanks for making those changes! Your code is all merged in. :)

Cheers,
Ann :)

**Pull request merged**
