### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by mikatodd**

### CODE REVIEW

**Comment by mikatodd** [comment]
Hi Sharon!
Thank you for your help on this. I was a little unsure if I did the process correctly on my first pull request. I deleted the folder and file mentioned and pushed the changes. I only see the advice and css folder in my 105-practice directory so I believe it was deleted properly.

**Comment by acodeinprogress** [comment]
Hi!

Ok so there are a couple more changes that you'll want to make here.

First, there is still an extra HTML file in the advice folder called your-name-advice.html that will need to be deleted.

Also, it looks like you deleted the index.html file. We still want that file as part of our repo so you'll need to add that file back in.

Once you do those things, you'll want to run `git add -A` again and then commit and push.

xoxo,
Sharon

**Comment by mikatodd** [comment]
Hi Sharon,

Gotcha! Hopefully I did this correct this time. I remember being a little confused through this lesson so now it makes sense why I have an extra file. Instead of committing and pushing the changes at once, I did them one at a time so hopefully it was resolved. Thank you for your patience and time!

**Comment by redrambles** [comment]
Hey @mikatodd,

Thanks for making those changes - your code is merged in!

Cheers,
Ann :)

**Comment by mikatodd** [comment]
Hooray!!! Thank you Ann!!! :)

**Pull request merged**
