### PR TITLE
added updated advice index page

### PR DESCRIPTION
**Pull request by bluebird5-star**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hi @bluebird5-star,

Congrats on making your first pull request!

I see that you have an extra file in the advice folder, which is called sample-advice0.html.

The other issue is that you deleted the index.html file and we are going to want that back. (You can see the diff of your pull request here if you are curious.)

Once you add the index.html file back and delete the sample-advice0.html file, please add the change with `git add -A`, commit as per usual and push up your branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code. Let us know if you have any questions!

xoxo,
Sharon

**Comment by bluebird5-star** [comment]
Hi Sharon

Thanks but I'm afraid I am struggling with this - I have (or think I have)
deleted the sample-advice0.html from the advice folder and have added back
the index.html - have added and commit the changes - I had a merge conflict
when trying to merge master branch which as far as I am aware is resolved.
I try to  - *git push to origin master*" - but it doesnt seem to work -
I've attached screenshot.   I'm not sure what I'm doing wrong here and
getting quite confused having tried to go back and review things.

Would really appreciate your help/feedback on this.

Thank you
Sandy

**Comment by redrambles** [comment]
Hey @bluebird5-star !

Unfortunately we aren't getting the screenshots on this end - can you please send them to 'questions@skillcrush.com'? We can keep the convo going there! :)

Cheers,
Ann :)

**Comment by redrambles** [comment]
Hey @bluebird5-star ,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Pull request closed without merging**
