### PR TITLE
Cathleen s advice

### PR DESCRIPTION
**Pull request by CathleenSmythe**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @CathleenSmythe !

This is great - there are just 2 things we need from you before we can merge in your pull request.


1) Your advice file is named `advice/cathleen-s-advice.html/cathleen-s-advice.html` - but we want it to be named `advice/cathleen-s-advice.html`. The simplest way to address this is to use your Finder / File Explorer - locate your file inside the nested 'cathleen-s-advice.html' folder that is inside the advice folder and move the file directly inside the advice folder. Then delete the (now empty) 'cathleen-s-advice.html' folder.

2) We still need a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that long list. :)

Once you fix the location of your advice file and add your link to the index.html file, add with `git add -A`, commit as per usual and then push your advice branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by CathleenSmythe** [comment]
I hope I have resolved the issue and now my pull request can be merged.

**Comment by acodeinprogress** [comment]
Hi @CathleenSmythe,

I'm not seeing any changes here. Did you make sure to make them on the advice branch and then push your work to the advice branch on GitHub?

xoxo,
Sharon

**Comment by CathleenSmythe** [comment]
Truly I'm not sure at this point. I thought I followed the advice. I know I did the git add -A and git commit -m "With my message". Perhaps I should have done something else?

**Comment by CathleenSmythe** [comment]
Okay, I followed the directions one more time and pushed it up. Hopefully we are good to go now. Let me know if I'm still missing the mark:(

**Comment by acodeinprogress** [comment]
Hey @CathleenSmythe,

Hmmm I'm still not seeing any changes here.

Can you email a screenshot of your terminal that shows that you added, committed, and pushed your work to GitHub to questions@skillcrush.com so that we can take a look?

xoxo,
Sharon

**Comment by CathleenSmythe** [comment]
Let me know what you see that I left out.
Screen Shot 2021-02-16 at 4 29 43 PM
Screen Shot 2021-02-16 at 4 31 20 PM

**Comment by redrambles** [comment]
Hey @CathleenSmythe  - thanks for those screenshots!

They show us that you still need to push up:

Screen Shot 2021-02-16 at 9 48 04 PM

You'll want to run `git push origin advice` to push your advice branch up to GitHub - and then we'll have your two most recent commits on our end.

Let us know how things go!

Cheers,
Ann :)

**Comment by CathleenSmythe** [comment]
I still see some of the same things you circled even though I typed git push origin advice in terminal. Including my screenshot. Seriously. What am I doing wrong? Should I have done what you first suggested in the first message, THEN the git push origin advice? I will include the screenshot, but try this. Not sure of the order I should be doing this.
Screen Shot 2021-02-17 at 9 20 47 PM

**Comment by CathleenSmythe** [comment]
This is what I did:
Screen Shot 2021-02-17 at 9 28 28 PM
Screen Shot 2021-02-17 at 9 28 44 PM

**Comment by redrambles** [comment]
Hey @CathleenSmythe !

Awesome - your push went through! See how your 'origin/advice' and 'HEAD->advice' markers are next to the same commit in the Terminal? That means that both your local and remote branches are pointing to the same commit, which means that the push was successful.

Your code is merged in!! Yay!!!

Cheers,
Ann :)

**Pull request merged**
