### PR TITLE
Mike L Advice

### PR DESCRIPTION
**Pull request by mlem567**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @mlem567 !

This is great!! The only thing we need is for you to move your `mike-l-advice.html` file into the `advice` directory. Right now it is in the root of the project directory.

Once you make that change, add with `git add -A` - commit as per usual and push up your advice branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by mlem567** [comment]
Hi Ann, I updated the PR. I think I moved mike-l-advice.html. From the root command: git add mike-l-advice.html.  Then I ran git commit -m "Updated html file". Then I ran git push origin advice. I see the PR was updated. 
I think I can tell because the PR says:   mlem567 wants to merge 2 commits into skillcrush:master from mlem567:advice.
Am I reading the PR correctly?
Thanks! 
Mike    On Thursday, July 23, 2020, 10:55:42 AM PDT, Ann Cascarano <notifications@github.com> wrote:  
 
 


Hey @mlem567 !

This is great!! The only thing we need is for you to move your mike-l-advice.html file into the advice directory. Right now it is in the root of the project directory.

Once you make that change, add with git add -A - commit as per usual and push up your advice branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by acodeinprogress** [comment]
Hi @mlem567,

This is almost there! 

It looks like you either didn't delete your advice file in the root folder of this project or you didn't run `git add -A` when you added your changes to the staging area.

Currently, you have two advice files - one in the root folder of the project and one in the advice folder. You'll want to make sure to leave the one in the advice file and remove the one from the root folder.

Give those changes a try and then run `git add -A`, commit, and push. Then we should be able to get this merged in!

xoxo,
Sharon

**Comment by mlem567** [comment]
Hi Sharon, thanks for the input. I found i was editing my mike-l-advice.html from my root and not in the advice directory. doh! i saved my commit and pushed origin advice. Please tell me that did it! Thanks!

**Comment by acodeinprogress** [comment]
Hi @mlem567,

Awesome! Now I see that you have some conflict markers present in the index.html file. You'll need to remove those, then add, commit, and push before we can merge this in.

xoxo,
Sharon

**Comment by redrambles** [comment]
Hey @mlem567 ,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Pull request closed without merging**
