### PR TITLE
Added Melissa M page

### PR DESCRIPTION
**Pull request by ZonaEm**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @ZonaEm !

This is coming along! We have your advice page - but nothing else so far in your pull request. Looks like you meant to include a file `css/melissa-m-advice.css` - and we'll also need a link to your HTML file inside the main `index.html` file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that long list. :)

Once you have done these two things, add and commit your changes and then push your `advice` branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

Once you have made these changes,

**Comment by ZonaEm** [comment]
Ok so I guess that's where I'm lost - I have my CSS file in the css folder of the 105-practice file, in my 'advice' file I have a copy of my HTML and CSS in the correct folders so I should be set...if my 'advice' branch is only my HTML how do I get my CSS to merge too?  
Screen Shot 2020-02-24 at 2 15 14 PM

**Comment by ZonaEm** [comment]
Ok so I updated the index.html and I don't see any changes after fixing the CSS file (rename it to melissa-m-advice.css and link it in my index.html)...I thought I finished my edits, and added, and committed, and merged, but I don't see anything here that looks different. My git log says everything is up to date, my git status does too...where did everything merge to or update to or go?
Screen Shot 2020-02-24 at 2 50 23 PM

**Comment by redrambles** [comment]
Hey @ZonaEm !

In the output of your screenshot, we see that you are attempting to merge the 'advice' branch into itself (you are on the advice branch), which is why nothing happened. We don't really need to through any merges right now, though - we just want to make the changes I outlined in the previous reply and then add and commit those - and lastly push up the advice branch again. 

If you are working on some files and then running `git status` and not seeing that Git has picked up on any changes, I would investigate whether you may be working on a different set of files, perhaps in another location - than the one you are looking at in the Terminal. 

Let us know how things go!

Cheers,
Ann :)

**Comment by redrambles** [comment]
Hey @ZonaEm,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Pull request closed without merging**
