### PR TITLE
105 experiment

### PR DESCRIPTION
**Pull request by GVangberg**
Some advice I'd love to share.

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @GVangberg,

This looks great so far!

There are just a couple changes that you'll need to make before we can merge this in:
1. It looks like you have an extra advice file in the advice folder called new_file.html that doesn't have any content in it, so we'll need to delete that file.
2. We would like for you to include a link to your advice page in the index.html file. 

If you could make those changes, all you have to do is run a slightly different git comment (`git add -A`), commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by GVangberg** [comment]
Hey

Thanks for feedback. I have done the steps but I'm unsure if I did the
'push' step correctly. Does it show up?

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusfri.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Den fre. 26. jul. 2019 kl. 17.31 skrev Sharon <notifications@github.com>:

**Comment by redrambles** [comment]
Hey @GVangberg !

We don't see the change here. Can you try running `git push origin 105-experiment` ? What is the result?

**Comment by GVangberg** [comment]
You can see the result below.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virusfri.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

Den lør. 3. aug. 2019 kl. 21.54 skrev Ann Cascarano <
notifications@github.com>:

**Comment by acodeinprogress** [comment]
Hey @GVangberg,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
