### PR TITLE
Added Erica R's advice page with css and updated index.html with link

### PR DESCRIPTION
**Pull request by ericabross**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @ericabross !

This is looking great!! The only thing we need you to change is to put back two student links that were accidentally deleted in the main index.html file. You can see them here: https://github.com/skillcrush/105-practice/pull/947/files#diff-eacf331f0ffc35d4b482f1d15a887d3bL17-L18

What you can also do is run a fetch from upstream and then  still in your advice branch, run:
`git checkout upstream/master index.html` and then add your link back to the end of the list. 

Once this is fixed up - please add and commit and push up your advice file once more, which will automatically update this pull request. Then we'll be all set to merge in your code!

Cheers,
Ann :)

**Comment by ericabross** [comment]
@redrambles I think I did it right. Thanks for the feedback!

**Comment by redrambles** [comment]
Hey @ericabross !

Ahhhh - so close!! Looks like I missed one more 'missing' student link - right here:
https://github.com/skillcrush/105-practice/pull/947/files#diff-eacf331f0ffc35d4b482f1d15a887d3bL663

Once that one is added back in - we'll be all set!! Sorry for not spotting this one the first time 'round!

Let me know if you have any Qs!

Cheers,
Ann :)

**Comment by ericabross** [comment]
I think I got it this time. *fingers crossed*

Let me know if I missed anyone else. LOL

**Comment by acodeinprogress** [comment]
Hey @ericabross,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
