### PR TITLE
Experiments

### PR DESCRIPTION
**Pull request by tylerthietje**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @Airboater1 !

This is awesome! The only thing is that we cannot accept images as part of student pull requests - as our repo would soon get too large. You are more than welcome to link to an existing hosted image, however! :)

Once you have removed the image and amended the src in your advice file - add these changes, commit and push up your experiments branch once more. This will automatically update your pull request, and we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by Airboater1** [comment]
Hi Ann,

I have removed the image and tried to push the experiments branch again,
but I see the following error:

tyler-thietjes-macbook-pro:105-practice Tyler$ git push experiments

fatal: 'experiments' does not appear to be a git repository

fatal: Could not read from remote repository.


Please make sure you have the correct access rights

and the repository exists.

Could you possibly help me figure out why I am seeing this error, and tell
me what I need to do to get working again?

Thanks,
Tyler

**Comment by acodeinprogress** [comment]
Hey @Airboater1,

This is because our push command should start with the name of our remote repo and then the name of our branch. So right now, it thinks that experiments is your remote repo.

We'll need to change our push command to the following:
`git push origin experiments`

Then that should work!

xoxo,
Sharon

**Comment by Airboater1** [comment]
Hey SHaron,

That seemed to do the trick! I have now pushed my code to the repo and
hopefully you can see it and approve the Pull request. Please let me know
if there are any other issues.

Thanks again for your help!
Tyler

**Comment by acodeinprogress** [comment]
Hey @tylerthietje,

It looks like you added in some extra files in your commit. You can see them by looking at the [Files Changed](https://github.com/skillcrush/105-practice/pull/752/files) tab near the top of this page.

Once that's fixed up, you can add, commit, and push and your changes will join your pull request here.

xoxo,
Sharon

**Comment by tylerthietje** [comment]
I believe I have deleted the extra files and think the pull request should be good to go now. Let me know if that is not the case! 

Thanks!
Tyler

**Comment by acodeinprogress** [comment]
Hey @tylerthietje,

I see that the image is still present in your pull request. I also noticed that you deleted some links to other students' advice pages. You can see these lines highlighted in red on the Files Changed page.

xoxo,
Sharon

**Comment by tylerthietje** [comment]
Hi Sharon,

I guess I am a little confused on what I am doing here! I commented out the
image in my code. Is the image still present when it is commented out? Do I
need to delete it completely from my file?

As for the deleted links, Git was telling me that I had a merge conflict,
so I thought that deleting the links was the way to resolve the conflict.
It seems this was incorrect. How do I roll back to a version of my
index.html file that has the links still in it?

Thanks,
Tyler

**Comment by redrambles** [comment]
Hey @tylerthietje !

Ok! So for the image, you'll need to delete the images folder entirely, which contains the 'advice-banner.png' file.

As for the index.html file - I think that the simplest solution at this point would be to selectively checkout only this file from your updated master branch. So here are the steps

1) Delete your 'images' directory.
2) Move to your master branch
3) Fetch from upstream
4) Merge upstream/master into your master branch
5) Move back to your experiments branch
6) Run `git checkout master index.html`
7) This will overwrite your experiments branch's version of the index.html file with the updated version. Now you'll need to open it in your text editor and add your link, and then save the file.
8) Add all changes with `git add -A` then commit and push up your experiments branch.

We should then be all good and ready to merge in your code. :)

Let us know if you have any questions - we are nearly there!!

Cheers,
Ann :)

**Comment by redrambles** [comment]
Thanks for making those changes, @tylerthietje  - your pull request has been merged in! :)

Cheers,
Ann :)

**Pull request merged**
