### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by Sue-G**
Forking workflow last step

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @Sue-G !
 
This is a great start! We just need a few more things in order to merge this in.

1) Your `sueg-advice.html` file is in the root of the project directory right now - but we need it to be inside the `advice` directory. Please move it in there.

2) We are missing a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that long list. :)

Once you move your file and add your link, add your changes with `git add -A`, commit as per usual and then push your advice branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by acodeinprogress** [comment]
Hi @Sue-G,

Great! I just have 1 more teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by redrambles** [comment]
Hey @Sue-G,

We're getting closer!! Thanks for making those changes. There are just a few little things that remain, and then we'll be all set.

1) Unfortunately we cannot accept images as part of student pull requests, as the repository would soon get too large. You are free to link to a version of the image that is hosted somewhere on the internet, though, of course! :) Please remove the 'img' directory. 

2) There is an extra `Sue-G-advice.html` file that is sitting in the root of the project which needs to be removed.

Once you have made these changes, we should be good to merge in your code. Nearly there!

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by acodeinprogress** [comment]
Hey @Sue-G,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Comment by Sue-G** [comment]
Hi,
I thought I already submitted the pull request and made the necessary
changes.

**Pull request closed without merging**
