### PR TITLE
Added link to christina-l-advice.html

### PR DESCRIPTION
**Pull request by christina-lynn**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @christina-lynn,

This is nearly perfect!

The only thing missing is that it looks like you have a stray `<` on your `<a>` in the index.html file.

Go ahead and try completing that tag with a `br>` after the stray `<`

Once you do that, you'll want to add, commit, and push. Your work will join your pull request here and then we can merge it in.

xoxo,
Sharon

**Comment by christina-lynn** [comment]
Not sure what to do now. I updated my file and then added, committed, and pushed it. But I forgot to make sure I had the newest code from the upstream. So, I got a conflict message. I was worried that if I resolved the code leaving my updated link and erasing the next person's link, their link would disappear or have a conflict. 

So, I tried was going to do everything over agin with the newest code. But I did not go to the advice branch before I added, committed, and pushed my new file. So, I am not sure what my next step would be to fix this.

**Comment by christina-lynn** [comment]
There was a conflict when I completed everything. I resolved it by removing the someone else's link. Was that correct? Or should I have done something different?

**Comment by christina-lynn** [comment]
It showed there were more conflicts. I resolved it by removing my link. I was then going to redo the assignment, but there seems to be a discrepancy between my local files and the remote ones. 

Is it possible to delete my forked and cloned repo and then redo the whole assignment?

**Comment by redrambles** [comment]
Hey there!

Ok! So I see that you have deleted your repository and wish to start from scratch - that's ok, though we really didn't have to do that here. In any case - I'm going to close this pull request and give you some time to make a new one. Let us know if you have any questions! :)

Cheers,
Ann :)

**Pull request closed without merging**
