### PR TITLE
commit changes

### PR DESCRIPTION
**Pull request by AmithaMurali84**
back ground image added

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @AmithaMurali84 !

This is a good start! We have the link to your `advice/amitha-m-advice.html` file in the main index.html file - but the advice file itself is missing from your pull request. Does it still need to be added and committed?

Once it is, you'll want to push it up with `git push origin advice` - which will automatically update this pull request. Then we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by redrambles** [comment]
Hey @AmithaMurali84 !

Awesome! We have your advice file, but unfortunately it is sitting in the root of the project folder rather than inside the advice folder. We need you to move it into the advice folder, then add the change with `git add -A` - commit as per usual and push up your advice branch one more time.

Then we should be all set.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by acodeinprogress** [comment]
Hey @AmithaMurali84,

Thanks for making that change! In the process, it looks like there are some other changes that are needed:

1. There is an extra your-name-advice.html.zip in this project
2. An image was added to the project. Unfortunately we cannot accept images in this repository - as it would quickly become too large. You can definitely link to existing online images, though! :)

Once you make those changes, you'll need to run `git add -A`, commit, and push, your changes will join your pull request here.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @AmithaMurali84,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
