### PR TITLE
ADDING KELHAMS ADVICE PAGE

### PR DESCRIPTION
**Pull request by kscliffe**
Advice I would like to share

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @kscliffe,

This looks great so far! There are just a couple changes that you'll need to make before we can merge this in:

1) You added in a normalize.css file. This file isn't necessary in this case because we are just having you practice your own HTML, CSS, and Git skills. If you could remove that file, that would be great!

2) I see that you added an image to the project. Unfortunately we cannot accept images in this repository as it would quickly become too large. You can definitely link to existing online images, though! :) Please remove your image file and update your image links in your advice page. 

Once you make those changes, you'll need to run a slightly different git command (git add -A), commit, and push, your changes will join your pull request here.

xoxo,
Sharon

**Comment by kscliffe** [comment]
Hey Sharon,

I made all the amendments you requested.

I'm not sure if i was supposed to try and merge, I think I may have gone a step too far? I'm still getting to grip with each of the steps. I've not had a lot of free time this last week so it's been few days in-between which is enough time to forgets bits apparently.

I appreciate your help.

Thanks,
Kelham

**Comment by acodeinprogress** [comment]
Hey @kscliffe,

Thanks for making those changes!

It looks like in the process, you added some repeat lines in the index.html and there isn't a link in that file that directs users to your personal advice page. You can see the lines that were added in green by looking at the index.html file in the [Files Changed](https://github.com/skillcrush/105-practice/pull/377/files) tab near the top of this page.

Once you remove those extra lines and add in a link of your own, you can once again add, commit, and push.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @kscliffe,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
