### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by williamowen65**
This was a fun project

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @williamowen65 !

Glad you are having fun with this project!! This is a great start - but there are a few little things we'll need you to address before we can merge this in.

1) Unfortunately we cannot accept images as part of student pull requests, as the repository would soon get too large. You are free to link to a version of the image that is hosted somewhere on the internet, though, of course! :) Please delete your image file.

2) You have committed two separate CSS files - one which you aren't using: `css/william-owen.css` - please delete it.

3) An additional file with the name of `your-name-advice.html/william-owen-advice.html` has joined your pull request - which we don't need - please delete this also.

Once you have made these changes, add with `git add -A`, commit as per usual and then push up your `advice` branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code! Let us know if you have any questions!

Cheers,
Ann :)

**Comment by williamowen65** [comment]
Thanks Ann,

Those extra files are embarrassing, but a good learning lesson for me to back up and retrace my steps. I found all three files you mentioned and tried to figure out how to delete them.

I first looked on Github but deleting those files didn't appear obvious. Then I went to my command line, opened my explorer and deleted those files. Then on the CL used git add -A, git commit -m "Deleted files", git fetch upstream, git push origin master.  My github repo is still holding on to those files.

Do you have any guidance?

**Comment by acodeinprogress** [comment]
Hey @williamowen65,

It looks like you made those changes on your master branch and then pushed to your master branch. Since each pull request is specific to the branch that you originally made it for, you'll need to make those same changes on your advice branch before they will show up here.

xoxo,
Sharon

**Comment by redrambles** [comment]
Hey @williamowen65 ,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Pull request closed without merging**
