### PR TITLE
Added my name

### PR DESCRIPTION
**Pull request by onecruz**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @onecruz !

This is a good start! Just a few things:

1) We see a file called `steven-c-advice.html` as part of this pull request -but right now it is inside the root of the project directory. We need it to be inside the `advice` directory - so please move it in there.

2) We are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that long list. :)

Once you move your advice file and add your link, add and commit your changes and then push your advice branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by onecruz** [comment]
> Hey @onecruz !
> 
> This is a good start! Just a few things:
> 
> 1. We see a file called `steven-c-advice.html` as part of this pull request -but right now it is inside the root of the project directory. We need it to be inside the `advice` directory - so please move it in there.
> 2. We are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that long list. :)
> 
> Once you move your advice file and add your link, add and commit your changes and then push your advice branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!
> 
> Let us know if you have any questions!
> 
> Cheers,
> Ann

Can you guide through the steps please? I'm still a little confused on the process.

**Comment by redrambles** [comment]
Hey @onecruz !

Ok - you'll just want to do as I described in my previous reply.

First, move into your repository in the Terminal and make sure that you are on your advice branch:

`git checkout advice`

Next, open up the folder in  your Finder / File Explorer, find your `steven-c-advice.html` file and drag it into the advice folder.

Then open up the index.html file in your text editor of choice, and add your link to your advice file somewhere in that long list. You can see what other students have done there and do the same - but with your name and a link to your advice file.

Once that's done - back in the Terminal add your change with `git add -A` - then commit as per usual and finally push up your advice branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code. Keep us posted on your progress!

Cheers,
Ann :)

**Comment by redrambles** [comment]
Hey @onecruz ,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Pull request closed without merging**
