### PR TITLE
Added Elizabeth G file

### PR DESCRIPTION
**Pull request by e-gunn**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @e-gunn !

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that long list. :)

Once you add your link, add and commit your changes and then push your advice branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by e-gunn** [comment]
Hi Ann, 

I had already added my link to index.html. I went back and did the following in the 105-practice directory (advice branch):

1. git add index.html
2. git commit -m "Added Elizabeth G link to advice page"
3. git push origin advice 

Did I understand this request correctly?

**Comment by redrambles** [comment]
Hey @e-gunn ,

Yes you did understand the request correctly and thank you for adding that file!! The last little thing that I see here is that you are referencing a `css/elizabethg-advice.css` file from your advice file - but there is no such file in your pull request. Perhaps it still needs to be added, committed and pushed? If you prefer to link to the backup 'css/style.css' stylesheet instead (which is free for anyone to use) - you can edit your link in your advice file to point to it. 

Whichever your preference, when you have finished your changes, please add and commit and push up your advice branch once more in order to update this pull request - and we should be good to go.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by redrambles** [comment]
Hey @e-gunn !

Thanks for making those changes, your code is merged in! 🎉

**Comment by e-gunn** [comment]
Great! Thanks for walking me through it Ann.

**Pull request merged**
