### PR TITLE
Reworked the links for Advice Elizabeth G-A

### PR DESCRIPTION
**Pull request by elizgrigand**

### CODE REVIEW

**Comment by elizgrigand** [comment]
Hello,

I went back in to check links. I found an error and corrected it, creating a new pull request. 

Thank you! 

-Elizabeth G-A

**Comment by acodeinprogress** [comment]
Hey @elizgrigand,

I see that you closed that pull request. How would you like to proceed with this assignment?

xoxo,
Sharon

**Comment by elizgrigand** [comment]
Hello,

I set up a different pull request because I had to rework so much, it was different. You can see it at: [https://github.com/skillcrush/105-practice/pull/1755]

**Comment by elizgrigand** [comment]
Hello Sharon, 

This is the pull request. 
Thank you for your time. 

Truly,
Elizabeth

**Comment by acodeinprogress** [comment]
Hey @elizgrigand,

Great!

There are just a few small changes needed here as well.

There are some conflict markers present in the index.html file that you'll need to remove. Once those have been deleted, you can add, commit, and push your work and your changes will join your pull request here.

xoxo,
Sharon

**Comment by elizgrigand** [comment]
Hi Sharon! 

Thank you so much. It should be ready to go. Thank you for the support.
Best,
Elizabeth

**Comment by elizgrigand** [comment]
Sharon, just let me know if there is anything else I need to add. 
Thanks so much!

Best, 
Elizabeth

**Comment by redrambles** [comment]
Hey @elizgrigand!

We are close here! Just a few things before we can merge this in.


1) You have added a file called `css/elizabeth-g-a-advice.css`, which is great - but you aren't linking to it from your advice file - please add a link to your custom css file in your `advice/elizabeth-g-a-advice.html` file.

2) There are many conflict markers inside the main index.html file - so let's do a bit of a 'do over' for that particular file. Once you are done with the first item I listed above, let's fetch from upstream:
`git merge upstream`

And then let's checkout only the index.html file from the upstream/master branch, so that it can be a copy of what is in the main code base:

`git checkout upstream/master index.html`

Now open up the index.html file and add a link to your advice file once more - somewhere inside that long list.

Once you have done this, add your changes with `git add -A` - then commit as per usual `git commit -m "Your message here"` and finally push up your advice branch once more: `git push origin advice` - and we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by redrambles** [comment]
Hey @elizgrigand !

Did you have any trouble with the steps detailed above? Let us know how we can help!

Cheers,
Ann :)

**Comment by elizgrigand** [comment]
Hi,
Thanks for asking.

I don’t want to go on slack. I feel really uncertain.

I don’t know why I don’t understand where I got it wrong.

Yes. I feel really frustrated because I had no trouble when I took the
class before.

I am just trying and then it is like a week before I hear back. So then
everything is off and needs correction. Then when I redo it it is worse.

I am just trying to understand. I will get it.
...

**Comment by redrambles** [comment]
Hey there! 

Ok! If you'd like us to walk through this in a Dev Q&A - we can do that then if you like as well! Sometimes it's nice to have a face to face and a screen share to clear things up. You can register on our events page any time! If you'd prefer another solution, please e-mail us at 'questions@skillcrush.com' and we'll work something out.

Hang in there!

Cheers,
Ann :)

**Comment by acodeinprogress** [comment]
Hey @elizgrigand,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
