### PR TITLE
Updated HTML file to have my name and comments, added personal CSS, a…

### PR DESCRIPTION
**Pull request by KateAckerman**
…dded link on Main Index.html

### CODE REVIEW

**Comment by redrambles** [comment]
Hello @KateAckerman !

This is coming along! There are two things that we need to address before  we can merge this in.

1) We cannot accept image files, as it would soon make our repository too large. You are free to link to an existing image online, though! Please remove the `img/dsc03339.jpg` file (and the `img` folder).

2) Seems as though a few students' links were removed in the main index.html file ([see here)](https://github.com/skillcrush/105-practice/pull/868/files#diff-eacf331f0ffc35d4b482f1d15a887d3bL17). (The lines in red were deleted.) We'll need to add those lines back in. The easiest way to go about this is the following:

a) While in your advice branch, open up your index.html file and copy the link to your advice file.
b) In the Terminal / Git Bash, run the following: `git checkout master index.html`. This will overwrite your current index.html file in your advice branch with the version of the same file on the master branch - replacing all the accidentally deleted student links in one fell swoop. 
c) Open up your index.html file again and paste your link at the top of the list and save the file.


Once you have made changes detailed in both '1' and '2' - please add `git add -A` and commit `git commit -m "your message here"` and push up your branch once more `git push origin master` - which will automatically update this pull request. Then we'll be all set to merge in your code!

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by KateAckerman** [comment]
Hi Ann,

I think I have followed the steps correctly... but an not seeing an updated
pull request on GitHub.

Thanks, Kate

**Comment by redrambles** [comment]
Hey @KateAckerman !

Ah yes! I just edited my previous reply as the last command we want to run is `git push origin advice` - and not `master` - because the advice branch is the one we want to update on GitHub. Can you run that last command please?

Cheers,
Ann :)

**Comment by KateAckerman** [comment]
okay let me know if that worked!

**Comment by redrambles** [comment]
Hey @KateAckerman !

Thanks for making that change - everything is perfect! Your code is merged in. :)

Cheers,
Ann :)

**Comment by KateAckerman** [comment]
Great thanks!

**Pull request merged**
