### PR TITLE
Replaced sk name with my name added advice styled css

### PR DESCRIPTION
**Pull request by AmandaJudd**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @AmandaJudd !

Everything is good here except that unfortunately we cannot accept images as part of student pull requests, as the repository would soon get too large. You are free to link to a version of the image that is hosted somewhere on the internet, though, of course! :)

Once you have removed the images, please add with `git add -A` and commit as per usual, then push up your `advice` branch once more, which will automatically update this pull request. 

Then we should be all set to merge in your code. Let us know if you have any questions!

Cheers,
Ann :)

**Comment by AmandaJudd** [comment]
Thanks Ann,

I removed the image and followed your other prompts.  I will wait in hopes
that all is set to merge in my code now.

Amanda

**Comment by AmandaJudd** [comment]
Hey - I've decided to move forward in the lessons (quiz, etc.) while I wait
on the acceptance of the merge.  I pray this will be okay and not cause
issue.

Take care,
Amanda

**Comment by acodeinprogress** [comment]
Hey @AmandaJudd,

I see that you removed the images from the CSS but you didn't remove the actual image files or the `img` folder from this project.

Please go ahead and remove those and then we can get this merged in!

xoxo,
Sharon

**Comment by AmandaJudd** [comment]
Good evening,

Thank you for the additional guidance.  I have, now, deleted the img folder
and the image files in it.

Take care,

Amanda

**Comment by acodeinprogress** [comment]
Hi @AmandaJudd,

Great! I'm not seeing those changes here so you'll need to make sure to also run `git add -A`, commit, and push your work up to GitHub.

xoxo,
Sharon

**Comment by AmandaJudd** [comment]
Good morning!

Okay, the commit and push is completed.

Thanks so much,
Amanda

**Comment by redrambles** [comment]
Hey @AmandaJudd !

Thanks for making those changes - your code is merged in!

Cheers,
Ann :)

**Comment by AmandaJudd** [comment]
Thanks!

**Pull request merged**
