### PR TITLE
attempt #2 - Merged updated master branch into the advice branch

### PR DESCRIPTION
**Pull request by Asanag10**
Thank you so much, Ann! I think it worked this time. Please advise.

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @Asanag10 !

This is really close! The only thing we need to remedy is that changes were made to the main css files (css/style.css), which we don't want. Let's return that file to its previous state.

In the Terminal, still in your advice branch - run the following:

`git checkout master css/style.css`

This will replace the edited version of that file with the original version.

Then you'll want to add `git add -A`, commit `git commit -m "Remove accidental edits"` and then push up your advice branch once more `git push origin advice`.

Then we should be all set to merge in your code. Let us know if you have any questions!

Cheers,
Ann :)

**Comment by Asanag10** [comment]
[image: image.png]

Thank you, Ann! I'll get on it now. I'm determined to get this right.

**Comment by Asanag10** [comment]
Hi Ann,

I followed your instructions and see the push reflected in Github. Please
advise.

   -
   https://github.com/skillcrush/105-practice/pull/1091/commits/0beaa1b05d7325d8cc00d2e016917200eb80acb1




Thank You,
Asana

**Comment by acodeinprogress** [comment]
Hi!

Thanks for making that change!

I see that you added some images to the project in your latest commit. Unfortunately we cannot accept images in this repository - as it would quickly become too large. You can definitely link to existing online images, though! :)

Please remove your `img` directory with the images inside, and update your image links in your advice page. 

Then you'll need to run `git add -A`, commit, and push, your changes will join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by Asanag10** [comment]
Thank you, Sharon. I'm sorry for all of the back and forth. I will remove
the additional images and will proceed as advised.

**Comment by Asanag10** [comment]
Good Morning!

I've removed my image folder and replaced the image link in my advice page.
Please review the recent update to my pull request and advise.

   -
   https://github.com/Asanag10/105-practice/commit/cceb691b1febe53f170fb99f5e88d02f045db12c



Thank you for your help!



Asana

**Comment by redrambles** [comment]
Awesome!! We're all good, @Asanag10  - your code is merged in!

Cheers,
Ann :)

**Comment by Asanag10** [comment]
Yay! Praise God! I don't know why that was so painstaking! LOL 😩😊
I really need to revisit that assignment and figure out where I went wrong.
Thank you!!

**Pull request merged**
