### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by ranmac2**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @ranmac2 !

This is good! We just have two things to address before we can merge this in.

1) You have an additional HTML file in your pull request: `advice/randall-m-advice.html`. Please remove it.

2) You have a few conflict markers that still need to be deleted in the main index.html file - next to where you added your link. Please remove the conflict markers.

When you have made those changes - please add with `git add -A` - the commit `git commit -m "Removed additional file and conflict markers"` (or message of your choice) and push up your advice branch once more `git push origin advice`. This will automatically update your pull request, and we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by acodeinprogress** [comment]
Hi @ranmac2,

Thanks for making that change! It looks like in the process of removing the merge conflict markers, you also deleted a lot of links that other students had added to the index.html file. We will need to add those links back in so that we preserve everyones work.

Once that's fixed up, you'll need to add, commit, and push your work again.

xoxo,
Sharon

**Comment by ranmac2** [comment]
I'm beyond confused on how I'm supposed to do that. I thought I deleted the conflict markers only, but now I see on the gitbash log there were 280 deletions??? I ran the gitlog to get the hash of the commit before the changes to try it again. I've only removed the additional html file, I see no conflict markers, and when I committed the deletion of the html file again, I see there are now 39 deletions?? Can you please offer some assistance?

Thank you

________________________________

**Comment by redrambles** [comment]
Hey @ranmac2 !

Ok no worries. There are a few ways that you could resolve this.

1) You could visit the original code base here: https://github.com/skillcrush/105-practice - open up the index.html file and copy everything inside it. Then you can paste it inside your own index.html file - and add your own link at the bottom of the link.

2) Because this is Git - there is an easier way! You can replace the version of the index.html file that exists inside your advice branch with the one on the master branch with this command:

`git checkout master index.html`

And then you can open up the file in your text editor and add your link at the bottom of the list.

Once you have chosen and executed either one of the above options - make sure to save your file - then in the Terminal add with `git add -A`, commit `git commit -m "Your message here"` and then push up your advice branch one more time `git push origin advice`. This will update your pull request and we should then be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by acodeinprogress** [comment]
Hey @ranmac2,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
