### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by speakerwire**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @speakerwire ,

You did a great job and your code is all merged in! Yay!

Cheers,
Ann :)

P.S - I love your username :)

**Comment by speakerwire** [comment]
Hey Ann, 

      I am trying to get to my dashboard in Wordpress and found my login password is not recognized nor are my emails so I am not getting the reset link?  Do you have any suggestions for me?

Regards,

Ian

**Comment by speakerwire** [comment]
Nevermind Ann, I literally just now got it to work for me.. 

False Alarm..

**Comment by speakerwire** [comment]
Oh I just read the ps you wrote thanks! 

So I am setting up the 203-accelerate site cloned it into my sites folder right next to the old Wordpress folder with all the same files in it and created a new database named accelerate and when I go to install Wordpress on the new site it tells me I already have it installed and gives me the option to login which I did only for it to put me into my dashboard for the old site.  I assume I need to lookup how to do concurrent installs of Wordpress so I can get a fresh dashboard and database.  

Can you help  me with this?

**Comment by redrambles** [comment]
Hey @speakerwire - You'll want to e-mail in this question to 'questions[at]skillcrush.com' and we can dive into it there. This thread is just for your 105-practice project's pull request. :)

I'll be looking out for your e-mail!

Cheers,
Ann :)

**Pull request merged**
