### PR TITLE
Version1

### PR DESCRIPTION
**Pull request by awithall**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @awithall,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by awithall** [comment]
Hi Sharon,

I added the link and committed the changes. I used the git push command and got an "Everything is up to date" message locally. I'm not seeing any updates here though. What have I missed?

Thanks,
Ashleigh

**Comment by acodeinprogress** [comment]
Hey @awithall,

Did you make sure to make your changes on your `version1` branch and then push to your `version1` branch on GitHub?

xoxo,
Sharon

**Comment by awithall** [comment]
Did this come through properly?

Thanks,
Ashleigh

**Comment by acodeinprogress** [comment]
Hey @awithall,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
