### PR TITLE
James Hickey Advice

### PR DESCRIPTION
**Pull request by jghickeyiii**
James Hickey Advice

### CODE REVIEW

**Comment by redrambles** [comment]
Hello @jghickeyiii !

I see that you have added a link to the main index.html file - but neither your advice HTML nor your advice CSS are included in this pull request. Perhaps these two files still need to be added and committed locally? When you have done so, just push up your branch once more (`git push origin experiment`) - and this will automatically update your pull request.

Then we should be all set to merge in your code! Let us know if you have any questions.

Cheers,
Ann

**Comment by jghickeyiii** [comment]
Hey Ann,

I think that I’ve got it sorted out now - let me know if it’s good to go!

Thanks,

James G. Hickey

**Comment by acodeinprogress** [comment]
Hey @jghickeyiii,

I'm not seeing any changes here. Did you make sure to make those changes on your experiment branch on your computer and then push to the experiment branch on GitHub?

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @jghickeyiii,

I'm going ahead and closing this pull request.

xoxo,
Sharon

**Pull request closed without merging**
