### PR TITLE
Experiments

### PR DESCRIPTION
**Pull request by zhylosa**
Advice that I would like to add.

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @zhylosa,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by zhylosa** [comment]
I have added a entry in the index.html file.  Please review again.

**Comment by acodeinprogress** [comment]
Hey @zhylosa,

Awesome! Thanks for adding that in.

Unfortunately, it looks like merge conflict markers (`<<<<<<< HEAD`, `=======`, `>>>>>>> master`) in the index.html file. You can see where they are located by looking at the [Files Changed tab](https://github.com/skillcrush/105-practice/pull/358/files) near the top of this page. You can also see that there is an extra line (`<a href="advice/coriannrix-advice.html" target="_blank">Coriann's Advice</a><br>`).

Once you remove those extra things, you can add, commit, and push again and then we can get this merged in.

xoxo,
Sharon

**Comment by redrambles** [comment]
Hey @zhylosa ,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Pull request closed without merging**
