### PR TITLE
Updated advice page

### PR DESCRIPTION
**Pull request by jen-neu**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @jen-neu,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by jen-neu** [comment]
Hi Sharon,

I’m not sure what I didn’t do right. I had the link in my index.html file already. Yikes.

So I did:
Git add index.html
Git commit -m “Added link to advice page”
Git push origin master

Not sure if this is what you meant.

Cheers,
Jen

Sent from my iPhone

On Jul 30, 2020, at 8:09 PM, Sharon <notifications@github.com> wrote:

﻿

Hey @jen-neu<https://github.com/jen-neu>,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hi Jen!

Yes, that is super close! It looks like you pushed your changes to the master branch but this pull request is for the advice branch.

In order for your changes to show up here, you'll need to make them on your advice branch and then push to your advice branch instead of master branch.

Once you do that, it should appear here and we can get it merged in.

xoxo,
Sharon

**Comment by jen-neu** [comment]
Hi Sharon, 
I just tried to add my index.html file and I got this message...
         Untracked files:
          (use "git add <file>..." to include in what will be committed)
                  css/jen-n-main.css
           nothing added to commit but untracked files present (use "git add" to track)


Thanks in advance for your help!
Jen

Screenshot (77)

**Comment by acodeinprogress** [comment]
Hi @jen-neu,

Thanks for that screenshot! There are a couple different things happening here.

First, you are on your advice branch. In order to update this pull request, you'll need to make your changes on your advice branch.

Being on the right branch may clear up the other issue but if it doesn't, let us know.

xoxo,
Sharon

**Comment by redrambles** [comment]
Hey @jen-neu ,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Pull request closed without merging**
