### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by bjhahn**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @bjhahn !

Love your advice!!! Everything is good here except that unfortunately we cannot accept images as part of student pull requests, as the repository would soon get too large. You are free to link to a version of the image that is hosted somewhere on the internet, though, of course! :) 

Once you have removed the 'graphics' folder - please add this change with `git add -A` - then commit as per usual and push up your advice branch once more, which will automatically update this pull request. Then we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by bjhahn** [comment]
I got a gitbash message saying everything up to date. Is that what tells me the pull request is updated?

**Comment by redrambles** [comment]
Hello @bjhahn,

Not necessarily. We didn't receive any updates on our end - so that usually means that either the 'advice' branch wasn't pushed (`git push origin update`) or that you are working on a different branch. Do either of these scenarios seem likely?

**Comment by acodeinprogress** [comment]
Hi @bjhahn,

Unfortunately we aren't able to see that image. Can you please try emailing it to questions@skillcrush.com?

xoxo,
Sharon

**Comment by bjhahn** [comment]
Sharon,

I just sent the image as an attachment to questions@skillcrush.com.

Thanks,
BJ

________________________________

**Comment by redrambles** [comment]
Hey @bjhahn !

This is perfect! Thanks for making those changes, your code is merged in!

Cheers,
Ann :)

**Pull request merged**
