### PR TITLE
Added Rebecca S.'s advice page

### PR DESCRIPTION
**Pull request by beckstone**

### CODE REVIEW

**Comment by beckstone** [comment]
Ann, 
If you see this, can you confirm that I have corrected the situation and indeed added my link to the advice page now?

**Comment by acodeinprogress** [comment]
Hey @beckstone,

I'm not seeing any changes on here. Did you make sure to add, commit, and push your changes up to your advice branch on GitHub?

xoxo,
Sharon

**Comment by beckstone** [comment]
Can you see changes now?

**Comment by redrambles** [comment]
Hey @beckstone,

Yes! Thanks for making those changes - your code is merged in. Yay! 👍 

Cheers,
Ann :)

**Comment by beckstone** [comment]
Yay, indeed! Thank you!

**Pull request merged**
