### PR TITLE
personalization

### PR DESCRIPTION
**Pull request by sdexter91**
Submitting my first pull request! Here I personalized the sample code provided a bit.

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @sdexter91,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by sdexter91** [comment]
Hi Sharon,

Apologies for the delay on this -- I think I got it figured out! Not sure
if I "pushed" correctly though, so the changes might not have been updated
on my pull request.

Let me know if it worked!

Thank you,
Sam

**Comment by redrambles** [comment]
Hey @sdexter91 - you did great!! 

Thanks for making that change, your code is all merge in! Yay! :)

Cheers,
Ann :)

**Comment by sdexter91** [comment]
Awesome!! Thank you Ann :)

**Comment by sdexter91** [comment]
Awesome!! Thank you Ann :)

**Pull request merged**
