### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by Umudouma**
Merging edited advise page

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @Umudouma !

This is great! In your advice file, you link to a `css/ubong-advice.css` file - but this file isn't part of your pull request. We got your advice page and the link to it in the index.html - but no CSS. You don't need to include any CSS as part of this assignment - but I wanted to make sure that you hadn't accidentally forgotten to add and commit the file - or push it up.

If you want to include that file - please add and commit it - otherwise please remove the link to it from the head of your `advice/ubong-u-advice.html` file. Then push up your `advice` branch once more, which will automatically update this pull request - and we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by Umudouma** [comment]
Thank you for your  feedback.

I really thought my css file was part of the pull request. Just found out i
deleted it by mistake. i will update it. Thank you

**Comment by Umudouma** [comment]
I have pushed the updated version with css. Please let me know if am making
sensing. Hopefully am starting to get a hang of this.

**Comment by acodeinprogress** [comment]
Hey @Umudouma,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
