### PR TITLE
V2.0

### PR DESCRIPTION
**Pull request by KBjornV**
Here's my advise, thanks

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @KBjornV !

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. If you're not sure how to do this, feel free to take a look at other students links for reference. :)

Once you add your link, add and commit your changes and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by KBjornV** [comment]
Thanks so much, I missed the steps of submitting a pull request to myself and merging my forked versions.  I just submitted another pull request to y'all.  So it all should be on there now.  Please let me know.

take care,
________________________________

**Comment by redrambles** [comment]
Hey there - I'm closing this pull request given that you opened another. :)

**Comment by KBjornV** [comment]
ok, was I not supposed to open another pull request.

I thoughts that what I needed to do to update with my corrected code.
________________________________

**Comment by KBjornV** [comment]
Here's the other email I sent and didn't hear back on

thanks
________________________________

**Pull request closed without merging**
