### PR TITLE
Beckstwocents

### PR DESCRIPTION
**Pull request by tbecks513**
Successful push! Now to try a pull request.

### CODE REVIEW

**Comment by tbecks513** [comment]
Batting a 1000!

**Comment by acodeinprogress** [comment]
Hey @tbecks513,

This is great so far! There are just a few minor tweaks that you'll need to make before we can merge this in:

1. `deskimage` It looks like you're referring an image that hasn't been added to this project. We do want to keep this project as clean as possible so we don't want to add any images to it. Instead, you can host them publicly on an image hosting site and then link to them instead.
2. There is an extra advice file called `beckstwocents` that is empty. You can see this file by looking in the [Files Changed](https://github.com/skillcrush/105-practice/pull/3/files) tab near the top of this page. You'll need to delete this file.
3. We'll also need a personal stylesheet where you'll add some files.
4. We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. 

Once you do that, you'll need to run a slightly different git command (`git add -A`), commit, and push. Your changes will join your pull request here and then we can get it all merged in.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @tbecks513!

Thanks for making that change! Now we need to complete the rest of the points in the email above (1, 2, and 4). I'll include them here for easy reference:

1. deskimage It looks like you're referring an image that hasn't been added to this project. We do want to keep this project as clean as possible so we don't want to add any images to it. Instead, you can host them publicly on an image hosting site and then link to them instead.
2. We'll also need a personal stylesheet where you'll add some files.
3. We would like for you to include a link to your advice page in the index.html file.

Once you do that, you'll take the same steps that you took previously (add, commit, and push) and then we can get this merged in!

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @tbecks513,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
