### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by JenKP**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @JenKP !

This is a great start!! The only thing I see here is that you are referencing a stylesheet named `jen-kp-style.css` in your advice file - but there is no such file as part of this pull request. If you meant to add one, please add it to the 'css' directory and update your link in your advice file to `css/jen-kp-style.css`.

Then add your changes with `git add -A` commit as per usual and finally push up your `advice` branch once more, which will automatically update this pull request. Then we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by JenKP** [comment]
Hi Ann,

Thanks - I have added the CSS - not sure how it ended up in there! But - ack! I can't seem to find my advice html file anywhere on my comp. It's gone. I'm in the command line trying to fix this. Can I get it back through GH?

Eek,
Thanks - learning a ton!
Jen

________________________________

**Comment by redrambles** [comment]
Hey @JenKP !

I see your advice file here - it's at `advice/jen-kp-advice.html`. Right now it is linking to a stylesheet (`jen-kp-style.css`) that doesn't exist. Have a look at the PR view here: https://github.com/skillcrush/105-practice/pull/1641/files

It is totally fine if you'd rather not hunt for your CSS file or create it again (it isn't on GitHub, alas) - you can just link to the 'main', sort of 'backup' css file that we make available to all students '../css/style.css'. 

Otherwise you can create your css file - add it inside the /css directory and then link to it from your advice file.

Does this make sense? Let us know if you have any questions!

Cheers,
Ann :)

**Comment by acodeinprogress** [comment]
Hey @JenKP,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
