### PR TITLE
Christine M's Advice page 

### PR DESCRIPTION
**Pull request by hellochristinemoore**
Added personalized advice.html, christine-m.css file, normalize.css and img folder

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @hellochristinemoore !

Everything is good here except that unfortunately we cannot accept images as part of student pull requests, as the repository would soon get too large. You are free to link to a version of the image that is hosted somewhere on the internet, though, of course! :)

Once you make that change, add with `git add -A` and commit as per usual - and then push up your advice branch once more - which will automatically update this pull request. Then we should be all set to merge in your code! :)

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by acodeinprogress** [comment]
Hey @hellochristinemoore,

Thanks for making those changes!

It looks like our image is still present in our repo so you'll need to go ahead and remove that.

I also see some conflict markers in some of our files (`<<<<<<< HEAD`, `=======`, `>>>>>>> upstream/advice`) that we'll need to remove.

If you need help locating them, you can check out the [Files changed](https://github.com/skillcrush/105-practice/pull/1020/files) tab near the top of this page.

Once you make those changes, you'll need to make sure to run `git add -A`, the commit and push.

xoxo,
Sharon

**Comment by hellochristinemoore** [comment]
Hi Sharon & Ann,
Thank you for patience whilst I am still battling to master this beast :) I really, really hope this commit is good to go. Otherwise, I'll definitely have to redo this chapter (face palm emoji). Looking forward to your response!
Best, Chris x

**Comment by redrambles** [comment]
Hey @hellochristinemoore !

Thanks for making those changes - everything looks good here. Your code is merged in!

Cheers,
Ann :)

**Pull request merged**
