### PR TITLE
edit advice and add name to list

### PR DESCRIPTION
**Pull request by C8Design**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @C8Design,

I noticed that you didn't add an advice page or any css. If you could add those things, that would be great! Once you do that, you can add, commit, and push your work and it will join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by C8Design** [comment]
Hi Sharon! 

Do I add my file alone or the whole folder with everyone's files (for both advice page and css)? On my computer I had dragged my advice file to the advice folder. The link in the name list does open the advice file locally, though as you said it's different on github.
I have trouble with adding to GitHub and I think I'm getting better with practice.

Caitlin

**Comment by acodeinprogress** [comment]
Hi @C8Design,

All the other files should already be there. You'll just want to add your own advice HTML and CSS files.

When you added your advice file, did you verify that you were on the advice branch and make sure that you pushed to your advice branch on GitHub?

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @C8Design,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
