### PR TITLE
Mcgurk 101

### PR DESCRIPTION
**Pull request by mauramcgurk**
Hello,
I'm submitting my html and css files for the Newbie Advice page.
Thanks and Cheers!
Maura

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @mauramcgurk,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by mauramcgurk** [comment]
Thank you Sharon! I thought it would be a quick fix, but I ended up committing to the wrong branch (of a different project even!), and I'm having a hard time sorting it out. I'm working on this, so please don't close the pull request in the meantime. Thank you, Maura________________________________________________________________________________


-------- Original Message --------
Subject: Re: [skillcrush/105-practice] Mcgurk 101 (#231)

**Comment by acodeinprogress** [comment]
Hey @mauramcgurk,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Comment by mauramcgurk** [comment]
Yay! Thank you so much for the news, and for your help!Cheers!Maura________________________________________________________________________________To stay current on new work and exhibitions, please join my mailing list (and I never share your info)! 


-------- Original Message --------
Subject: Re: [skillcrush/105-practice] Mcgurk 101 (#231)

**Pull request merged**
