### PR TITLE
my changes

### PR DESCRIPTION
**Pull request by CoastalGirl**
The advice I wish to share.

### CODE REVIEW

**Comment by CoastalGirl** [comment]
Hoping I get it right this time!

**Comment by acodeinprogress** [comment]
Hey @CoastalGirl,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by CoastalGirl** [comment]
Fixed the index so hoping it is good to go.

**Comment by acodeinprogress** [comment]
Hey @CoastalGirl,

Thanks for making that change! This is alllmost there!

It looks like when you added your link, you removed a `>` from our `<div class="skillcrush">` and your `<br>` is missing a closing `>` as well.

Once you fix those up, you can add, commit, and push again and then we'll get this merged in!

xoxo,
Sharon

**Comment by redrambles** [comment]
Thanks for making those changes, @CoastalGirl !

Your code is all merged in! :)

Cheers,
Ann

**Pull request merged**
