### PR TITLE
Added Daniel T Advice

### PR DESCRIPTION
**Pull request by Dtrules19**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hi @Dtrules19,

This is looking great! I just have one teeny tiny change that you'll need to make before we can merge this in.

It looks like you add an extra file called .Rhistory in our css folder. You'll need to remove that file.

Once you do that, you can `git add -A`, commit, and push. Your changes will join your pull request here.

xoxo,
Sharon

**Comment by Dtrules19** [comment]
.Rhistory File was deleted

**Comment by redrambles** [comment]
Hey @Dtrules19 

Thanks for making that change!! There's just one little thing left to do - right now you aren't linking to your stylesheet (css/Daniel-T-advice.css) from your advice page. You'll want to do that so that your styles can apply.

Once you've added the link to your stylesheet in your `advice/Daniel-T-advice.html` page - add and commit and then push up your advice branch once more - just like you did before - and we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by acodeinprogress** [comment]
Hey @Dtrules19,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
