### PR TITLE
added advice from Erika

### PR DESCRIPTION
**Pull request by erikala**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @erikala,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by erikala** [comment]
Hi Sharon,

Sorry I forgot to include the link. Can you see it now?

Thanks,

Erika

**Comment by acodeinprogress** [comment]
Hey @erikala,

I'm not able to see that you've made any changes. Did you make sure to make the changes on your new-branch branch on your computer and then push them to your new-branch branch on GitHub?

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @erikala,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
