### PR TITLE
105 practice branch

### PR DESCRIPTION
**Pull request by sarahg714**
second request. unable to merge previous branch.

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @sarahg714,

This looks great! I just have a couple teensy requests before we can merge this in.
1. We would like for you to include a link to your advice page in the index.html file.
2. It looks like you deleted the .gitignore file but we actually need to have this as part of our repo.

If you could add those things in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by sarahg714** [comment]
Hi @acodeinprogress , 
Sorry for the delay in response! It's been a rough couple weeks battling a tough cold.

Can you specify what link you're referring to above? I'm not quite sure I understand how to add a link in the index.html file. And I see the deleted .gitignore file, but I can't recall where I need to add it back. Can you help me out? 
Thank you so much, I appreciate your help!
Sarah

**Comment by redrambles** [comment]
Hey there!

Ok! So here's how I would recommend tackling these things:

1) Make sure that you are still inside your 105-practice-branch

2) Open your project in your text editor of choice. Recreate a .gitignore in the root of your project directory. Visit this page https://github.com/skillcrush/105-practice/pull/714/files and look a the what was in the .gitignore file before it was deleted (on the left hand side). Copy and paste in that information into your new .gitignore file and save.

3) Open up the main index.html file. You'll see that it is essentially a long list of links - one for each student - pointing to their respective advice pages. We'd like you to add yours at the bottom of the list.

Once these things are done, add your changes in the Terminal / Git Bash using `git add -A` - then commit `git commit -m "your message here"` - then push up your 105-practice-branch branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code. :) Let us know if you have any more questions!

Cheers,
Ann :)

**Comment by sarahg714** [comment]
Hi Ann @redrambles ,
I hope I did it right this time! I'm so bummed I got it all messed up, I thought I was doing so well before. But I'll keep practicing! Let me know if there are any changes I need to add! Thank you

**Comment by redrambles** [comment]
Hey @sarahg714 !

Thanks for adding back in the .gitignore file! :) We are nearly all set to go. Now we just need you to open up the index.html file and add a link to your advice file at the bottom of the list. Once you have done that - add and commit that change and then push up your branch once more - and we should be all set to merge in your code.

You're doing great - hang in there!

Cheers,
Ann :)

**Pull request merged**
