### PR TITLE
Personalized html and css files

### PR DESCRIPTION
**Pull request by UnsweetT**
Here is my advice.

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @UnsweetT!

This looks great so far! There's just one small adjustment that we'll need to make.

It looks like you renamed the index.html file to nancyt-advice.html. Instead, we want to leave that named as index.html. You already have a nancyt-advice.html file inside of the advice folder and it's perfect!

Once you change back the nancyt-advice.html that is in the main 105-practice folder, then you'll want to run a slightly different git command (`git add -A`), then commit, and push. Your changes will join your pull request here and then we can get everything merged in!

xoxo,
Sharon

**Comment by UnsweetT** [comment]
I have renamed my index.html file and pushed it here.  Do I need to do anything else?  Thank you for your assistance!  ~ Nancy T.

**Comment by acodeinprogress** [comment]
Hey @UnsweetT,

Ok, so it looks like we now renamed it to index..html instead of index.html.

Can you change it back to have just one .?

xoxo,
Sharon

**Comment by UnsweetT** [comment]
Thanks for your patience, Sharon.  ~Nancy T.

**Comment by acodeinprogress** [comment]
Hey @UnsweetT,

Perfect! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
