### PR TITLE
Added jean-t advice page

### PR DESCRIPTION
**Pull request by jeniferjean**
105 practice

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @jeniferjean !

This is a great start! We got your advice file an your CSS file - but we need two more things for you in order to merge this in.

1) You made a change in the `css/style.css` file - which is the 'default' stylesheet that many students are using. If you scroll down to the bottom of your changed files page here: https://github.com/skillcrush/105-practice/pull/1460/files - you will see that you have added a few lines that weren't previously there. Please remove them.

2) We need a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that long list. :)

Once you remove that bit of code in the main stylesheet and add your link in the index.html file, add your changes with `git add -A`, commit as per usual and push up your advice branch once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by jeniferjean** [comment]
Hi Ann,

I made the requested changes. Let me know if anything else is needed. Thanks!

**Comment by redrambles** [comment]
Hey @jeniferjean !

Thanks for making those changes! We're nearly set to go but there still is a 
`.container {
    width: 500px
}`
block inside the main `styles.css` file that doesn't belong there (see [here](https://github.com/skillcrush/105-practice/pull/1460/files)).

Once you remove that block of code from the style.css file - please add and commit and push up your advice branch once more, and we should be all set.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by jeniferjean** [comment]
Hi Ann, 
Oops, third time's that charm. Should be fixed now. Thank you!

**Comment by redrambles** [comment]
Hey @jeniferjean,

All good - thanks for making that change. :) Your code is merged in! 🎉 

Cheers,
Ann :)

**Pull request merged**
