### PR TITLE
Added link to Jessica F Advice page

### PR DESCRIPTION
**Pull request by j-fisch**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @j-fisch,

Congrats on making your very first pull request!

I noticed that you didn't add an advice page here. If you could add that in, that would be great! Once you do that, you can add, commit, and push your work and it will join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by j-fisch** [comment]
Whoops! It should be fixed now!

**Comment by redrambles** [comment]
Hey @j-fisch !

We have your advice page now (yay!) - thanks for making that change! I do notice, though - that it is referencing a stylesheet named `css/jessica-f-advice.css` - but there isn't one in your pull request. Did you mean to add it ?

Cheers,
Ann :)

**Comment by j-fisch** [comment]
Oh goodness. I've added it. I think maybe now I've got it all set? I'll get this git thing one of these days.

**Comment by acodeinprogress** [comment]
Hey @j-fisch,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
