### PR TITLE
Experiments

### PR DESCRIPTION
**Pull request by stastnyt**
Simple advice

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @stastnyt!

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. If you're not sure how to do this, feel free to take a look at other students links!

Once you add your link, add and commit your changes and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by stastnyt** [comment]
Whoops, I totally skipped that part. Thanks for checking that!
I just pushed it again in the terminal.

T

**Comment by redrambles** [comment]
Hey @stastnyt !

Ok! So if you take a look at [your change set here](https://github.com/skillcrush/105-practice/pull/258/files) - you'll see that we have two sets of advice files and css files. You'll want to go with only one pair - so please delete the pair you are not going to use.

The other thing is that there is still no link pointing to your advice page from the main index.html file - so please add that in. :)

Once this is done, you'll want to add with `git add -A`, then commit as per usual and push up your branch, which will automatically update this pull request.

Then we should be all set to merge in your code! :)

Please let us know if you have any questions.

Cheers,
Ann

**Comment by stastnyt** [comment]
Okay, I made the changes and tried it again. I think I did it right this
time.
I am still really struggling to understand git. I also forget about git
sometimes and just start making changes to the files and I don't know if
that affects master stuff because I don't usually remember to check if I am
in the right branch before making changes.

**Comment by redrambles** [comment]
Hey @stastnyt !

Ok! We now have the link to your advice file inside the index.html file - awesome! We still have the additional `advice/ts-edits.html` and `css/ts-edits.css` that we don't need. 

First, make sure that you are in your 'experiments' branch. Then, you'll want to:

1) Delete both of those files (using any method you prefer - the Terminal, the text editor or your Finder / File Explorer)
2) 'Add' those deletions to the repository by running `git add -A`, and then committing that change with `git commit -m "your message here"` and finally pushing up your branch: `git push origin experiments`, which will automatically update this pull request.

At that point we should be all set to merge in your code.

Let us know if you have any questions!

**Comment by stastnyt** [comment]
Aww man. I thought I deleted those, but maybe I was in the wrong branch?
There is only one though, the experiments one.
I'll fix this tonight. I definitely need to review git/github D:

**Comment by redrambles** [comment]
Hey @stastnyt,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Comment by stastnyt** [comment]
shoot, did i not send it right?? sorry! i'll try to get back on that
sometime this weekend.

**Pull request closed without merging**
