### PR TITLE
Experiments

### PR DESCRIPTION
**Pull request by allan28**
Some advice from a fellow Skillcrusher.

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @allan28!

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. If you're not sure how to do this, feel free to take a look at other students links for reference!

Once you add your link, add and commit your changes and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by allan28** [comment]
Hey @redrambles!

Thanks so much for your feedback. I made the changes accordingly and pushed my branch up. Could you please check if the pull request has been updated?

Thanks a lot again!

Cheers,
Allan

**Comment by acodeinprogress** [comment]
Hey @allan28,

I see that you changed your advice file but not the index.html file. You'll want to edit that file and add a link that directs to your personal advice file.

Once you do that, you can add, commit, and push and we can get this merged in!

xoxo,
Sharon

**Comment by allan28** [comment]
Hey @acodeinprogress,

Just made the changes. Can you please check? So sorry, I don't know how I forgot to add that in the first go. ://

Thanks a lot!

Best,
Allan

**Comment by redrambles** [comment]
Hey @allan28,

You did a great job and your code is all merged in! Yay!

Cheers,
Ann :)

**Comment by allan28** [comment]
Hey @redrambles,

Thank you soo much!! Appreciate it!

Best,
Allan

**Pull request merged**
