### PR TITLE
Yana's advice commit

### PR DESCRIPTION
**Pull request by ydaneva**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @ydaneva,

This is looking great!! The only thing we need is for you to remove two unnecessary files:

1) `css/.Rhistory`
2) `css/normalize.css`

Once you have removed these files, add your changes with `git add -A` then commit them as per usual `git commit -m "Your message here"` and then push up your `advice` branch once more, which will automatically update this pull request.

Then we'll be all set to merge in your code. Let us know if you have any questions!

Cheers,
Ann :)

**Comment by ydaneva** [comment]
Hi Ann, I think I removed both files. That was a great exercise, I realized I need to first make the changes to my files, commit my changes and *then* sync with the shared remote repo to be up to date. I received many error messages because I was trying to first sync and then do the changes until I figured it out. Actually, this was something I was wondering about during the lesson. Good that I saw now how it is done (I think)

**Comment by redrambles** [comment]
Hey @ydaneva !

This is great! Good job deleting those extra files that we don't need. 

There's just one more little thing to do before we can merge this in. Two student links in the index.html file were accidentally deleted - see here: https://github.com/skillcrush/105-practice/pull/952/files#diff-eacf331f0ffc35d4b482f1d15a887d3bL17-L18

This usually happens as a result of a merge conflict. We'll just need you to add those two links back in, and then add and commit your changes and push up your `advice` file once more. Then we should be all set to merge in your code. 

If you go through the process of syncing up with the main codebase once you've added those links both in (which is good practice) - you may end up with another merge conflict in the index.html file. This is 100% normal - basically everybody is editing that file. The thing to remember is that we basically want to keep everyone's code - just delete any duplicates (if you see any within your conflict areas) - and the conflict markers themselves - and we'll be good to go. 

Let us know if you have any Qs - we're nearly done here! :)

Cheers,
Ann :)

**Comment by ydaneva** [comment]
Thanks, Ann. Hope it is ok now, otherwise let me know.

**Comment by redrambles** [comment]
Hey @ydaneva,

Yes - this is perfect! Thanks for making that last little change - your code is all merged in!

Cheers,
Ann :)

**Pull request merged**
