### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by aluettin**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @aluettin !

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that long list. :)

Once you add your link, add and commit your changes and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by aluettin** [comment]
Hi, Ann! I followed the instructions, but had that issue with my SSH keys. I resolved that, then went to do another pull request as instructed, but I don't know that it went into effect. Is there any way you could confirm this? Thanks!

**Comment by acodeinprogress** [comment]
Hi @aluettin,

I just commented on your post on Slack. Just let us know what you'd like to do!

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @aluettin,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Comment by aluettin** [comment]
Thank  you so much! :-)
    On Tuesday, August 4, 2020, 06:51:04 PM EDT, Sharon <notifications@github.com> wrote:  
 
 


Hey @aluettin,

Great job! Your code is all merged in.

xoxo,
Sharon

**Pull request merged**
