### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by kev-conn**

### CODE REVIEW

**Comment by kev-conn** [comment]
Thanks!

**Comment by redrambles** [comment]
Hey @kev-conn !

This is a great start! We just need two more things before we can merge this in.

1) We have two css files from you. One is in the 'css' directory - which is great - and the other, `advice/kevin-c-style.css` - is in the advice directory, which we want to remove.

2) We are missing a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that long list. :)

Once you delete the extra advice file and add your link to the index.html file - please add with `git add -A`, commit as per usual and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by kev-conn** [comment]
Can you check one more time - I've reset my commits back to just advice and css and then pushed it up and merged.

**Comment by kev-conn** [comment]
Found the 'Open' button

**Comment by kev-conn** [comment]
Screen Shot 2020-04-30 at 9 33 29 AM
This is currently my git log for my advice branch-not sure why it won't merge

**Comment by acodeinprogress** [comment]
Hey @kev-conn ,

Have you pushed those changes up to GitHub yet?

xoxo,
Sharon

**Comment by kev-conn** [comment]
I was having a hard time with that and reached out for help but couldn't figure it out. it just kept saying I don't have the access to do it. :/

**Comment by kev-conn** [comment]
Screen Shot 2020-05-07 at 1 38 59 PM

**Comment by acodeinprogress** [comment]
Hey @kev-conn,

The issue here is that we are trying to push to a remote repo that we've labeled `advice` but we probably named our remote repo `origin` and we want to push to our `advice` branch of that repo.

Let's try running this command:
`git push origin advice`
and see if that works.

xoxo,
Sharon

**Comment by kev-conn** [comment]
Screen Shot 2020-05-11 at 7 14 50 PM
this is what happened

**Comment by kev-conn** [comment]
Screen Shot 2020-05-11 at 7 35 57 PM
Okay! I think this may have done it!

**Comment by redrambles** [comment]
Hey @kev-conn !

We are nearly done!!! We just need you to remove the additional css file `advice/kevin-c-style.css` that you've added to the advice directory. Once you remove that file, please add with `git add -A` - commit as per usual (`git commit -m "Your message here"`) and then push up           your branch one last time (`git push origin advice`) -and we should be all set!

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by acodeinprogress** [comment]
Hey @kev-conn,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
