### PR TITLE
Added don-n advice page

### PR DESCRIPTION
**Pull request by DJNardone**
I hope I did this right!

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hi @DJNardone,

Great work! There's just one thing that we'll need to fix up before we can merge this in.

If you take a look at the [Files Changed tab](https://github.com/skillcrush/105-practice/pull/987/files) near the top of this page, you can see that you overwrote a line of code in another student's CSS file. We'll need for you to change that back to preserve that student's work.

Once you do that, you can add, commit, and push your code. Your changes will join your pull request here and then we can get it merged in.

xoxo,
Sharon

**Comment by DJNardone** [comment]
Hey Sharon,
I completed the changes you requested.  Thanks for your help!
Don

**Comment by redrambles** [comment]
Hey @DJNardone !

Thanks for making that change! This is just about ready to go - we just need one more thing. Your `don-n-advice.html` file is in the root of the project folder - but we need it to be inside the '/advice' directory. Please move it in the directory - then add and commit your change and push up your advice branch once more. 

Then we should be all set!!!

Let us know if you have any questions.

Cheers,
Ann :)

**Comment by DJNardone** [comment]
Hi Ann,
I moved the don-n-advice.html into the 'advice' folder and pushed the change.  
Thanks again for teaching me the right way!
Don

**Comment by redrambles** [comment]
Hey @DJNardone ,

Thanks for making that last change! Everything looks good - your code is merged in! :)

Cheers,
Ann :)

**Pull request merged**
