### PR TITLE
Making Changes and Pushing to repo

### PR DESCRIPTION
**Pull request by marcijo**
Some advice Marci would like to share - mainly changed the styles with a few changes to the HTML

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @marcijo !

This is good! You are nearly there! We have two requests before we can go ahead and merge this in.

1) You have two css files in your pull request - one is `css/marci-advice.css` - which we want - and the other is `css/style.css` - which we don't need. Please delete the `css/style.css` fie.

2) We are missing a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. If you're not sure how to do this, feel free to take a look at other students links for reference. :)

Once you delete your css/style.css file and add your link to the index.html file -  add and commit your changes and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by acodeinprogress** [comment]
Hey @marcijo,

Thanks for making those changes! It looks like you also deleted the .gitignore file, which we want to keep as part of our repo. Please go ahead and add that back in.

We also would like for you to edit the index.html file and add a link that will take the user to your personal advice page.

Once you make those changes, you can follow the same steps as before to push your code to GitHub and then we can get this merged in.

xoxo,
Sharon

**Comment by marcijo** [comment]
Hi Sharon,
Were you able to find out how to replace the gitignore file in a Windows
environment?  Thanks!

**Comment by acodeinprogress** [comment]
Hey @marcijo,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Comment by marcijo** [comment]
Thank you!

**Pull request merged**
