### PR TITLE
Adding Kelly Kobarda's code

### PR DESCRIPTION
**Pull request by kellybk**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @kellybk !

This is great - we only need you to address two small things:

1) we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. If you're not sure how to do this, feel free to take a look at other students links and see if you can add one of your own!

2) There is a file named '_notes/ccLibSync.xml' that was included in your pull request. Please remove it.

Once you have deleted the '_notes/ccLibSync.xml' file and have added your link in the main index.html file, add (`git add -A`) and commit your changes (`git commit -m "your message here"`) and then push your branch up once more (`git push origin kellys-code`), which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by kellybk** [comment]
Random Creative Cloud files deleted (oops) and index.html file updated with a link to my practice advice page.

**Comment by acodeinprogress** [comment]
Hey @kellybk,

Thanks for making those changes!

It looks like some conflict markers were left in our index.html file by accident. You can see them if you look at the [Files Changed](https://github.com/skillcrush/105-practice/pull/109/files) tab near the top of this page.

Once those are removed, you'll need to add, commit, and push again and then we can merge in your code.

xoxo,
Sharon

**Comment by kellybk** [comment]
Conflict markers left by git cleaned up.
Third time's a charm?

**Comment by redrambles** [comment]
Hey @kellybk,

Indeed, third time's a charm! Good work, your code is all merged in! Yay!

Cheers,
Ann :)

**Pull request merged**
