### PR TITLE
my advice page

### PR DESCRIPTION
**Pull request by codingkaveman**
Hopefully this is correct …

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @codingkaveman!

This is really close! We just need two little things before we can merge in your code.

1) We need your `advice/steve-manning-advice.html` to link to your `css/steve-manning-advice.css` stylesheet in the <head> of the document. Right not it's just linking to `css/style.css` - but not your stylesheet.

2) We are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. If you're not sure how to do this, feel free to take a look at other students links for reference. :)

Once you make these two changes, add (`git add -A`) and commit (`git commit -m "your message here"`) your changes and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by codingkaveman** [comment]
Sorry I didn't get to check over the weekend, but this morning I'm confident that I've got it right this time around. Thanks for the feedback!

Cheers, 
Kave

**Comment by redrambles** [comment]
Hey @codingkaveman !

Thanks for making that fix - your stylesheet is now properly linked up. :) 
However - we are still missing a link to your advice page in the main index.html page. If you open up the main index.html file (in the root of the folder), you will see a long list of links that point to each student's advice page. We need you to add a link to yours as well. Once you've done that, add and commit that change and push up your branch once more, which will automatically update this pull request.

Then we should be all set!

Cheers,
Ann :)

**Comment by acodeinprogress** [comment]
Hey @codingkaveman,

We just merged in your other pull request so I'm going to go ahead and close this one.

xoxo,
Sharon

**Pull request closed without merging**
