### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by Nittilam**
Hi Ann, 

Sorry for the delay in response, Here is my attempt at fixing the issue, please let me know if the pull request is okay now.

Nittilam

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @Nittilam,

Congrats on making your first pull request!

It looks like you made a lot of changes to the index.html. You can see them listed in the index.html file by clicking on the Files Changed tab near the top of this page.

We want to preserve everyone's work so we'll need for you to restore this file back to the way it was and simply add in just your link before we can merge this into the main codebase. Once you fix that up, you can add, commit, and push and your changes will join your pull request here.

xoxo,
Sharon

**Comment by Nittilam** [comment]
Hi Sharon, 


How do I restore the index.html file? I am not sure I understand what the issue is exactly. In my previous pull-request I was told by Ann to do the following: 
Here's how to fix.

" 1. Make sure you are in your advice branch in your project in the Terminal.
2. Let's fetch from upstream again with git fetch upstream.
3. Now let's replace the index.html file inside your advice branch with a copy of the file as it is on the upstream 
remote repository (Skillcrush' repo): git checkout upstream/master index.html
4. Now all you need to do is add your link in the index.html page, which points to your advice page, save the file, add and commit that change and then push up your advice branch once more.


This will automatically update your pull request and we should be all set to merge in your code."



I followed the above instructions and re-submitted a second pull request.


Let me know what I have to do now :)


thanks !
Nittilam

**Comment by acodeinprogress** [comment]
Hi @Nittilam,

I'm not seeing any changes here. Did you make sure to add, commit, and push your work? If so, could you please email us a screenshot?

xoxo,
Sharon

**Comment by Nittilam** [comment]
Hi Sharon,


Perfect I will be sending an email over.


Thank you
Nittilam :)

**Comment by Nittilam** [comment]
Hi Sharon!


I think we are good to go now ! Please let me know if we are all set?


Thank you for your patience :)
Nittilam

**Comment by redrambles** [comment]
Hey @Nittilam ,

You did a great job and your code is all merged in! Yay!

Cheers,
Ann :)

**Pull request merged**
