### PR TITLE
Added Kelsey H's advice

### PR DESCRIPTION
**Pull request by KelseyRocco**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @KelseyRocco !

This is a good start! We have your link in the main index.html file - but unfortunately we don't have your advice file itself (or any custom CSS, if you chose to use some). In your link in the main index.html file, you are referencing a file called `advice/kelsey-h-advice.html` - perhaps it still needs to be added and committed in your repository?

Once you're all good there - please push up your advice branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code. Let us know if you have any questions!

Cheers,
Ann :)

**Comment by KelseyRocco** [comment]
Let me  know if that worked?

**Comment by acodeinprogress** [comment]
Hi @KelseyRocco ,

I see that you edited the index.html file but I don't see where you've added an advice file or a CSS file. Want to give this another go? You'll need to add those files, commit, and push in order for them to show up here.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @KelseyRocco,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
