### PR TITLE
Added my advice link

### PR DESCRIPTION
**Pull request by Jacquanb**
Added my advice link to the code.

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @Jacquanb !

This is great! The only thing is that there is an additional stylesheet hanging out in the root of the project folder which we don't need (`jacquan-b.css`). Please remove that file. (Your other stylesheet is in the css directory, which is where it should be. :))

Once you have removed that file, please add your changes with `git add -A` - commit as per usual and push up your `advice` branch once more. This will automatically update your pull request and we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by Jacquanb** [comment]
> Hey @Jacquanb !
> 
> This is great! The only thing is that there is an additional stylesheet hanging out in the root of the project folder which we don't need (`jacquan-b.css`). Please remove that file. (Your other stylesheet is in the css directory, which is where it should be. :))
> 
> Once you have removed that file, please add your changes with `git add -A` - commit as per usual and push up your `advice` branch once more. This will automatically update your pull request and we should be all set to merge in your code.
> 
> Let us know if you have any questions!
> 
> Cheers,
> Ann :)

**Comment by Jacquanb** [comment]
Hello, 

I  deleted the CSS file that was not needed.

Thank you for the feedback,

Best,

Jacquan

**Comment by acodeinprogress** [comment]
Hey @Jacquanb,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
