### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by iremkenar**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @iremkenar !

This is a good start! We have your link in the index.html file - but your advice file is in this location: `irem-k-advice.html/irem-k-advice.html/irem-k-advice.html` - and we need it to be in this location `advice/irem-k-advice.html/`

Please move your `irem-k-advice.html` file into the `advice` folder - and delete the `irem-k-advice.html/irem-k-advice.html` folder.

Once this is done - please add with `git add -A` and then commit `git commit -m 'Your message here"` and then push up your advice branch once more, which will automatically update this pull request. Then we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by iremkenar** [comment]
Hi Ann,

Thanks for the feedback! I’ve just updated as per your comments.
Then I saw a conflict on my pull request, as I realized that I pushed the unsynced version from 4 days ago. So, I’ve synced the source code and pushed the synced version, with two new commits. Now I see the conflict is resolved.

Please let me know if I need to change anything or we’re good to go :)

Thanks again and stay safe!
Irem

**Comment by acodeinprogress** [comment]
Hey @iremkenar,

Thanks for making those changes!

It looks like you might've accidentally uploaded a zip file (irem-k-advice.html.zip) during the process, so we'll need for you to remove it before we can proceed.

Once you do that, please add (using `git add -A`), commit, and push. Then we should be able to get this merged in.

xoxo,
Sharon

**Comment by iremkenar** [comment]
Hi Sharon,

Just deleted that file. Please have a look and let me know if it's all good now.

Thanks!
Irem

**Comment by redrambles** [comment]
Hey @iremkenar !

Thanks for making that change - everything is good now and we've just merged in your code. Yay!!!

Cheers,
Ann :)

**Pull request merged**
