### PR TITLE
Added Mary S advice link

### PR DESCRIPTION
**Pull request by marylizvision**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @marylizvision !

This is a good start! We got your link in the main index.html file which is pointing to `advice/mary-s-advice.html` - but we don't have the file itself. Perhaps it's still needs to be added and committed? Once it's good to go, push up your advice branch once more, and this pull request will be automatically updated.

Then we should be all set to merge in your code. Let us know if you have any questions!

Cheers,
Ann :)

**Comment by marylizvision** [comment]
Hi Ann! 

Thanks for your response!

 I'm trying to add, commit, and push the advice branch and it looks like everything is working correctly on my command line but nothing is updating on here...GitHub is taking me a while to comprehend! 😅  Also, it looks like my CSS document is on the Master branch and the HTML is on the Advice branch...at least locally...not sure how I managed that one! Haha.

I'll keep researching to figure out what I'm missing! Thanks so much!

Mary

**Comment by redrambles** [comment]
Hey @marylizvision ,

You did a great job and your code is all merged in! Yay!

Cheers,
Ann :)

**Comment by marylizvision** [comment]
Hi Ann!

Phew, thank you!!

Cheers,
Mary

**Pull request merged**
