### PR TITLE
Experiments

### PR DESCRIPTION
**Pull request by mtthewedwards**
I didn't make very many changes to the code in HTML or CSS, I'm going to redo the HTML/CSS lessons to reinforce my knowledge in that area. Just changed some of the writing and changed the background and fonts and colors. I wanted to focus on getting my changes upstream.

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @mtthewedwards,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by mtthewedwards** [comment]
Hi Sharon, thanks for checking it out. Ok, so a link to the advice page...I'm trying to remember where I would put that link in my html. Would that go in the <head> section of html? I feel like I've forgotten everything since I took the html/css 101 class which is why I'll be going back to relearn it.

**Comment by mtthewedwards** [comment]
@acodeinprogress I'm adding this link to the <head> of my html:
<link rel="stylesheet" href="../css/matthewedwards-advice.css"> 

Is that the correct place for it?

**Comment by acodeinprogress** [comment]
Hey @mtthewedwards,

If you take a look at the line above the one that you just added, we already have a link to the CSS file.

Instead, we'd like for you to edit the index.html file and add a line that will link to your advice page.

xoxo,
Sharon

**Comment by mtthewedwards** [comment]
Hi @acodeinprogress, 

Thanks for following up. I'm not sure why but I am really struggling with this. How do I create a link to my advice page? I know the link needs to go in the head. Am I linking it to my html file inside the advice folder on my computer? Am I linking to something online? I have this file: folder:file:///Users/matthewedwards/Desktop/105-clone/105-practice/advice/matthewedwards-advice.html Is this what I'm linking to? I think I am overcomplicating this and misunderstanding what you want me to do. Sorry for the confusion.

**Comment by acodeinprogress** [comment]
Hey @mtthewedwards,

If you open up the index.html file in your text editor, you'll see other student links that look something like this:
`<a href="advice/sharons-advice.html" target="_blank">Sharon's advice</a><br/>`

You'll want to add one in there that goes to your own advice page so your href would look like "advice/matthewedwards-advice.html"

xoxo,
Sharon

**Comment by mtthewedwards** [comment]
Hi @acodeinprogress,

Looks like there was a conflict. How do I go about fixing this?

**Comment by acodeinprogress** [comment]
Hey @mtthewedwards,

This is all fixed and your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif) now. Yay!


xoxo,
Sharon

**Comment by mtthewedwards** [comment]
@acodeinprogress thanks for your help! Turns out I was just looking in the wrong file to add the link. Glad I figured this out!

**Pull request merged**
