### PR TITLE
Terri P's advice

### PR DESCRIPTION
**Pull request by terri-pie**

### CODE REVIEW

**Comment by terri-pie** [comment]
Need to make one more change!

**Comment by terri-pie** [comment]
Updated link to my CSS file in terri-p-advice.html.

**Comment by redrambles** [comment]
Hey @terri-pie !

This is coming along nicely! We just need you to do two things before we're good to merge this in.

1) You deleted the contents of the 'default' stylesheet (css/style.css )- and we're going to need that back. :) No worries! The easiest way to grab it again is to do the following:

- `git fetch upstream`
- `git checkout upstream/master css/style.css`

Boom! It should be back in all its previous glory. This command will basically check out the version of the css/style.css file as it exists on the upstream (Skillcrush) repo. :)

2) In the index.html file - you have duplicated a bit of markup around the header section in addition to adding your link. You'll see what I mean if you open the index.html file in your text editor. You'll basically want to remove lines 18-23 or so and then move your link down inside the div with the class of 'skillcrush'.


Once you have made those two changes, add them in with `git add -A` - then commit as per usual, and push up your branch once more, which will automatically update this pull request. Then we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by terri-pie** [comment]
Thank you Ann! I hope I incorporated those changes successfully! Please let me know if I need to do anything else. :)

**Comment by terri-pie** [comment]
Hi,

Do I need to submit another pull request? Are there any other changes I need to make?

Thank you!

**Comment by acodeinprogress** [comment]
Hey @terri-pie,

No need to submit another pull request!

There is just one last change that you'll need to make here. It looks like in the process of making those changes, there are some extra lines of code at the very end of the index.html file that look like this:
```<<<<<<< HEAD
</html>
ß
=======
</html>
>>>>>>> upstream/master```

You can see them by looking at the [Files Changed](https://github.com/skillcrush/105-practice/pull/1732/files) tab near the top of this page.

You'll need to remove those lines and then add, commit, and push and then we should be able to merge this in!

xoxo,
Sharon

**Comment by terri-pie** [comment]
Thank you Sharon! I'm really sorry for the repeat requests/mistakes! I removed the extra lines and pushed the changes as advised (I hope). I'm confused about why I get a message saying "this branch has no conflicts with the base branch" when there are differences in my file from the base branch?

Thanks again for your help (and patience)! :)

**Comment by acodeinprogress** [comment]
Hi @terri-pie,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).

It's difficult to say why you got that message without seeing your commands but everything came through here perfectly!

xoxo,
Sharon

**Pull request merged**
