### PR TITLE
Add Wesley T's advice

### PR DESCRIPTION
**Pull request by wtom3912**
Sharing advice

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @wtom3912!

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. If you're not sure how to do this, feel free to take a look at other students links for reference. :)

Once you add your link, add and commit your changes and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by wtom3912** [comment]
Hi Ann,

I added the link to the index.html file but I'm not sure if it was added to
the correct branch because when I perform a git commit it says there is
nothing to commit. I attached some screenshots of the index.html file page
and my terminal.

Thanks,
Wesley

**Comment by redrambles** [comment]
Hey @wtom3912,

Ok! Unfortunately your screenshots didn't make it through on this platform - so please feel free to email us at questions[at]skillcrush.com - and we'll take it from there! :)

**Comment by redrambles** [comment]
Hey @wtom3912!

Thanks for making those changes - your code is all merged in! :)

Cheers,
Ann :)

**Pull request merged**
