### PR TITLE
new html and css

### PR DESCRIPTION
**Pull request by sofiatozzi**
I would love to share this advice with you!

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @sofiatozzi,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by sofiatozzi** [comment]
Hi Sharon! I was able to add the link to index.html and pushing the changes. Let me know if what I did is correct since I need a little extra practice with github!
Best,

Sofia.

**Comment by acodeinprogress** [comment]
Hey @sofiatozzi,

Awesome! Thanks for making that change!

It looks like in the process, you accidentally removed a closing > from someone else's <br> tag. Try taking a look at line 20 and then add it back in. Once you do that, you can follow the same steps of adding, committing, and pushing.

xoxo,
Sharon

**Comment by sofiatozzi** [comment]
Hi Sharon,

Can you check if I was able to push the changes? I had to push changes from both branches (master and my branch called "newproject"). im very confused in how im executing the terminal. I tried to push the changes from the new project branch and is not going thru, so I went ahead and did it from master branch. I understand the functions of git however when i have to apply it to github it get very confused.

**Comment by sofiatozzi** [comment]
Hi Sharon, So checking on git, It looks like both master and newproject branch codes are fixed, however when I try to push changes to github with newprojects branch this message pops up:

 ! [rejected]        newproject -> newproject (non-fast-forward)
error: failed to push some refs to 'git@github.com:sofiatozzi/105-practice.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
Sofias-MacBook-Pro:105-practice sofiatozzi$ 

how can I fix this in order to push the new changes to github?

thanks so much in advance!!

**Comment by acodeinprogress** [comment]
Hey @sofiatozzi,

When you get that error, it means that you may have made some changes on GitHub that you need to pull down to your computer first.

I'm not sure if you were able to get this sorted out or not but in your newest commits on GitHub, I see that you added some duplicate lines that will need to be removed. You can see them highlighted in green by clicking on the [Files Changed](https://github.com/skillcrush/105-practice/pull/692/files) tab near the top of this page and scrolling down to the index.html file. There should be just one green line for the link that you added for your advice page and the rest should not be highlighted in green.

Once you make that change, you can follow the same steps and we'll take a look!

xoxo,
Sharon

**Comment by sofiatozzi** [comment]
HELLO AGAIN!

OK, I was able to delete all the double links (so they will be shown in red) I hope I get it this time right.... I think what happened, as a newbie, i totally got confused between both, master an newproject branches and started to make changes in both and added extra links. I take Github as a challenge I need to practice the most... Thanks for always helping me out (and all your amazing patience!)

Best,

Sofia.

**Comment by sofiatozzi** [comment]
One more question..... now that I'm  comparing my code to the original from skillcrush, I'm missing 3 peoples links from the first links (ADAM, LAWANAS AND ADDRIENNE) When I go to my branch and add the changes, commit and then push the changes it get rejected:
 ! [rejected]        newproject -> newproject (fetch first)
error: failed to push some refs to 'git@github.com:sofiatozzi/105-practice.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

 To fix this, should I sync my fork with y master branch? so sorry for all the questions. I feel like at this point it should't be a bad idea to start all over.(messing with both branches made me add and delete links and it made it too confusing)

**Comment by acodeinprogress** [comment]
Hey @sofiatozzi,

You are absolutely correct! I'm seeing that you removed some links from other students. Those will also need to be added back in before we can get this merged in.

The error you're seeing is the same as you got before, which means that you may have made a change on GitHub itself again and will need to pull it down to your computer before you can push up your updates.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @sofiatozzi,

Nevermind my message above. I saw that you submitted a new pull request, which looks great so I'll close this one and merge that new one in!

xoxo,
Sharon

**Pull request closed without merging**
