### PR TITLE
julearenas advice html/css

### PR DESCRIPTION
**Pull request by jpaola98**
Please check and advise

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @jpaola98,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by jpaola98** [comment]
Hi:

I have added the link to the index.html file. Please let me know if I need to add anything else.

Thank you,

Julieth

**Comment by acodeinprogress** [comment]
Hey @jpaola98,

This is close! We would actually like for you to edit the index.html file. You should see a bunch of links that look something like this:
`<a href="advice/sharons-advice.html">Sharon's advice</a>`
We'd like for you to add one that links to your advice page.

Once you do that, you'll follow the same steps of adding, committing, and pushing and your changes will join your pull request here.

xoxo,
Sharon

**Comment by jpaola98** [comment]
Hi:
I think I got it now. I added a link to my advice page to the index.html file, I made some changes to my html and css files as well which resulted in a couple of conflicts when I tried to add/commit the files, but I corrected them as well. Please let me know if this worked.

Thank you,

Julieth

**Comment by acodeinprogress** [comment]
Hey @jpaola98,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
