### PR TITLE
Peter's advice added

### PR DESCRIPTION
**Pull request by peter-kalavritinos**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hi @peter-kalavritinos,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by peter-kalavritinos** [comment]
Hi Sharon!

I just added the link and I added, committed, and pushed my changes.  Did I
do this correctly?

Thank you!
Peter

**Comment by acodeinprogress** [comment]
Hey @peter-kalavritinos,

I'm not seeing any changes here. Did you make sure to make your changes on your advice branch and then push up to GitHub? If you did, can you share a screenshot of your terminal with the commands you ran and the result?

xoxo,
Sharon

**Comment by peter-kalavritinos** [comment]
Hi Sharon,

Here is a screenshot.  How does this look?

**Comment by acodeinprogress** [comment]
Hey @peter-kalavritinos,

Unfortunately the screenshot didn't come through. Could you please email it to us at questions@skillcrush.com?

xoxo,
Sharon

**Comment by peter-kalavritinos** [comment]
Hi Sharon,

I will send that over right now!

**Comment by redrambles** [comment]
Hey @peter-kalavritinos !

We are very close to the finish line! The only thing we need now is for you to delete the `my-advice.html/peter-k-advice.html` folder/file that still exists in this advice branch. Once you remove the 'my-advice.html' folder, add the change with `git add -A`, commit as per usual and push up your advice branch once more. Then we should be all set to merge this in!

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by peter-kalavritinos** [comment]
Hi Ann!

Ok, I just did everything and it should be good to go.  I will attach a
screenshot of my command line just in case.

Thank you so much for your help and patience!

Best,
Peter

**Comment by redrambles** [comment]
You're all set, @peter-kalavritinos !

Thanks for making those changes - your code is merged in! :)

**Pull request merged**
