### PR TITLE
Kens advice

### PR DESCRIPTION
**Pull request by kclemens1004**
Some advice I would love to share

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @kclemens1004,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by kclemens1004** [comment]
Should be all set! please let me know if I missed a step.

**Comment by redrambles** [comment]
Hey @kclemens1004!

I'm still seeing only the two files in your change set here (https://github.com/skillcrush/105-practice/pull/284/files) - did you perhaps forget to push up your branch?

Ann :)

**Comment by acodeinprogress** [comment]
Hey @kclemens1004,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
