### PR TITLE
Advice page Naomi Martin

### PR DESCRIPTION
**Pull request by Naomilouiserose**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @Naomilouiserose!

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that long list. :)

Once you add your link, add and commit your changes and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by Naomilouiserose** [comment]
Hi Ann,

I did originally add my link and I had a conflict when I tried to merge branches, which I thought I had resolved it. I followed your instruction this morning and added my link again and I was able to push origin advice again without any conflicts but now there is showing a conflict on this thread. Maybe this is the old conflict showing and this morning's update worked? I am not sure!

Thanks for your help,
Naomi

**Comment by redrambles** [comment]
Hey @Naomilouiserose !

Thanks for pushing up that change! It's normal to get conflicts in this file as there are so many students that edit it. Everything is good here - your code is merged in!

Cheers,
Ann :)

**Comment by Naomilouiserose** [comment]
Ok great, thank you very much! x

**Pull request merged**
