### PR TITLE
Added amanda e advice page to index

### PR DESCRIPTION
**Pull request by a-ashedwards**
Added amanda e advice page to index

### CODE REVIEW

**Comment by a-ashedwards** [comment]
Hello,
I have been reviewing the files, and am having a difficult time determining which conflicts need to be resolved.  I updated my remote branches again, but received a message that my branches were already up-to-date.  I would appreciate it if I could be pointed in the right direction.
Thank you,
Amanda Edwards

**Comment by acodeinprogress** [comment]
Hi @a-ashedwards,

I would recommend starting off by reviewing this lesson regarding merge conflicts: [https://learn.skillcrush.com/module-8/merging-resolving-conflicts/](https://learn.skillcrush.com/module-8/merging-resolving-conflicts/)

See if that helps and let us know if you need any assistance!

xoxo,
Sharon

**Comment by a-ashedwards** [comment]
I believe the conflicts were resolved, thank you.

**Comment by a-ashedwards** [comment]
I thought that I had figured out what I did incorrectly, and would truly appreciate a little bit of guidance.
Thank you,
Amanda Edwards

**Comment by redrambles** [comment]
Hey @a-ashedwards !

Thanks for making those changes - all good here. Your code is merged in! 👍 

Cheers,
Ann :)

**Pull request merged**
