### PR TITLE
Add Elaine advice to index.html

### PR DESCRIPTION
**Pull request by elaine-p-nguyen**

### CODE REVIEW

**Comment by elaine-p-nguyen** [comment]
This my practice pull request for "Forking workflow"

**Comment by redrambles** [comment]
Hey @elaine-p-nguyen !

We have the link to your advice file inside the index.html file - but we don't have your advice file itself as part of this pull request. If you run `git status` - do you still see that it needs to be added and committed? If so- you'll need to do that and then push up your `advice` branch once more, which will automatically update this pull request.

If you don't see anything when you run `git status` - then it's most likely that you still need to push up your most recent changes `git push origin advice`.

Once we get your advice file, we'll be able to merge this in. Let us know if you have any questions!

Cheers,
Ann :)

**Comment by elaine-p-nguyen** [comment]
Hi Ann, 
Sorry for late reply, I did run `git status` and turned out I didn't add advice file to commit yet. Now that I'm already run add and commit advice file to `advice branch`, do I have to run `git merge` again to merge it into master and start new pull request?

**Comment by redrambles** [comment]
Hey there @elaine-p-nguyen !

Everything is good here - thanks for making that change, your code is merged in! :)

Cheers,
Ann :)

**Pull request merged**
