### PR TITLE
Edited advice HTML doc and added style.css doc

### PR DESCRIPTION
**Pull request by catherine-rose**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @catherine-rose !

This is a good start! We just need you to tackle a few little things before we can merge this in.

1) Your `catherine-d-advice.html` is in the root of the project folder, but we need it to be in the `advice` directory. Please move it in there.
2) Your `style.css` is in the root project folder as well. You'll want to rename it to something like `catherine-d-styles.css` and then place it inside the `css` directory.

Once you have made those changes - please add with `git add -A`, commit as per usual, and push up your `advice` branch once more.

Then we should be all set to merge in your code. Let us know if you have any questions!

Cheers,
Ann :)

**Comment by catherine-rose** [comment]
Thank you @redrambles! I renamed my css file and moved both the css and advice files to the advice directory, then pushed them. Hopefully this is correct!

**Comment by acodeinprogress** [comment]
Hey @catherine-rose,

You're almost there!

It looks like the CSS file is in the `advice` folder rather than the `css` folder. Once you move it there, you'll want to follow the same steps as before to add, commit, and push.

Once you do that, we can get this merged in!

xoxo,
Sharon

**Comment by catherine-rose** [comment]
Hi Sharon,

Sorry, dumb mistake. But now I think I'm confusing myself. I moved
catherine-d-style.css from the advice folder to the css folder, added,
committed, then pushed. But I pushed the advice directory. Is this right or
am I missing/mixing up a step? Thanks so much for your help!

Catherine

**Comment by acodeinprogress** [comment]
Hey @catherine-rose,

Hmmm.... it looks like the CSS is still in the advice folder but you changed the name from `catherine-d-style.css`  to `css`.

I would highly recommend changing the name back to `catherine-d-style.css` and then moving it to the `css` folder. 

xoxo,
Sharon

**Comment by catherine-rose** [comment]
Hi Sharon,

I have NO idea how I did that. I must have used a wrong command. Everything
should be fixed now. I renamed my mistakenly named css file back to
catherine-d-style.css and moved it into the css folder, added, committed,
pushed. Hopefully everything looks correct now. Thanks again!

Catherine

**Comment by acodeinprogress** [comment]
Hey @catherine-rose,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
