### PR TITLE
Added Alice's Advice

### PR DESCRIPTION
**Pull request by y-alicee**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @y-alicee !

This is a good start! We have your link in the main index.html file - and it is referencing an advice file at `advice/alice-y-advice.html` - but there is no such file in your pull request. Do you still perhaps need to add and commit it? Once you have done so, please push up your `advice` branch once more, which will automatically update this pull request. Then we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by y-alicee** [comment]
Hi Ann!

This was one bit of the course I actually really didn't get and so I've
tried going back to do it again and I get stuck at the same part each
time...

In the 'Working with Teams Step 4 of 6: Start the Forking Workflow'
challenge I always get lost at '16. Navigate back to your command line to
add and commit your changes'.

When I head back into the command line I go to add the alice-y-advice-html
file but it says it's not found. Do I need to navigate into the advice
folder in order to add that successfully? Also do I need to add and commit
the changes made to the index.html file?

Sorry for all the questions and thank you! :)
Alice

**Comment by acodeinprogress** [comment]
Hi Alice,

Yes, you'll need to commit any changes that you want to appear on GitHub. If you want to add the advice file to the staging area, you'll either need to alter the command so that it first looks in the advice folder and then looks for your advice file. This means that if your advice file is called `alice-y-advice.html`, then the you would add `advice/alice-y-advice.html`. Alternatively, you could just go into the advice file and then add `alice-y-advice.html`.

xoxo,
Sharon

**Comment by redrambles** [comment]
Hey @y-alicee,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Pull request closed without merging**
