### PR TITLE
Add Raheims Advice

### PR DESCRIPTION
**Pull request by ramsers**
some advice I was given that I found helpful

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @ramsers!

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. If you're not sure how to do this, feel free to take a look at other students links for reference. :)

Once you add your link, add and commit your changes and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by ramsers** [comment]
Hey Ann just added the link and pushed the branch. Just wondering if it
came through.

Cheers,
Raheim

**Comment by acodeinprogress** [comment]
Hey @ramsers,

I'm not seeing any updates here. Did you make sure to do your work on your experiments branch on your computer and then push to your experiments branch on GitHub?

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @ramsers,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
