### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by MickSalter**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @MickSalter !

We got your CSS (yay!) - but we don't have your advice file nor a link to it from the main index.html file. Once you add those in - please add with `git add -A` then commit as per usual and push up your `advice` branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code. Let us know if you have any questions!

Cheers,
Ann :)

**Comment by MickSalter** [comment]
> Hey @MickSalter !
> 
> We got your CSS (yay!) - but we don't have your advice file nor a link to it from the main index.html file. Once you add those in - please add with `git add -A` then commit as per usual and push up your `advice` branch once more, which will automatically update this pull request.
> 
> Then we should be all set to merge in your code. Let us know if you have any questions!
> 
> Cheers,
> Ann :)

Hey Ann
Thank you for your help. I'm a little confused though. I can see my advice file in the index html  under "Jonathans Advice" at the top. I thought I already linked it. This is what it looks like in the code ( <a href="advice/jonathan-s-advice.html" target="_blank">Jonathan's Advice</a><br> )
Please let me know.
Thank you again for your help
  ##Cheers

**Comment by MickSalter** [comment]
Hey Ann
Thank you for your help. I'm a little confused though. I can see my advice
file in the index html under "Jonathans Advice" at the top. I thought I
already linked it. This is what it looks like in the code ( Jonathan's
Advice
<https://github.com/skillcrush/105-practice/pull/advice/jonathan-s-advice.html>
)
Please let me know.
Thank you again for your help
Cheers

**Comment by acodeinprogress** [comment]
Hey @MickSalter,

So sorry about that! We didn't realize that this was an update to a previous pull request. We'll go ahead and merge this in now.

xoxo,
Sharon

**Pull request merged**
