### PR TITLE
adding Davide's advice

### PR DESCRIPTION
**Pull request by Usedtofarm**
Hello!,
I would like to know if I did everything correctly!

### CODE REVIEW

**Comment by Usedtofarm** [comment]
Hope everything is right!

**Comment by acodeinprogress** [comment]
Hey @Usedtofarm,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by Usedtofarm** [comment]
Hi @acodeinprogress ,

I added the link and pushed the changes. I hope to have it done right 

Davide

**Comment by acodeinprogress** [comment]
Hey @Usedtofarm,

I'm not seeing any updates here. Did you make sure to make your changes on your `davide-advice` branch and then push to your `davide-advice` branch on GitHub? This pull request is only for that branch so if you made your changes on a different branch, they won't show up here.

xoxo,
Sharon

**Comment by Usedtofarm** [comment]
Hi @acodeinprogress 

I tried again, I will attach a screenshot of my request hoping it helps clarify if I am implementing your instruction correctly.

Thanks for your time

github-pull

**Comment by acodeinprogress** [comment]
Hey @Usedtofarm ,

Great job! It looks like your changes came through and tour code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif) now.


xoxo,
Sharon

**Pull request merged**
