### PR TITLE
Kevins advice

### PR DESCRIPTION
**Pull request by KevSB**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @KevSB,

This looks great! I just have 1 teensy request before I merge this in.
It looks like you removed other students' links in the index.html file. Instead, we just want you to add your link in addition to everyone else's so that we can preserve everyones links. Once you fix that up, you can add, commit, and push and your changes will join your pull request here.

Let me know if you need any help!

xoxo,
Sharon

**Comment by KevSB** [comment]
tried to get back to  the conflict to see who I deleted but having trouble
finding that html file I edited on github.

**Comment by KevSB** [comment]
I think these may be the students I removed.
Lauren's Advice <advice/laurenlavoie-advice.html>
- Garrett's Advice <advice/garrettnoble-advice.html>
- Rodricode's Advice <advice/rodricode-advice.html>
- Lex's Advice <advice/alexsis-advice.html>
I opened the 105 practice index.html file this morning, the16th of
August.and they were there. If they were the names I removed, it appears to
be resolved.
What shall I do from here? Is everything OK?
Thank you Sharon for your help,
Kevin

**Comment by acodeinprogress** [comment]
Hey @KevSB !

You can see which lines were removed by clicking on the [Files Changed](https://github.com/skillcrush/105-practice/pull/573/files) tab near the top of this page and looking for the lines highlighted in red (they also have a minus sign at the beginning of each line to indicate that that line was removed).

When you were checking locally, did you make sure that you were looking at your kevins_advice branch? If not, you'll need to make sure to check that branch and add them back there.

Once you have those changes on your computer, you'll also need to push them to your kevins_advice branch on GitHub.

xoxo,
Sharon

**Comment by KevSB** [comment]
Hi Sharon,
I added the names back to the index.html file.
Should be OK now.
Thank you
Kevin

**Comment by acodeinprogress** [comment]
Hey @KevSB,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
