### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by codedbyk8**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @codedbyk8 !

This is fantastic!! We only need to address one tiny issue before we can merge in your code. 

Your CSS file is called `css/Kate_M.css` - but in your advice file, you are referencing it as `..css/kate_m.css` (lowercase). This isn't an issue for most browsers while your files are local, but will present a problem on a server. You can either rename your css file (i.e. `git mv css/Kate_M.css css/kate_m.css`) or you can edit the link to the stylesheet in your advice page.

Either way, once this is done you'll want to add your changes with `git add -A` - commit as per usual and then push up your `advice` branch which will automatically update this pull request. Then we should be all set to merge in your code. :) 

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by codedbyk8** [comment]
I fixed it and committed and pushed. Don't see it on here quite yet - let me know what may need my attention!

**Comment by redrambles** [comment]
Hey there @codedbyk8 !
 
We're not seeing it on our end either. Are you sure there is nothing left to add (`git status` will tell you if there is) and commit? If not - perhaps you accidentally pushed your master branch (it is the one we are most used to pushing, after all) instead of the advice branch? Can you try `git push origin advice` once more?

Cheers,
Ann :)

**Comment by codedbyk8** [comment]
Ok I believe that did it - everything looks in order. :-)

**Comment by redrambles** [comment]
Hey @codedbyk8 !

Yes! Thanks for making those changes, your code is merged in. 👍 

Cheers,
Ann :)

**Pull request merged**
