### PR TITLE
Added link to html

### PR DESCRIPTION
**Pull request by mal-delaney**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @mal-delaney !

This is a great start! I see that you have added a link to your advice page (`advice/mallory-d-advice.html`) in the main index.html file (awesome!) - but we don't have the advice page itself as part of this pull request. Do you still need to add and commit it? When you do, push up your advice branch once more and your pull request will automatically be updated.

Then we should be all set to merge in your code. Let us know if you have any questions!

Cheers,
Ann :)

**Comment by mal-delaney** [comment]
hello ann,

I went ahead and tried to add it onto github. i’m just not sure if it showed up or if it merged? thanks for
your help!

mallory delaney.

**Comment by redrambles** [comment]
Hey @mal-delaney,

Thanks for making that change - your code is merged in! :)

Cheers,
Ann :)

**Comment by mal-delaney** [comment]
@redrambles awesome! thank you for your help ! :)

**Pull request merged**
