### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by ReneeVGonzalez**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @ReneeVGonzalez !

This is good! We just have a few changes to make before we're set to merge this in.

1) Unfortunately we cannot accept images as part of student pull requests, as the repository would soon get too large. You are free to link to a version of the image that is hosted somewhere on the internet, though, of course! :) We'll need you to remove the `img-advice` directory.

2) You have a double of your advice page in the root of the project directory (`Renee-Gonzalez-advice.html`) and a double of your css  in the css directory (`css/advice-renee.css`). Please delete both of these files.

Once you have made those changes - please add with `git add -A`, commit `git commit -m "Your message here"` and then push up your `advice` branch once more, which will automatically update your pull request. Then we should be all set to merge in your code!

Let us know if you have any questions!

!csa

**Comment by ReneeVGonzalez** [comment]
Hello!

I have deleted the files and followed the steps but when I went to push I got this message: 
To github.com:ReneeVGonzalez/105-practice.git
 ! [rejected]        advice -> advice (fetch first)
error: failed to push some refs to 'git@github.com:ReneeVGonzalez/105-practice.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for detail

But now it says I have nothing to commit, so I am not sure if it worked? I think I messed it up because I tried to do this practice lesson twice because I was confused the first time.

Can you please let me know what else I may need to do next.

Thank you so much for your help!
Renee

**Comment by redrambles** [comment]
Hey @ReneeVGonzalez !

Ok! So the message that you are getting generally means that you have made some updates directly on Github - which creates another commit on the remote repo that doesn't exist on your local repo, and Git's job is to protect the integrity of the history of the project - so it won't let you push up your new commit if it doesn't include the one that was made on GitHub. (Phew - that was a long sentence!) Does that make any sense? 

What I would do now is to run `git pull origin advice` - which will integrate the change that exists on GitHub that doesn't exist locally - and then you can push again with `git push origin advice`. 

Keep us posted on your progress!
Cheers,
Ann :)

**Comment by redrambles** [comment]
Hey @ReneeVGonzalez !

We are suuuuuuper close! If you have a look at the index.html file in your pull request here:  https://github.com/skillcrush/105-practice/pull/938/files#diff-eacf331f0ffc35d4b482f1d15a887d3bR19-R23

You'll notice that there are some conflict markers (`======` and  `>>>>>>> 1ec51addb29e20194da87f1984be2c53fef524e8`) that we'll want to remove - as well as the two links that are immediately following yours, as they are duplicates (you can see that they exist above your link).

Once you make that change, add and commit and then push up your advice branch once more - which will automatically update this pull request. Then we should be all set to merge in your code! :)

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by ReneeVGonzalez** [comment]
Thank you so much for all your help with this! I greatly appreciate you walking me through being able to complete this portion!!

Renee Gonzalez

**Comment by redrambles** [comment]
Hey @ReneeVGonzalez !

Thanks for making those changes - your code is all merged in!!! Yay!!!

Cheers,
Ann :)

**Pull request merged**
