### PR TITLE
added a new html

### PR DESCRIPTION
**Pull request by MsDonnaD**
new html with a link to advice page...change of link on advice page

### CODE REVIEW

**Comment by redrambles** [comment]
Hello @MsDonnaD !

This is good - we just need to address one small issue. You appear to have accidentally renamed the main 'index.html' file to 'Untitled-1.html' - so let's fix that! :)

In the Terminal or Git Bash, inside this project, please do the following:

1) `git checkout upstream/master index.html`

This will pull in the index.html file from the main code base. 

2) Open up the index.html file and add the link to your advice page once again.

3) Delete the 'Untitled-1.html' file.

4) Add and commit and push these changes with `git add -A`, `git commit -m "your message here"` and `git push origin master`

This will automatically update your pull request, and we should be good to merge in your code. 

Keep us posted and let us know if you have any questions!

Cheers,
Ann :)

**Comment by MsDonnaD** [comment]
deleted untitled html. added index.html with advice link

**Comment by redrambles** [comment]
Hey @MsDonnaD !

Ok - we are getting closer! There are a few more things to take care of, and then we should be good to go.

1) Please delete the advice/donna-advice.css file - you already have a stylesheet (css/donna-advice.css)
2) At the bottom of your 'css/donna-advice.css' file, this some text that appears to have been accidentally copy/pasted there, and doesn't belong in a stylesheet (lines 94-105). Please remove them.

Once these are done, please add with `git add -A` and then commit as per usual, and push up your branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code. Let us know if you have any questions! :)

Cheers,
Ann

**Comment by redrambles** [comment]
Hey @MsDonnaD,

Thanks for making those changes - your code is all merged in! Yay!

Cheers,
Ann :)

**Pull request merged**
