### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by Nix73**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @Nix73 !

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that long list. :)

Once you add your link, add and commit your changes and then push your advice branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by Nix73** [comment]
Hi Ann,

The link is there :) it is right at the top. If you like I could move it to the bottom of the page. 

Cheers Nix

**Comment by Nix73** [comment]
Sorry Anne,

I dont understand whats going on. From my local index.html file it shows the link that I inserted.  I -
did the following:
git add index.html
git commit -m"link added to page"
git push origin master
but nothing seemed to happen...


thanks Nix

**Comment by redrambles** [comment]
Hey @Nix73 !

Ok! Let's try using `git push origin advice` instead of `git push origin master` because you are working on your advice branch right now, and this is the one tied to your open pull request.

Once you run that, we should see a change on our end. We'll go from there!

Cheers,
Ann :)

**Comment by Nix73** [comment]
I have no idea what i did...I went back to advice in my local directory and tried to push it and it kept telling me there was nothing to push...then found the message above saying there were conflicts to resolve...I resolved these by removing the lines that were highlighted ...and viola it said the master has merged with advice...which I don't think was what I supposed to do.
so confusing....

Nix

**Comment by acodeinprogress** [comment]
Hi @Nix73,

Thanks for making that change!

It looks like you deleted some links that other students added to this project. You can see them listed in the index.html file by clicking on the Files Changed tab near the top of this page.

We want to preserve everyone's work so we'll need for you to add those back in before we can merge this into the main codebase. Once you fix that up, you can add, commit, and push and your changes will join your pull request here.

I also see that you added some images to the project. Unfortunately we cannot accept images in this repository - as it would quickly become too large. You can definitely link to existing online images, though! :)

Please remove your `img` directory with the images inside, and update your image links in your advice page. 

Then you'll need to run a slightly different git command (git add -A), commit, and push, your changes will join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by redrambles** [comment]
Hey @Nix73 !

Thanks for fixing up the index.html file - that one is good to go! Now all we need to do is remove the images that are still part of this pull request.

Let's just remove the images folder entirely:

`rm -r images`

Then go ahead and add that change:
`git add -A`

Then commit as per usual:
`git commit -m "Your message here"` 

And then let's push up your branch once more:
`git push origin advice`

Then we should be all set to merge this in. Let us know if you have any questions!

Cheers,
Ann :)

**Comment by Nix73** [comment]
Hi Ann,

So I removed the image folder. It no longer is in my local repo. How ever when I try follow your instructions it says there is no image folder.  
Screenshot 2020-10-20 at 09 14 51

**Comment by redrambles** [comment]
Hello @Nix73 !

Sorry for the delay!! Ok - so if you are on your `advice` branch right now (double check with `git status`) - and your image folder has been successfully deleted,  if you run `git status` you should see that Git has picked up on that deletion. You will then want to add that change with `git add -A`, and commit as per usual `git commit -m "Your message here"` and then finally push up your `advice` branch once more, which will automatically update this pull request.

Then we should be all set to merge this in.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by acodeinprogress** [comment]
Hey @Nix73,

I see that you made some changes to the index.html file but I'm still not seeing the removal of those images. We'll still need for those images to be removed before we can move forward with your pull request.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @Nix73,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
