### PR TITLE
Anna branch

### PR DESCRIPTION
**Pull request by AEFitzGerald**
Here is my first edits and page creation on a cloned repo!

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @AEFitzGerald,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by AEFitzGerald** [comment]
Hi Sharon,
Thank you! I included the link and pushed it on up :)
I hope you are having a great weekend.
All the best,
Anna

ANNA E FITZGERALD, ORB LLC
2201 NORTH DUSTY LANE
TUCSON, AZ 85749
512-757-0552
ORB.YOGA.LLC@gmail.com

**Comment by AEFitzGerald** [comment]
I resolved the conflicts when I did the upstream sync.

**Comment by redrambles** [comment]
Hey @AEFitzGerald,

You did a great job and your code is all merged in! Yay!

Cheers,
Ann :)

**Pull request merged**
