### PR TITLE
my advice re-done

### PR DESCRIPTION
**Pull request by trevans3**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @trevans3,

So sorry for the delay!

Ok! So I think that we have ourselves tangled up a bit here, so I'm going to suggest that you follow the next couple steps which will involve resetting your advice branch to a copy of what the master branch is on upstream and then adding in your code files and finally adding in your link to the main index.html file. It's the fastest/easiest way to get to where we want to go.

1. Make sure that you are inside your advice branch (git status will tell you which branch you are on - and so will git branch).
2. Using the Finder / File Explorer, find your advice/X.html file and temporarily tuck it away on your Desktop.
3. Do the same for your css/X.css file (if you have one)
4. Fetch from upstream `git fetch upstream`
5. Reset your advice branch to be an exact copy of the master branch on the upstream remote. This means that it will exactly match the main codebase as it is at this point in time. `git reset --hard upstream/master`
6. Move your html file from the desktop and place it inside the 'advice' directory
7. Move your css file from the desktop and place it inside the 'css' directory.
8. Open up the index.html file using your text editor of choice and add a link to your advice file.
9. Run git status. You should see three changes - your html file, your css file and the index.html file. Add everything with `git add -A`.
10. Commit as per usual `git commit -m "Your message here"`
11. Now we'll need to force push:` git push -f origin advice` - because we changed history with the reset command. This is ok to do in this instance because you are working alone on your own branch - no one else will be affected by this change in history.

Once that force push goes through, this pull request will be updated. At that time we should see on our end that the only changes included in your PR involve your own html and css files - and a modification to the index.html file (your link) - which is exactly what we want.

Then we should be all set to merge in your code.

Let us know if you have any questions!

**Comment by trevans3** [comment]
Hi Ann -
So I just went through to attempt to fix the workflow per your
instructions. However, when it came time to push -f origin advice
I got this error below.

$ git push -f origin advise
error: src refspec advise does not match any
error: failed to push some refs to 'github.com:trevans3/105-practice.git'

I've attached my command log for reference

Trevor E.

**Comment by redrambles** [comment]
Hey @trevans3,

Aha - you have a typo in your branch name for that last push command- instead of 'advise' it should be 'advice'

Want to give that force push command another try?

**Comment by trevans3** [comment]
Ahh, always the little typos!

Alright, I commanded another force push just now and hopefully it worked.

**Comment by redrambles** [comment]
Hey @trevans3 !

Yasss - thanks for making that change - your code is merged in!

Cheers,
Ann :)

**Pull request merged**
