### PR TITLE
Added Gareth M

### PR DESCRIPTION
**Pull request by Gareth-Morris**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @Gareth-Morris,

I noticed that you didn't add an advice page or any css. If you could add those things, that would be great! Once you do that, you can add, commit, and push your work and it will join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by Gareth-Morris** [comment]
Hi Sharon

I believe I have sorted out the advice page and CSS file; however, I
cant add commit and push the files. It says I need to resolve a merge. I
have no idea how to do this.

This is the directory I am in:

~/desktop/105-practice (advice|MERGING)

I dont know how to merge it, unmerge it, and I dont know what needs to be
merged - help!

Thanks

Gareth

**Comment by acodeinprogress** [comment]
Hey @Gareth-Morris,

Can you please send a screenshot of your terminal so that we can see the exact error message?

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @Gareth-Morris,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
