### PR TITLE
My advices's page ready and finished

### PR DESCRIPTION
**Pull request by juTelles**
Just dropping by to give some new advices to new developers....also, any feedback will be well received...

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @juTelles,

Great work so far! 
I see that you added a couple debug.log files (one in the advice folder and one in the main project folder). Unfortunately we cannot accept extraneous files in this repository - as it would quickly become too large. So please go ahead and remove both those of those files.

Also, we would like for you to include a link to your advice page in the index.html file.

Once you make those changes, you'll need to run a slightly different git command (git add -A), commit, and push, your changes will join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by juTelles** [comment]
Hi Sharon, 
I am sorry for those debug files, and thanks a lot for letting me know, because I actually thought they had come with the skillcrush files download, and it turns out that for some unknown reason some chromes browsers have a bug of creating this files automatically when you open a local html file in it, at least now I know and I can solve it, but what kind of developer don't release the sudden appearance of mysterious files in her project??

Well, I deleted the files and added the link into the index page, plus some minor changes in the page itself, then did the git commands you told me to do, please let me know if I did everything right!!

Bye and thanks very much!!
Juliana

**Comment by redrambles** [comment]
Hey @juTelles,

Thanks for making those changes -  did a great job and your code is all merged in! Yay!

Cheers,
Ann :)

P.S - Love what you did with this assignment! :)

**Comment by juTelles** [comment]
Hi @redrambles,
Thanks a lot, I am really happy to hear you liked my assignment!!!
Just so you know, you guys at skillcrush are great, and I am loving the course!!!
JuTelles

**Pull request merged**
