### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by pughdr45**
Try this again

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @pughdr45,

This looks great! I just have 1 teensy request before I merge this in.
It looks like you changed the stylesheet that the index page uses to your personal stylesheet. Instead, we only want your personal stylesheet to apply to your personal advice page. We still want the index page to use our general style.css stylesheet. If you could change it back, that would be great.
Once you do, you can add, commit, and push and your changes will join your pull request here.

Let me know if you need any help!

xoxo,
Sharon

**Comment by pughdr45** [comment]
Think I fixed it??

**Comment by pughdr45** [comment]
I think I it fixed. Not sure what to do now. I will probable do this lesson over.

**Comment by acodeinprogress** [comment]
Hey @pughdr45,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
