### PR TITLE
Adding Madeline's advice files

### PR DESCRIPTION
**Pull request by madgrds**
I'm not entirely sure if this is ending up where I want it--but I think I'm asking to be pulled into the main Skillcrush repo?

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @madgrds!

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. If you're not sure how to do this, feel free to take a look at other student links for reference. :)

Once you add your link, add and commit your changes and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by madgrds** [comment]
Thanks, Ann! Fixing now...

**Comment by madgrds** [comment]
@redrambles Ack, sorry, Ann. I just cannot figure this out. 

I made those changes to the main index file, then ran all the steps to merge with master:

screen shot 2019-02-21 at 10 03 54 am

But now...I can't seem to create a pull request?

screen shot 2019-02-21 at 10 09 51 am

I'm not sure what I'm doing wrong... Any ideas?

**Comment by redrambles** [comment]
Hey @madgrds !

This is really good! You don't need to create a new pull request - you just need to push up your branch, which has the new changes:

`git push origin experiments`

This will automatically update this existing pull request, and we should be good to merge it in.

**Comment by madgrds** [comment]
🙌 🙌 🙌 Awesome! Thanks, Ann. That was making my head spin.

**Comment by redrambles** [comment]
Thanks, @madgrds - you did a great job and your code is merged in. :)

**Pull request merged**
