### PR TITLE
Add My advice

### PR DESCRIPTION
**Pull request by JSkilz**
Some advice for some practice!

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @JSkilz,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by JSkilz** [comment]
Hi Sharon,
Thanks again for your help! I added the link and made a few changes. I think the new commit is part of the pull request now. Thanks again! 
Best,
Jen

**Comment by JSkilz** [comment]
> Hi Sharon,
> Thanks again for your help! I added the link and made a few changes. I think the new commit is part of the pull request now. Thanks again!
> Best,
> Jen

@acodeinprogress Just wanted to make sure this got to you and that it looks correct this time. thanks!

**Comment by acodeinprogress** [comment]
Hey @JSkilz,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
