### PR TITLE
Advice website branch

### PR DESCRIPTION
**Pull request by Havu1988**
Added my advice website

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @Havu1988,

Looks great so far! I see that you added some images to the project - one in the advice folder and one in our main folder. We like to keep our repository as simple and clean as possible so we cannot accept images. You can host the image online and then include a link in your code to the image. If you could remove the images then run a slightly different git command (git add -A), commit, and push, your changes will join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by Havu1988** [comment]
Hi Sharon, 
I deleted the pictures from the repo. Will you please check if everything is good now, or there is anything else i should be doing? 

Thank you !!

**Comment by acodeinprogress** [comment]
Hey @Havu1988,

Thanks so much! It looks like some lines were deleted in the main index.html file. You can see what was removed by clicking the [Files Changed](https://github.com/skillcrush/105-practice/pull/184/files) tab near the top of this page.

Those lines were added by other students and we'd like to preserve their code so they will need to be added back in.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @Havu1988,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
