### PR TITLE
added elan advice and css styles

### PR DESCRIPTION
**Pull request by ekara83**
adding elan advice and css styles

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @ekara83,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by ekara83** [comment]
thanks @acodeinprogress! I've added the link!

**Comment by ekara83** [comment]
Advice I would like to share

**Comment by acodeinprogress** [comment]
Hey @ekara83,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
