### PR TITLE
coded and styled my advice page

### PR DESCRIPTION
**Pull request by amc538**
This is my advice page.  I kept it simple, for now. :-)

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @amc538,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by amc538** [comment]
I'm sorry,  I just saw this message.  I'll take care of it tonight 😉

**Comment by amc538** [comment]
Git is my weak point.  I'm practicing it every chance I get. I hope I did this right :-)

**Comment by acodeinprogress** [comment]
Hey @amc538,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
