### PR TITLE
Experiments

### PR DESCRIPTION
**Pull request by AliShin**
Some advice I would like to share.

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @AliShin,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by AliShin** [comment]
Hi Sharon,

I remember adding a link in the index.html, added, committed, pushed and
pulled. Do you mind guiding me? I tried doing it few times before I pulled
the request as it wasn’t the expected solution.

Kind regards,
Alexandra Shin

**Comment by AliShin** [comment]
It previously showed I had a conflict regarding index.html and I merged conflict. I could still use your guidance to understand what exactly went wrong.

**Comment by acodeinprogress** [comment]
Hey @AliShin,

It's possible that you erased the link that you added to the index.html file when you fixed the merge conflict, thereby erasing any changes. Although usually some sort of change shows up.

I would suggest running through your fetch and merge commands again and then go ahead and open up the index.html file in your text editor and add another link. Then you should be good to add, commit, and push up to GitHub. You'll want to make sure that you do your work on your experiments branch on your computer and then push up to your experiments branch on GitHub.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @AliShin,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
