### PR TITLE
Added and styled two sections of content

### PR DESCRIPTION
**Pull request by annabertel**
Here is my contribution to the collaborative advice page!

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @annabertel,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by annabertel** [comment]
Hey Sharon,

I believe I've done this now--did my changes join my pull request?

Anna :)

**Comment by acodeinprogress** [comment]
Hey @annabertel,

I'm not seeing those changes. Did you make sure to push them to GitHub?

xoxo,
Sharon

**Comment by redrambles** [comment]
Hey @annabertel,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Pull request closed without merging**
