### PR TITLE
Added my advice

### PR DESCRIPTION
**Pull request by MorganEJLA**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @MorganEJLA !

We have your link in the index.html file, but we don't have your 'advice/morgan-j-advice.html' file. Have  a look a the result of `git status` - it may be that it hasn't yet been added and/or committed. If it has - then it must still need to be pushed `git push origin advice`.

Once your file is pushed up - we should be all good to merge in your changes.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by MorganEJLA** [comment]
Hi i keep getting this message now

morganjones🖤 git push origin advice
ERROR: Permission to skillcrush/105-practice.git denied to MorganEJLA.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
morganjones🖤

**Comment by redrambles** [comment]
Hey there! 

Ok - so your 'origin' remote connection is pointing to skillcrush's repository - which you don't have write access to, which is why you are getting that error. Let's change that 'origin' address to point to your repo instead, like this:

``` git remote set-url origin git@github.com:MorganEJLA/105-practice.git```

Then go ahead and try `git push origin advice` again. What is the result?

**Comment by redrambles** [comment]
Hey @MorganEJLA,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Pull request closed without merging**
