### PR TITLE
105 practice assignment

### PR DESCRIPTION
**Pull request by GillianTrethewey**
Advice to share!

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @GillianTrethewey,

Your advice file looks great! There are just a couple things that you'll need to fix up before we can merge this in:

1. It looks like you added an HTML advice file in the `css` folder rather than a personal stylesheet to go along with your HTML advice file.
2. We would like for you to edit the index.html file and add a link that directs to your HTML advice page.

Once you make those changes, you'll want to run `git add -A`, then commit and push to GitHub. When you do this, you'll want to make sure that you make your changes on your `105-practice-assignment` branch and then push to that same branch on GitHub.

xoxo,
Sharon

**Comment by GillianTrethewey** [comment]
Thanks Sharon. I added the link to the index.html file and fixed the css file that had been overwritten. Gillian :)

**Comment by GillianTrethewey** [comment]
Should be fixed. Sorry just learning how the comments work and closed by mistake.

**Comment by redrambles** [comment]
Hey @GillianTrethewey,

You did a great job and your code is all merged in! Yay!

Cheers,
Ann :)

**Pull request merged**
