### PR TITLE
added sergio-c-advice.html to index.html

### PR DESCRIPTION
**Pull request by tinygvillage**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @tinygvillage !

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that long list. :)

Once you add your link, add and commit your changes and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by tinygvillage** [comment]
Hi there Ann,

    So, I’m having an issue. This happened yesterday when I was working on the assignment, however, I wasn’t sure if it was a normal read on the Command Line. Here is a screenshot of what I experienced when trying to fetch the upstream:



On March 21, 2020 at 11:10:13 AM, Ann Cascarano (notifications@github.com) wrote:

Hey @tinygvillage !

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that long list. :)

Once you add your link, add and commit your changes and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by tinygvillage** [comment]
So, on my end, the main index.html had been updated, but perhaps I didn’t update it correctly? 


On March 21, 2020 at 11:10:13 AM, Ann Cascarano (notifications@github.com) wrote:

Hey @tinygvillage !

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that long list. :)

Once you add your link, add and commit your changes and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by redrambles** [comment]
Hey @tinygvillage !

Thanks for making that change - everything is looking great! Merging in! :)

Cheers,
Ann :)

**Pull request merged**
