### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by stulinden**
added some style to html!!!

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @stulinden,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by stulinden** [comment]
Scroll to the very end it's there

Sent from my iPhone

________________________________

**Comment by stulinden** [comment]
I think I fixed everthing.

**Comment by redrambles** [comment]
Hey @stulinden,

You did a great job and your code is all merged in! Yay!

Cheers,
Ann :)

**Pull request merged**
