### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by amanda-walton**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @amanda-walton,

Congrats on making your first pull request!

If we take a look at the [Files changed](https://github.com/skillcrush/105-practice/pull/1140/files) tab near the top of this page, we can see that a large number of files were edited and that some of them have merge conflicts.

We'll need for you to fix up those changes before we can get this merged in. Once you do, you can add, commit, and push. 

Let us know if you need any help!

xoxo,
Sharon

**Comment by amanda-walton** [comment]
Hi Sharon,

I need some help thanks. I fixed the merge conflicts in my html files and re-committed. But it's still showing 68 files changed. Most of those are not my files, so I'm not sure how to fix the conflicts. Thanks for your help! This is actually the second time I have taken the git class and I still can't get my head around how it works!

Amanda

**Comment by amanda-walton** [comment]
@acodeinprogress I just wanted to follow up on this. The message above I think is telling me to add more commits by pushing to the advice branch. But when I run git status on that branch it says nothing to commit. I'm at a loss for how to fix this.

**Comment by acodeinprogress** [comment]
Hey @amanda-walton,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
