### PR TITLE
added my advice

### PR DESCRIPTION
**Pull request by denism21**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @denism21 !

This is great! The only thing is that you have made a change in someone else's file (css/abowler-advice.css) - which you can see on the '[files changed' page here.](https://github.com/skillcrush/105-practice/pull/863/files) Please return the style back to its original value, and then add and commit that change and push up your advice branch once again.

This will automatically update your pull request, and we should then be all set to merge in your code. 

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by denism21** [comment]
Yeah I am not sure that I know how to do that.  I am really struggling with understanding how git works.
Denis

**Comment by redrambles** [comment]
Hey @denism21 !

No worries - I can walk you through it. All we want to do right now is restore the previous version of this file 'css/abowler-advice.css'. The easiest way to go about doing that is:

1) Make sure you are on your advice branch
2) Run `git checkout master css/abowler-advice.css `. This will overwrite the version of the file in your advice branch with the original version of the file that is on the master branch.
3) Add and commit your changes with `git add -A` `git commit -m 'Correct accidental edit'` (or message of your choice)
4) Push up your advice branch once more: `git push origin advice`

That's it! Now your code should be all set to be merged in. 

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by acodeinprogress** [comment]
Hey @denism21,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
