### PR TITLE
added jared-p-advice.html

### PR DESCRIPTION
**Pull request by Jared-P-111**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @Jared-P-111!

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that long list. :)

Once you add your link, add and commit your changes and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by Jared-P-111** [comment]
Hey redrambles, 

I missed it! Darn, I must say git is kinda confusing but I think I am starting to git the hang of it. I pushed the index.html so if that updates the pull request we should be good. I put the link at the top of index.html. Thanks and let me know if I messed it up again.

**Comment by acodeinprogress** [comment]
Hi @Jared-P-111,

Did you make sure to push your changes up to the advice branch on GitHub?

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @Jared-P-111,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
