### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by kelsey-mcduke**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @kelsey-mcduke,

Congrats on making your first pull request. Unfortunately, it looks like you removed a couple of students links in the index.html file when you added your own. We want to preserve everyone's work so you will need to add those links back in. You can see which links were removed by looking at the [Files Changed](https://github.com/skillcrush/105-practice/pull/1127/files) tab near the top of this page.

Once you do that, you'll need to add, commit, and push. Your changes will join your pull request here and then we should be able to get it merged in!

xoxo,
Sharon

**Comment by kelsey-mcduke** [comment]
Hey!

I added back in the two links that somehow were deleted when I tried to fix the conflicts before. I am seeing now on GitHub that there are conflicts again. Am I to resolve these too before this can merge?

**Comment by acodeinprogress** [comment]
Hey @kelsey-mcduke!

Thanks for fixing that up! If you'd like to practice resolving those merge conflicts, you're welcome to. If not, we can take care of it for you. Just let us know what you'd like to do. :)

xoxo,
Sharon

**Comment by kelsey-mcduke** [comment]
Hello!

I did a second fetch from upstream, since it has been a minute since I submitted my request and resolved the conflicts for extra practice. Please let me know if I made any more mistakes. 

Thank you!

**Comment by acodeinprogress** [comment]
Hey @kelsey-mcduke,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
