### PR TITLE
New advice page

### PR DESCRIPTION
**Pull request by steve3236**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @steve3236 !

You are close! There are just two little things to address:

1) You have an additional css file `stevens.css` that is in the root of the project. Please delete it. You have another css file `css/stevens.css` which is in the correct location.
2) Your advice html file is in the root of the project (`steven-s-advice.html`) - You'll need to move it into the `advice` directory.

Once those changes are made, please add with `git add -A` then commit `git commit -m "Your message here"` and then finally push up your advice branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code! Let us know if you have any questions.

Cheers,
Ann :)

**Comment by steve3236** [comment]
Ann
I have searched all over in windows explorer for this file and can’t locate. I remember creating it. I searched by way of github and also tried the other’rm’ command.
Thanks 
Steve

**Comment by redrambles** [comment]
Hey @steve3236 !

Ok! So the first thing you will want to do is move into this repository using GitBash, and then make sure that your `advice` branch is checked out. Remember that these files only exist on that branch. When you do that, if you run `ls` you should see a ` stevens.css` and a `steven-s-advice.html` listed - along with the index.htmt file and our advice and css directories.

Given that we want to remove the `steven.css` file, we can do this by running `rm steven.css`. 

Next - we want to move the `steven-s-advice.html` file into the advice folder, which we can also do quickly in Git Bash: `mv steven-s-advice.html advice/`

That's it! Then if you run `git status` - you should see these changes listed there. You'll want to use `git add -A' to add them to the staging index, and then commit as per usual with `git commit -m "Your message here"` and then push up your advice branch once more `git push origin advice`.

Then we should be good to go. Keep us posted!

Cheers,
Ann :)

**Comment by steve3236** [comment]
Ann
Thanks for your patience. I think everything is as it should be to approve the pull request.
Thanks 
Steve

**Comment by acodeinprogress** [comment]
Hey @steve3236,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
