### PR TITLE
bailey-advice added

### PR DESCRIPTION
**Pull request by stratoTX**
my edits. hoping I did this right

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @stratoTX,

This looks great! I just have a couple teensy requests before I merge this in:
1. We would like for you to include a link to your advice page in the index.html file.
2. It would be great if you would add a personal stylesheet with some styles for your advice page.

If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by stratoTX** [comment]
edited bailey-advice.html, bailey-advice.css and created link on index html

**Comment by stratoTX** [comment]
so lost with GitHub

**Comment by acodeinprogress** [comment]
Hey @stratoTX,

Ok, so it looks like some extra things happened when you updated your code.
1. There is an extra file in the css folder called `Bailey's Advice For Newbies.webarchive`. We'll need to delete that file.
2. It looks like you added some extra links in the index.html file. Those will also need to be removed.

Once you make those changes, you can run a slightly different git command (`git add -A`), commit, and push. Then we can get everything merged in.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @stratoTX,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
