### PR TITLE
Forking workflow assignment

### PR DESCRIPTION
**Pull request by Stephanie0412**
I am really feeling like I did something wrong here. Thanks for your help.

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @Stephanie0412 !

Great job on this so far! The only thing we need from you before we can merge this in, is for you to remove your conflict markers in the index.html file. If you have a look at this link (https://github.com/skillcrush/105-practice/pull/1325/files) and scroll down until you get to the index.html file, you'll see what I mean.

There are three lines with conflict markers to remove. Once you do, save, add and commit your change and then push up your branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code. Let us know if you have any questions!

Cheers,
Ann :)

**Comment by Stephanie0412** [comment]
I think this did it. Thanks!

**Comment by redrambles** [comment]
Hey @Stephanie0412,

Thanks for making those changes! Your code is merged in!

Cheers,
Ann :)

**Comment by Stephanie0412** [comment]
Thank you!
On Wednesday, June 24, 2020 Ann Cascarano <reply@reply.github.com> wrote:



Hey @Stephanie0412,

Thanks for making those changes! Your code is merged in!

Cheers,
Ann :)

**Pull request merged**
