### PR TITLE
adding my advice html and css page

### PR DESCRIPTION
**Pull request by The-Jewell**
adding my advice html and styles

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @The-Jewell!

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. 

Once you add your link, add and commit your changes and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by The-Jewell** [comment]
ok, i got the change made and i think I was able to commit them and push them up.

**Comment by redrambles** [comment]
Hey @The-Jewell !

We still don't have any changes on our end. Did you make the change on your 'josephjewelladvice' branch? If so, once you've added and committed the change, you'll push up branch like this: 
`git push origin josephjewelladvice`
And that will automatically update this pull request.

Keep us posted!

Cheers,
Ann

**Comment by The-Jewell** [comment]
Alright when I use open . on the josephjewelladvice branch the main index has the link the my advice page at the very top. I used the git push origin josephjewelladvice and it seemed to push it up. Let me know if that worked! Thanks.

**Comment by acodeinprogress** [comment]
Hey @The-Jewell,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
