### PR TITLE
Updated advice page

### PR DESCRIPTION
**Pull request by jen-neu**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @jen-neu !

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that long list. :)

Once you add your link, add and commit your changes and then push your advice branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by jen-neu** [comment]
Hi Anne,

I made the changes you mentioned. Fingers crossed it worked!

Cheers,
Jen 😊

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by redrambles** [comment]
Hey @jen-neu !

We didn't receive the changes on our end yet. Did you remember to push up your advice branch? `git push origin advice`

Keep us posted!

Cheers,
Ann :)

**Comment by jen-neu** [comment]
Hi Ann,

Ug, it doesn’t seem to be working. I don’t know what I’m doing wrong. I’ve updated the index.html with my advice link. I’ve tried to push my changes to the forked 105-practice.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by redrambles** [comment]
Hey @jen-neu,

It worked!! Everything was updated and your code has been merged in. Yay!

Cheers,
Ann :)

**Comment by jen-neu** [comment]
Yay!! Thanks. 🎉

Sent from my iPhone

On Sep 24, 2020, at 5:07 PM, Ann Cascarano <notifications@github.com> wrote:

﻿

Merged #1545<https://github.com/skillcrush/105-practice/pull/1545> into master.

**Pull request merged**
