### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by Indra-M**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @Indra-M,

This is great!! The only thing is that you accidentally deleted some other students' files from the advice folder and we are going to want those back. (You can see the diff of your pull request [here](https://github.com/skillcrush/105-practice/pull/1731/files) if you are curious.)

Once you add the files back, please add the change with git add -A, commit as per usual and push up your advice branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code. Let us know if you have any questions!

xoxo,
Sharon

**Comment by Indra-M** [comment]
Hello! I don’t know how I managed to delete someone else’s link but I think I got it added back!

Thanks!

Indra Mohabir
614-940-4288

**Comment by Indra-M** [comment]
Hello- I think I got the files I accidentally removed back to the 105-practice index.html file successfully. Please let me know if there’s anything else I need to fix! 

Thanks! 

Indra Mohabir
614-940-4288

**Comment by acodeinprogress** [comment]
Hey @Indra-M,

Now it looks like there have been quite a lot of changes to the index.html file - so many that it's difficult to fix up. 
There are a few ways that you could resolve this.

You could visit the original code base here: [https://github.com/skillcrush/105-practice](https://github.com/skillcrush/105-practice) - open up the index.html file and copy everything inside it. Then you can paste it inside your own index.html file - and add your own link at the bottom of the link.

Because this is Git - there is an easier way! You can replace the version of the index.html file that exists inside your advice branch with the one on the master branch with this command:

git checkout master index.html

And then you can open up the file in your text editor and add your link at the bottom of the list.

Once you have chosen and executed either one of the above options - make sure to save your file - then in the Terminal add with git add -A, commit git commit -m "Your message here" and then push up your advice branch one more time git push origin advice. This will update your pull request and we should then be all set to merge in your code.

Also, if you take a look at the Files Changed tab near the top of the page, you can see that you also deleted individual files (not just links in the index.html file) that other students created. You'll also need to make sure to restore each HTML file that was deleted as well.

Let us know if you have any questions!

xoxo,
Sharon

**Comment by Indra-M** [comment]
Hi Sharon,
I pasted the master index.html file over mine in my editor, added my name to the bottom of the list and pushed it to my advice branch. It is displaying correctly in the advice folder in GitHub but not in the index.html file listed at the bottom under the README.md file. I need to remove that file but I’m afraid to do it in case I might delete the correct in one in the advice folder. Can you tell me how to remove it correctly? 


Thanks.

Indra Mohabir
614-940-4288

**Comment by acodeinprogress** [comment]
Hey @Indra-M,

Thanks for the update!

Unfortunately, it looks like you may have added the index.html file to the advice folder instead of replacing the one that is already in the root folder of this project.

The first issue I mentioned is also present: The only thing is that you accidentally deleted some other students' files from the advice folder and we are going to want those back. (You can see the [diff](https://github.com/skillcrush/105-practice/pull/1731/files) of your pull request here if you are curious.)

You'll need to delete the index.html file that you added to the advice folder and then try again by replacing the one in the root folder of the project. Then you'll need to restore the deleted student files and then `git add -A`, commit and push. Then this should be in a good place to merge!

xoxo,
Sharon

**Comment by Indra-M** [comment]
Hi Sharon,
I’m so sorry for all the trouble and confusion on my part! I think I’ve got it right now! I added Henry’s file back to the Advice folder along with mine and I removed the index.html file from the Advice folder and moved it back to the root.

Thanks!!

Indra Mohabir
614-940-4288

**Comment by acodeinprogress** [comment]
Hey @Indra-M,

Unfortunately, I'm not seeing any changes on this pull request. Did you make sure to make your changes on the advice branch and then push them to the advice branch on GitHub?

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @Indra-M,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
