### PR TITLE
added laurenh advice html/css

### PR DESCRIPTION
**Pull request by lhilmers**
added Lauren's advice

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @lhilmers,

This looks great so far!

I see that you changed a lot of the formatting of the index.html page. This makes it very difficult to tell if you accidentally removed or added any lines of code. We would love it if you could keep the same formatting and simply add a link to your advice page in that file.

Once you make those changes, you can add, commit, and push and your changes will join your pull request here.

xoxo,
Sharon

**Comment by lhilmers** [comment]
Hi Sharon! 
Lol I knew something was off. What would be the best way to correct my mistake? Is this something I should start over? Thank you so much for your feedback. 
-Lauren

**Comment by redrambles** [comment]
Hey @lhilmers !

No worries, we can guide you through this. You *could* just copy the index.html file from your master branch and then paste it over your experiments' branch index.html file, and then just add your link at the bottom of the page, leaving the rest of the page untouched - or, we can make use of some of Git's power:

1) While you are still in your experiments branch, run:

`git checkout e24f8c8e12d7 index.html `

This will checkout the version of the index.html page in the previous commit, pulling it into your current code, and overwriting all the formatting changes. You're basically rewinding that specific file back in time just a little. Then, you'll want to add your link to your advice page at the bottom of the list, and add and commit that change.

Once you're good there, push up your branch again (`git push origin experiments`) - and this will update your pull request. We should then be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann

**Comment by lhilmers** [comment]
Hi Ann,
I hope I fixed my errors correctly! Thank you for all your help!
-Lauren

**Comment by redrambles** [comment]
Hey there! 

Hmm - something didn't go according to plan here. It's a bit tricky so I have two suggestions for you:
1) If you can attend a Dev Q&A with me, we can go through the steps together, 'live' - while screensharing.
2) You can decide to copy/paste the entire index.html file from your master branch (or the skillcrush repo) and then replace the contents of your experiment branch's index.html file with it, and then just add your link at the bottom of the list
3) You can leave it to us to fix up. :)

Let us know what you'd like to do! :)

Cheers,
Ann

**Comment by lhilmers** [comment]
Hi Ann,
Clearly this is my Kryptonite lol! Ok, I wanted to try fix this so I copied the index.html file. If that didn't work then we'll definitely set up a Q & A!
-Lauren

**Comment by redrambles** [comment]
Hey @lhilmers,

Yaasss!!! You did a great job and your code is all merged in! Yay!

Cheers,
Ann :)

**Pull request merged**
