### PR TITLE
jason hall advice page

### PR DESCRIPTION
**Pull request by BoxOfCrayons**
Git, Github, and the Terminal were more exciting than I thought they would be. Sorry that I didn't get more creative with the HTML and CSS on this one - I was juggling 105 with keeping my 5 year-old sane on this snowy, yucky south central PA weekend.

### CODE REVIEW

**Comment by redrambles** [comment]
Hello @BoxOfCrayons !

Glad that you are finding Git / GitHub more interesting than expected! :) Hopefully with some more time you will become as big a fan as we are. :)

Ok! So we got your advice html file as part of this pull request, but it is in the root of the directory rather than inside the 'advice' folder. We also don't have any CSS, nor a link to your advice page from the main index.html file - so this is what we would like you to do:

1) Move your `jasonhall-advice.html` file inside the `advice/` directory.
2) Create a stylesheet inside the `css/` directory (maybe called `jasonhall-styles.css`) - and put a bit of CSS in there. (Doesn't need to be fancy!) Make sure to link your advice html page to your stylesheet.
3) Please add a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. If you're not sure how to do this, feel free to take a look at other students links for reference.

Once you have made these changes, please add with `git add -A`, commit your changes `git commit -m "your message here"` and then push up your 'experiments' branch once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by BoxOfCrayons** [comment]
Thank you for the advice, Ann! I moved the html into the advice directory. I did have a CSS created, but neglected to link it to my html. It's been added, committed, so hopefully it's good to now.

**Comment by redrambles** [comment]
Hey there! 

Ok that's awesome -but there haven't been any changes made to this pull request. When you committed your changes, did you forget to push? You will need to run `git push origin experiments` in order to have your changes show up here.

**Comment by acodeinprogress** [comment]
Hey @BoxOfCrayons,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
