### PR TITLE
Added personalized style sheet and advice for Camberly N

### PR DESCRIPTION
**Pull request by crncodes**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @crncodes !

This is great! The only thing is that your `camberly-n-advice.html` file is in the root of the folder - but we need it to be inside the `advice` directory. Please move it into the advice directory - and then edit your link to the css so that the relative link to the file functions given the new location of your HTML page. Once that's done - please add with `git add -A` and commit as per usual (`git commit -m "Your message here"`) and then push up your advice branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code! :)

Let us know if you have any questions.

Cheers,
Ann :)

**Comment by crncodes** [comment]
Thanks! I think I fixed it. I was wondering why I had to write the link to my stylesheet differently the first time!

**Comment by crncodes** [comment]
Hello,

Is this a conflict that I need to fix before it can be approved?

**Comment by redrambles** [comment]
Hello @crncodes !

Sorry it took me a bit to circle back - but everything looks great here! Your pull request has been approved. Yay!!!

Cheers,
Ann :)

**Pull request merged**
