### PR TITLE
Added rachel advice

### PR DESCRIPTION
**Pull request by racleong**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @racleong !

This is looking great! The only issue is that there is a space in the name of your advice file: `advice/rachel- l-advice.html` - which will break the link. No worries, this is an easy fix!

In the Terminal, run:
`git mv advice/rachel- l-advice.html advice/rachel-l-advice.html`

And then add the change with `git add -A` - and commit as per usual. Then push up your advice file once more - which will automatically update this pull request, and we should be all set to merge in your code. 

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by racleong** [comment]
Hi Ann,
Thanks for coming back to me.
I ran the above as suggested and it comes up with this "fatal: destination 'advice/rachel-l-advice.html' is not a directory".
Please let me know what to do.
Thanks so much,
Rachel

**Comment by redrambles** [comment]
Hey @racleong !

Arg - that's annoying - sorry about that! Ok so let's move into the advice directory first:
`cd advice`

And then run this:
`git mv "rachel- l-advice.html" rachel-l-advice.html`

When you next run `git status` - you should see that Git has picked up the name change. Then you can go ahead and add with `git add -A` and commit as per usual `git commit -m "Your message here"` and push up your `advice` branch once more.

Keep us posted!

**Comment by racleong** [comment]
@redrambles Thx Ann, I got it :)

**Comment by acodeinprogress** [comment]
Hey @racleong,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
