### PR TITLE
Changed name in html file

### PR DESCRIPTION
**Pull request by dmariet3**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @dmariet3,

Congrats on making your first pull request!

I see that you added an extra file to this project: your-name-advice.html.zip

You'll need to remove that file and then run `git add -A`, commit, and push, your changes will join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by dmariet3** [comment]
Hi @acodeinprogress ,
I've been struggling with this part. I ended up editing my files while waiting, and so I made changes to my html and css file. I also deleted the zip file. Here is a screenshot of what happens when I try to push my files. Im not sure why it failed.
Screen Shot 2020-04-29 at 11 52 48 AM

**Comment by acodeinprogress** [comment]
Hey @dmariet3,

Did you make any changes to your advice branch directly on GitHub?

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @dmariet3,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
