### PR TITLE
created 105-project HTML and CSS files

### PR DESCRIPTION
**Pull request by mbsgolden**
First Pull Request

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @mbsgolden,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by mbsgolden** [comment]
Ok, I think I did that. Would you be able to clarify what origin means?

Thanks!

Molly

**Comment by acodeinprogress** [comment]
Hey @mbsgolden,

I'm not seeing your changes here. Did you make sure to make them on your 105-experiment branch and push to your 105-experiment branch on GitHub?

When we say something like:
`git push origin master`
the only part of this command that will always be the same is the `git push` part.
`origin` is the name of the remote repo that we want to use.
If you run `git remote -v`, it will give you a list of remote repos. `origin` is the standard but it's possible to give your remote repos whatever name you want.
The `master` part is whatever branch we want to push to. So if you were updated your 105-experiment branch, you would run
`git push origin 105-experiment`
Does that help clarify?

xoxo,
Sharon

**Comment by mbsgolden** [comment]
Ok, I pushed it to the master not the branch called 105-experiments so you
should see it now.  Could you clarify why it indicates both a fetch and a
pull origin... such as this:

origin git@github.com:mbsgolden/105-practice.git (fetch)

origin git@github.com:mbsgolden/105-practice.git (push)

upstream git@github.com:skillcrush/105-practice.git (fetch)

upstream git@github.com:skillcrush/105-practice.git (push)


Thanks!


Molly

**Comment by acodeinprogress** [comment]
Hey @mbsgolden,

Awesome! Those changes are showing up now. It also looks like you removed the .gitignore file. We actually need that present in our repo. Would you mind adding that back in and then adding, committing, and pushing back to GitHub?

The fetch and pull are just showing you different protocols but you don't need to worry about those. The important part is the address that the names are set to. For example, your origin is set to git@github.com:mbsgolden/105-practice.git.

I hope this helps!

xoxo,
Sharon

**Comment by mbsgolden** [comment]
Hi Sharon,
Whoops sorry about that. I was deleting local .gitignore files in my repos
so that I could set up one global .gitignore on my computer and then I was
making changes to my other repos on Github,  but somewhere along the way I
changed the 105-experiment repo accidentally. Sorry about that. Do you have
advice for using .gitignore? I created a global .gitignore, but not sure if
that's best practice.

Thanks,

Molly

**Comment by redrambles** [comment]
Hello @mbsgolden !

Using a global .gitignore file is great for files that you are going to want to consistently keep out of your Git repo, no matter the project. The mac's '.DS_Store' is a great example of a file that would belong on a global .gitignore file. However - all of my local projects also have a .gitignore file - as there will be specific files that you will want to ignore on a 'per project' basis. 

Hope that helps clarify! In the meantime, when please add the .gitignore for this project back in  your 105-experiment branch, add and commit that change, and push up your branch once more so that the update is reflected here in your pull request. Then we should be all set to merge in your code!

Cheers,
Ann

**Comment by acodeinprogress** [comment]
Hey @mbsgolden,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Comment by mbsgolden** [comment]
Hi Sharon,

When I submit pull request it says that I have two  conflicting
files...  " .gitignore
and index.html". Would you be able to clarify what I must do? I added a
.gitignore file to my local repo branch called 105-experiment and pushed it
to the origin master branch.

Thanks!

Molly

**Pull request closed without merging**
