### PR TITLE
changes to 105-practice

### PR DESCRIPTION
**Pull request by bledsoeci**
Second submission for this exercise. Gets easier each time.

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @bledsoeci,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by bledsoeci** [comment]
Hi Sharon,
I checked the index.html file and my advice file is attached (<a
href="advice/advice-katieb.html" target="_blank">Katie B's advice</a><br>).
And I checked on my terminal using git status and there is nothing to add,
so I'm not sure what I'm missing.

I've attached screenshots of both the terminal and the index.html files.

Thank you,

Catherine

**Comment by acodeinprogress** [comment]
Hey @bledsoeci,

If we look at the Files Changed tab near the top of this page, it's not showing any modifications to the index.html file. Did you make sure that you have that change on your 105-practice branch and that you pushed it to your 105-practice branch on Github?

xoxo,
Sharon

**Comment by bledsoeci** [comment]
Ok, I did not push the file last time, so I have now pushed the file and
attached the screenshot. Do I need to do a pull request again? I went on
Github to check, hit "new pull request" and "compare across forks," but the
comment and pull request option did not come up like it did when I
submitted the previous pull request.

**Comment by acodeinprogress** [comment]
Hey @bledsoeci,

This is perfect! The changes were automatically added to this pull request. and now your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif). Yay!


xoxo,
Sharon

**Comment by bledsoeci** [comment]
Good morning Sharon,
Fabulous! Thank you for your help!

**Pull request merged**
