### PR TITLE
Add Advice

### PR DESCRIPTION
**Pull request by SilmaAG**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @SilmaAG !

This is as good start! We got your link to your `advice/eirnin-m-advice.html` file inside the main index.html file (yay!) but no such html file is part of your pull request. Perhaps it still need to be added and committed? Checking `git status` will help you confirm.

Once you have added and committed your advice page, please push up your `advice` branch once more, which will automatically update this pull request. Then we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by SilmaAG** [comment]
Okay I've done this twice and I can't figure out how to add or commit my advice page. Also that's not my advice file. Mine should be advice/silma-g-advice.html 
I've followed the instructions step by step but I really can't figure it out.

**Comment by SilmaAG** [comment]
@redrambles 

I tried it again. Please let me know if it worked :(

**Comment by redrambles** [comment]
Hey @SilmaAG !

Worked like a charm, you are all set!! Your code has been merged in. Yay!

Cheers,
Ann :)

**Pull request merged**
