### PR TITLE
Changed website into an Ella-May website

### PR DESCRIPTION
**Pull request by em-qr**
I tried adding an image but to no avail! was it do-able? and if so how?

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @em-qr !

This is a great start!

Unfortunately we cannot accept images as part of student pull requests, as the repository would soon get too large. You are free to link to a version of the image that is hosted somewhere on the internet, though, of course! :) 

1) Please delete the 'img' directory
2) Your `advice/ella-may-qr-advice.html.html` file has an additional `.html` extension - so let's remove that. You can do so easily with this command: `git mv advice/ella-may-qr-advice.html.html advice/ella-may-qr-advice.html`

Once this is done - add your changes with `git add -A` - then commit as per usual, and then push up your advice branch once more, which will automatically update your pull request. Then we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by acodeinprogress** [comment]
Hey @em-qr,

Thanks for making that change! It looks like your `img` folder and image file are still showing as additions here. Unfortunately we cannot accept images in this repository - as it would quickly become too large. You can definitely link to existing online images, though! :)

Please remove your `img` directory with the image inside, and update your image link in your advice page. 

Also, your link in the index.html file has an extra period at the end. You'll want to remove that so that it does't show on the page.

Once you do that, you'll need to run `git add -A`, commit, and push, your changes will join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by redrambles** [comment]
Hey @em-qr !

Thanks so much for making that change! We are nearly good to go - the only thing is that a `debug.log` file appears to have joined the pull request party here, and we really don't need that file. :) 

Please remove the `debug.log` file, and then add `git add -A` and commit as per usual - and then push up your advice branch once more. Then we should really really really be all set!! :)

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by redrambles** [comment]
Hey @em-qr !

Thanks for making those changes - your code is all merged in! Yay!

Cheers,
Ann :)

**Pull request merged**
