### PR TITLE
janae advice

### PR DESCRIPTION
**Pull request by jnae368**
Wish me luck! Git is a beast but it's empowering to learn...and review again...cause beast.

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @jnae368 !

This is great - we just have two things that we need to address:

1) We are missing a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. If you're not sure how to do this, feel free to take a look at other students links for reference. :)

2) If you look at your pull request files here, you'll notice an additional file called 'advice/New Rich Text Document.rtf' - which we don't want. Please delete this file.

Once you have made these changes, please add your changes with `git add -A`, then commit them and push your branch up once more, which will automatically update your pull request. At that point we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by jnae368** [comment]
Hi Ann,

Thank you for the detailed reply. I've made the (very obvious) updates and re-added and committed the changes? I am not fully used to Github so doing these steps a little out of context, I am hoping that all went well this time. Thank you again.

Janae

**Comment by acodeinprogress** [comment]
Hey @jnae368!

Thanks for making those changes!

It looks like you accidentally removed the `.gitignore` file rather than the extra advice file, which is called `New Rich Text Document.rtf` and resides in the advice folder.

We'll need the `.gitignore` file to be restored and the extra .rtf advice file to be removed.

Once you make those changes, you'll run `git add -A` again, commit, and push.

Then we can get this all merged in!

xoxo,
Sharon

**Comment by jnae368** [comment]
Ughhh...one thing I know about my learning style is that besides being hands-on, I make silly mistakes while I am learning at the beginning but once I know "it" I know it enough to optimize and change personal aspects about things like the workflow, etc. Looking forward to that day with coding...

**Comment by acodeinprogress** [comment]
Hey @jnae368,

Thanks for making that you change - you did a great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
