### PR TITLE
Added advice from jessie g

### PR DESCRIPTION
**Pull request by JessieG57**
So far I think this is how it's supposed to go!  This is life advice, not coding advice.

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @JessieG57 !

This is looking good!! The only issue is that you deleted a link from another student in the main index.html file by mistake. See [here](https://github.com/skillcrush/105-practice/pull/208/files) - scroll down to the index.html file. The red line on the left hand side shows what has been deleted. If you can add that line back in, and then add and commit your change and push up your branch once more, it will automatically update this pull request and we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann

**Comment by JessieG57** [comment]
Hi Ann-
Okay, I did it.  Not 100% sure I did it correctly, so any feedback is
appreciated.  Thanks!

Cheers,
Jessie

**Comment by acodeinprogress** [comment]
Hey @JessieG57,

I'm not seeing your changes here. Did you make sure to make those changes on your take1 branch on your computer and then push to your take1 branch on GitHub?

xoxo,
Sharon

**Comment by JessieG57** [comment]
Hi there-

Okay. I went back and made the changes on my Take1 branch.  I used the "git
push origin master" command.  Does that update the pull request, as Ann
referenced in the email from January 29, or is there something else I need
to do?  Thank you!

Cheers,
Jessie

**Comment by redrambles** [comment]
Hi @JessieG57 ! 

You'll need to use the `git push origin take1` command - because the syntax is `git push <where> <which_branch>`. :) Give that a try and it will update this pull request! :)

**Comment by acodeinprogress** [comment]
Hey @JessieG57,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
