### PR TITLE
Added my name and files to 105-practice

### PR DESCRIPTION
**Pull request by AlejandraValdivia**
Added my name and style files

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hi @AlejandraValdivia,

Congratulations on making your first pull request!

It looks like you made some general changes to the index.html file in addition to adding your link. For example, changing `Skillcrush 105 - Advice For Newbies` to `Alejandra's Advice For Newbies`

The only change that should be made in that file is the addition of a link to your advice file.

Once you fix that up, you can add, commit, and push your work up to Github. Your changes will join your pull request here and then we can get this merged in!

xoxo,
Sharon

**Comment by AlejandraValdivia** [comment]
Dear Sharon,
Hope you had a wonderful weekend!!
I've made the changes and commited them, I did everything you suggested but I keep getting rejected, it says that I must first merge advice/alex-v-advice.html....I've tried many times, I'm confused...Why can't  I just merge this to the 105-practice master branch?  Can you please help me? I just want to get this done because I want to learn...Screenshot attached :(
Thank you so much for your time and cooperation you're wonderful  xoxo

Alejandra Valdivia 
    On Monday, January 11, 2021, 06:30:05 a.m. PST, Sharon <notifications@github.com> wrote:  
 
 


Hi @AlejandraValdivia,

Congratulations on making your first pull request!

It looks like you made some general changes to the index.html file in addition to adding your link. For example, changing Skillcrush 105 - Advice For Newbies to Alejandra's Advice For Newbies

The only change that should be made in that file is the addition of a link to your advice file.

Once you fix that up, you can add, commit, and push your work up to Github. Your changes will join your pull request here and then we can get this merged in!

xoxo,
Sharon

**Comment by AlejandraValdivia** [comment]
Hi Sharon,
After many attempts, I'm not sure if is done but this is the last git message I got ( Screenshot attached). Does that mean my branch is merged with origin/upstream Skillcrush 105-practice? or what does it mean? Are my files included or is there any conflict, is there anything else I have to do?  Can you help me please? I love git and I want to dominate it, is challenging and fun at the same time. I can't wait to be an expert like yourself!
Thanks so much!

Alejandra Valdivia  

    On Monday, January 11, 2021, 06:30:05 a.m. PST, Sharon <notifications@github.com> wrote:  
 
 


Hi @AlejandraValdivia,

Congratulations on making your first pull request!

It looks like you made some general changes to the index.html file in addition to adding your link. For example, changing Skillcrush 105 - Advice For Newbies to Alejandra's Advice For Newbies

The only change that should be made in that file is the addition of a link to your advice file.

Once you fix that up, you can add, commit, and push your work up to Github. Your changes will join your pull request here and then we can get this merged in!

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @AlejandraValdivia,

Unfortunately, it doesn't look like your screenshot came through. Can you please email it to questions@skililcrush.com?

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @AlejandraValdivia,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
