### PR TITLE
Added Brett C's advice

### PR DESCRIPTION
**Pull request by bcormie3**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @bcormie3 !

This is a good start!! We got your link in the index.html file - but the advice file that it is pointing to (`advice/brett-c-advice.html`) isn't included in your pull request. Perhaps it still needs to be added and committed, and then pushed?

Once you push up your `advice` branch, your pull request will update automatically and we should be able to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by bcormie3** [comment]
Hi Ann has the issue been corrected?

**Comment by acodeinprogress** [comment]
Hi @bcormie3,

I'm not seeing any changes here. Did you make sure to make your changes on your advice branch and then push your changes up to the advice branch on GitHub?

xoxo,
Sharon

**Comment by bcormie3** [comment]
Hi. I'm not sure what I'm doing wrong. This is the third time I've done this lesson and I don't understand why it's not working. Here is a screenshot of the process.

image

**Comment by bcormie3** [comment]
Hi for the moment just disregard the previous message, I think I may have figured it out.

**Comment by acodeinprogress** [comment]
Hey @bcormie3,

Any updates here?

xoxo,
Sharon

**Comment by redrambles** [comment]
Hey @bcormie3 ,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Pull request closed without merging**
