### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by jessica-lau**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @jessica-lau !

This is nearly ready to go! We just need you to move your  `jessica-l-advice.html` - which is now inside the root of the directory - inside the `advice` directory.

Once you've done that, add and commit that change and push up your advice branch once more. That will automatically update this pull request, and we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by jessica-lau** [comment]
Hi,

I moved my advice page into the advice folder and pushed my advice branch again to update. Please merge in my code. Thanks!

**Comment by jessica-lau** [comment]
Hi,

I moved my advice page into the advice folder and pushed my advice branch
again to update. Please merge in my code. Thanks!

**Comment by redrambles** [comment]
Hey @jessica-lau,

Thanks for making those changes - your code is merged in!

Cheers,
Ann :)

**Pull request merged**
