### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by dbeez**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @dbeez,

Congrats on making your first pull request!

It looks like you deleted some links that other students added to this project. You can see them listed in the index.html file by clicking on the [Files Changed tab](https://github.com/skillcrush/105-practice/pull/1161/files) near the top of this page.

We want to preserve everyone's work so we'll need for you to add those back in before we can merge this into the main codebase. Once you fix that up, you can add, commit, and push and your changes will join your pull request here.

xoxo,
Sharon

**Comment by dbeez** [comment]
Hi Sharon, sorry about that. I see the files that I errantly deleted but
not sure how to fix it. i'm worried i'm going to make things worse. can you
give me a hint on what to do?

Thanks! Dave

**Comment by acodeinprogress** [comment]
Hey @dbeez,

Ok no worries! There are a few ways that you could resolve this.

You could visit the original code base here: [https://github.com/skillcrush/105-practice](https://github.com/skillcrush/105-practice) - open up the index.html file and copy everything inside it. Then you can paste it inside your own index.html file - and add your own link at the bottom of the link.

Because this is Git - there is an easier way! You can replace the version of the index.html file that exists inside your advice branch with the one on the master branch with this command:

git checkout master index.html

And then you can open up the file in your text editor and add your link at the bottom of the list.

Once you have chosen and executed either one of the above options - make sure to save your file - then in the Terminal add with git add -A, commit git commit -m "Your message here" and then push up your advice branch one more time git push origin advice. This will update your pull request and we should then be all set to merge in your code.

Let us know if you have any questions!

xoxo,
Sharon

**Comment by redrambles** [comment]
Hey @dbeez !

Ok - we are getting super close!

So I see you have restored the index.html to its previous glory (yay!!) - but we still need you to add your link to your advice page. Most students add theirs to the top or to the bottom of that long list.

Once you add your link - add and commit your change and then push up your advice branch once more. Then we should be all set to merge in your code!

Home stretch!

Cheers,
Ann :)

**Comment by acodeinprogress** [comment]
Hey @dbeez,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
