### PR TITLE
created new index.html and css files

### PR DESCRIPTION
**Pull request by ERezaie0216**
Not much of edits, sorry. but just practicing for now! Thanks :D

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @ERezaie0216,

Great advice! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by ERezaie0216** [comment]
Hi Sharon!

Thanks for the email. I just went ahead and updated my html code and added,
commited and pushed the code to Github. Please let me know if it's fixed!

Thanks for the help

**Comment by acodeinprogress** [comment]
Hey @ERezaie0216,

Thanks for making that update!

We'll still need to make the changes that I requested in my previous comment. You'll want to open up the index.html file in your text editor and add a link (<a>) in there that links to your advice HTML file.

Once you do that, you can also add, commit, and push like you did the last time. :D 
 
xoxo,
Sharon

**Comment by ERezaie0216** [comment]
Hi Sharon!

Omg I'm so sorry, I completely forgot about that step. I just fixed it
(added my advice link in index.html file). I hope it's fixed now! lol
Thanks for bearing with me.

Great day!
Emal

**Comment by acodeinprogress** [comment]
Hey @ERezaie0216,

Thanks for adding that in!

It looks like in the process, you ended up adding in some additional links in the index.html as well as some additional HTML and CSS files. You can view all of them by looking at the [Files Changed](https://github.com/skillcrush/105-practice/pull/616/files) tab near the top of this page.

xoxo,
Sharon

**Comment by ERezaie0216** [comment]
Hey!
Oh crap, I don't even know how all of that happened tbh. And I don't know
what to do about them now. I can see in my terminal all of those changes
were added that I didnt pay attention to. I really dont know how that
happened. Thank for pointing them out to me. Do I need to do anything to
fix the issue? Or...?

Thanks.
Emal

**Comment by acodeinprogress** [comment]
Hey @ERezaie0216!

If you want to try fixing this up, you're welcome to. Or we can close this pull request and you can give this assignment another try. Just let us know what you'd like to do. :)

xoxo,
Sharon

**Comment by redrambles** [comment]
Hey @ERezaie0216,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Comment by ERezaie0216** [comment]
Hi @redrambles! 

Yes please. So sorry for not responding as I had been working on phase 1 milestone and was forgetting about the things I har learn on GitHub. I’ll jump back in sometime soon and play around to get used to using Github! 
Thanks :))

**Pull request closed without merging**
