### PR TITLE
Feedback

### PR DESCRIPTION
**Pull request by achiara311**
I don't know what I'm looking at, but I hope I got some of it right.

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @achiara311,

I'm seeing a lot of extra files in your pull request. You can see all of the files listed by clicking the [Files Changed](https://github.com/skillcrush/105-practice/pull/310/files) tab near the top of this page.

We should only have 3 files show up here:

1. Your personal advice HTML file.
2. Your personal stylesheet.
3. The index.html file.

You'll need to delete all of the extra files. Once you do that, you'll need to run a slightly different git command (`git add -A`), commit, and push. Then we can get your code merged in.

xoxo,
Sharon

**Comment by redrambles** [comment]
We're getting closer! If you look at the Changed Files tab, you can see that you have two advice files, one is called 'advice/ajc-advice.html' and the other is 'advice/anthony-advice.html' - so you'll need to pick only one and delete the other.

Once you have done that, you will need to make sure that you link to your 'css/ajc-advice.css' stylesheet from the advice file that you have decided to keep. Right now you are only linking to '<link rel="stylesheet" type="text/css" href="**../css/style.css**">'

Lastly - if you look at the[ Files Changed](https://github.com/skillcrush/105-practice/pull/310/files) page, and you scroll down to the index.html file, you will notice that there have been a LOT of deletions on that page. The only change we want there is that you add a link to your advice file - so one single line. I suggest that you copy the index.html file from the main codebase and replace the contents of your index.html file with its contents. Then you can go ahead and add your link.

Once all this is done, you'll want to add (git add -A) and commit (git commit -m "your message here") and push up your branch once more. Then we should be all set to merge in your code! :)

Let us know if you have any questions.

Cheers,
Ann

**Comment by achiara311** [comment]
Got lost in a whirlwind of stuff which made me make a new branch, make the corrections you gave me, made the commits and pushes to that branch, and then I merged that branch with my master branch.

**Comment by acodeinprogress** [comment]
Hey @achiara311,

If you take a look at the [Files Changed](https://github.com/skillcrush/105-practice/pull/310/files) tab near the top of this page, you'll see that we still have some links that were deleted (you can see them in red). Those will still need to be added in before we can get this merged in.

xoxo,
Sharon

**Comment by achiara311** [comment]
For some reason, added a couple of css files when adding those missing red lines back into the index.html file. I don't know what I did.

**Comment by acodeinprogress** [comment]
Hey @achiara311,

Great job! I'm not seeing any extra CSS files so this is good to go and your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Comment by achiara311** [comment]
Oh ok! Cool, thanks!

**Pull request merged**
