### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by goca-d**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @goca-d,

Congrats on making your first pull request!

It looks like you deleted some links that other students added to this project. You can see them listed in the index.html file by clicking on the Files Changed tab near the top of this page.

We want to preserve everyone's work so we'll need for you to add those back in before we can merge this into the main codebase. Once you fix that up, you can add, commit, and push and your changes will join your pull request here.

xoxo,
Sharon

**Comment by goca-d** [comment]
I'm sorry this happened. Would I have the files I accidentally deleted in my local index.html file?

**Comment by redrambles** [comment]
Hey there @goca-d !

No worries at all - this happens very frequently as a result of resolving a merge conflict and is alllll part of the practice that we want to get here! :)

To find out which links need to be added back, you could consult your master branch's index.html page if you like - or the one directly on Skillcrush's GitHub repo - or like Sharon mentioned above, in the Files Changed view here: https://github.com/skillcrush/105-practice/pull/1577/files

One easy way to do this would be to first update your upstream remote reference with `git fetch upstream` and then checkout the version of the index.html file that exists on the upstream branch `git checkout upstream/master index.html`. This will overwrite your local index.html file with the most recent version of the file on Skillcrush's 105-practice repo. Then you can open it up in your text editor of choice and just pop in your link either at the top or the bottom of that long list (or somewhere in the middle if you prefer) - then save the file, add and commit as per usual and then push up your advice branch once more.

This will update your pull request and we should be all set to merge in your code!

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by goca-d** [comment]
Thanks so much for describing how to add the new changes. Here's hoping I did it right😳

**Comment by acodeinprogress** [comment]
Hey @goca-d,

I'm not seeing those changes. Did you make sure to make your changes on your advice branch and then push to the advice branch on GitHub?

xoxo,
Sharon

**Comment by goca-d** [comment]
Hmm, that's strange. I ran git log on my terminal and it shows the recent
changes that I did when I added the remainder of the code, but I didn't
request a new pull. Do you think I should close this one and request a new
one?

Thanks for all your help

**Comment by redrambles** [comment]
Hey @goca-d !

No need to create a new pull request, we can work with this one. If you can see the changes using `git log` then probably all that still needs to be done is to push those changes here. You'll want to do that with `git push origin advice`. 

Want to give that a try? We should then get your latest changes on our end, and if everything checks out - we can merge in your pull request! :) 

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by goca-d** [comment]
Hi Ann

Can you check if my pull request is done as it should be? If not I can
always have it removed and then redo the entire exercise.
Thanks,
Gordana

**Comment by redrambles** [comment]
Hey there! 

We still don't have the corrections that we need made to the index.html file on our end. If you are able to join any of our dev Q&A sessions (under 'Live Q&A') in your dashboard - we'd be happy to walk you through this last little bit. 

If you would prefer to start over, you can do that as well, of course. Whichever you prefer! :) 

Cheers,
Ann :)

**Comment by acodeinprogress** [comment]
Hey @goca-d,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
