### PR TITLE
Experiments

### PR DESCRIPTION
**Pull request by alexsisparish**
I'm very confused and not sure if I got any of this right but I hope so!

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @alexsisparish,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by alexsisparish** [comment]
So I got this conflicting files error, which I think has to do with what I was just about to start on in the class. Is it because my file isn't updated with the file on GitHub and there's been changes but not on my end? That's how I read it? So I just went ahead and added the code that was missing from mine and tried to resubmit my pull request but I'm just getting more confused I guess because there's already a pull request open?

**Comment by alexsisparish** [comment]
and I see now because I skipped ahead with the pull request. I'll be right back after I get through this lesson!

**Comment by redrambles** [comment]
Hey @alexsisparish,

You did a great job and your code is all merged in! Yay!

Cheers,
Ann :)

**Pull request merged**
