### PR TITLE
Added Jessie advice

### PR DESCRIPTION
**Pull request by Jessie-n-Z**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hi @Jessie-n-Z,

Congratulations on making your first pull request!

I see that you added a folder called jessie-z-advice.html and two files in that folder:
- jessie-z-advice.html
- your-name-advice.html

You should just have one advice file (`jessie-z-advice.html`) and it should be in the `advice` folder.

We would also like for you to include a link to your advice page in the index.html file. 

If you could make those changes, all you have to do is run `git add -A`, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by Jessie-n-Z** [comment]
So this is what I see. What do I find the folders and files?
[image: Screen Shot 2021-01-11 at 6.42.24 PM.png]

**Comment by redrambles** [comment]
Hey @Jessie-n-Z - that screenshot didn't come through on GitHub - can  you send it again at 'questions@skillcrush.com' ? We'll take it from there!

Cheers,
Ann :)

**Comment by redrambles** [comment]
Hey @Jessie-n-Z ,

You did a great job and your code is all merged in! Yay!

Cheers,
Ann :)

**Comment by Jessie-n-Z** [comment]
YES. Thank you for all of your help!

**Pull request merged**
