### PR TITLE
Committing untracked advice files

### PR DESCRIPTION
**Pull request by marcijo**
I have changed some key details on the web page.

### CODE REVIEW

**Comment by redrambles** [comment]
Hey Marci! 

Something unusual appears to have occurred with this pull request. Can you tell me which file you were working on?

**Comment by marcijo** [comment]
skillcrush/ 105-practice

**Comment by redrambles** [comment]
Hey @marcijo !

I mean which file in the advice and css directories? Something like 'advice/marci-jo-advice.html' ? And similar in the CSS directory?

Thank you!

Cheers,
Ann :)

**Comment by acodeinprogress** [comment]
Hey @marcijo,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Comment by marcijo** [comment]
I got a new job! Finally after 6 months of intensive searching. So I’m in
training right now for three weeks. I’m doing my React class but since I
went thru Github before I was not concerned about the pull request so
thanks for closing it.

**Pull request closed without merging**
