### PR TITLE
update

### PR DESCRIPTION
**Pull request by perfect-designz**
redid pullrequest. Please email me back if it is correct or needs work again. Thanks

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @perfect-designz,

I saw that you created a new pull request so I'm going to go ahead and close this one.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @perfect-designz,

We are on the right track here!

There are just a couple more things that we'll need:

1. You didn't add an advice page. 
2. We would like for you to include a link to your advice page in the index.html file. 

If you could make those changes, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by perfect-designz** [comment]
I completed everything. Hope everything is all in this time. Thanks

**Comment by redrambles** [comment]
Hey @username,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Pull request closed without merging**
