### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by nath248**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @nath248,

Congrats on making your first pull request!

It looks like you deleted some links that other students added to this project. You can see them listed in the index.html file by clicking on the [Files Changed tab](https://github.com/skillcrush/105-practice/pull/1764/files) near the top of this page.

We want to preserve everyone's work so we'll need for you to add those back in before we can merge this into the main codebase.

I also noticed that you didn't add an advice page or any css. If you could add those things, that would be great! Once you do that, you can add, commit, and push your work and it will join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by nath248** [comment]
Hi Sharon,

Thank you for your reply,

I went ahead and made the changes but I see my updates at the bottom of the page along with all the other student files, is this ok?
Also, I noticed that for the index.html it is showing a few links being deleted but I didn't physically delete them in the text editor. Would this occur when new projects are added after we've created our files?

Kindly,
Nathaly

**Comment by nath248** [comment]
Good morning Sharon,

Just wanted to follow up on this pull request. I went back in and made the changes advised. I did see an option to resolve conflict pop up but the only discrepancy that I see from the master to the advice branch is that my link was added. (See screenshot below). Kindly advise if there are any further changes that I may be missing.

[cid:image003.png@01D6EB30.87D02110]

Thank you!

Kind Regards,
Nathaly H.

**Comment by acodeinprogress** [comment]
Hey @nath248,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Comment by redrambles** [comment]
Hey @nath248 !

Ok! So I think that we have ourselves tangled up a bit here, so I'm going to suggest that you follow the next couple steps which will involve resetting your advice branch to a copy of what the master branch is on upstream and then adding in your code files and finally adding in your link to the main index.html file. It's the fastest/easiest way to get to where we want to go.

1) Make sure that you are inside your advice branch (`git status` will tell you which branch you are on - and so will `git branch`).
2) Using the Finder / File Explorer, find your `advice/nathaly-h-advice.html` file and temporarily tuck it away on your Desktop.
3) Do the same for your `css/nathalyh.css` file.
4) Fetch from upstream `git fetch upstream`
5) Reset your advice branch to be an exact copy of the master branch on the upstream remote. This means that it will be exactly match the main codebase as it is at this point in time. `git reset --hard upstream/master`
6) Move your html file from the desktop and place it inside the 'advice' directory
7) Move your css file from the desktop and place it inside the 'css' directory.
8) Open up the index.html file using your text editor of choice and add a link to your advice file.
9) Run `git status`. You should see three changes - your html file, your css file and the index.html file. Add everything with `git add -A`.
10) Commit as per usual `git commit -m "Your message here"`
11) Now we'll need to force push: `git push -f origin/advice` - because we changed history with the reset command. This is ok to do in this instance because you are working alone on your own branch - no one else will be affected by this change in history.

Once that force push goes through, this pull request will be updated. At that time we should see on our end that the only changes included in your PR involve your own html and css files - and a modification to the index.html file (your link) - which is exactly what we want. 

Then we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by nath248** [comment]
Hi Ann,

Thank you so much for this detailed explanation/steps. I was able to complete this and it seems there are no more conflicts with the branch. Kindly advise if this pull request is accepted.

Thanks again!

Kind Regards,
Nathaly H.

**Comment by redrambles** [comment]
Hey @nath248 

Thanks so much for making those changes - you did a fantastic job and your code is merged in!!! :)

Cheers,
Ann :)

**Comment by nath248** [comment]
Hi Ann,

Thank you for all your help!

Kind Regards,
Nathaly H.

**Pull request merged**
