### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by Nick01477**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @Nick01477 !

This is great! The only thing we need before we can proceed is for you to move your html file into the `advice` directory. Right now it is inside the root of the project folder.

Once you have done this, add the change with `git add -A` - then commit and push up your advice branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code! :)

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by Nick01477** [comment]
Hi Ann,

Thank you! I have been trying to figure out how to move the html file into
the advice directory, but I am a bit lost. Do I use git to move the HTML
into the advice directory?

Cheers,

Nick

**Comment by redrambles** [comment]
Hey @Nick01477,

I would just open up your Finder / File Explorer and drag it from the root of the project directory into the advice directory. If you wanted to use the Terminal / Git Bash to do this - you could by using:

` mv nick-m-advice.html advice/nick-m-advice.html`

Once this is done (whichever method you choose) - you will then need to add and commit that change (`git add -A`) (`git commit -m "Your message here"`) and then push up your advice branch once more, which will update this pull request.

Then we should be all set to merge in your code!

Cheers,
Ann :)

**Comment by Nick01477** [comment]
Hi Ann,

Thank you for helping out :). I think I have done the correct thing and
have pushed the changes.

Please let me know if it worked.

Cheers,

Nick

**Comment by redrambles** [comment]
Hey @Nick01477,

Thanks for making those changes - you did a great job and your code is all merged in! Yay!

Cheers,
Ann :)

**Pull request merged**
