### PR TITLE
Sean Barile's Advice

### PR DESCRIPTION
**Pull request by SeanBarile**
Some advice I'd like to give.

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @SeanBarile,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by SeanBarile** [comment]
Hi,

Sorry to ask but could you elaborate on the adding a link to the advice
html.  It needs a link “within” the .html file?  Sorry if this sounds like
an obvious question.

**Comment by SeanBarile** [comment]
Hello Sharon,

So I think I figured out what you meant.  Would you be able to verify that
I've done what you asked for correctly?  (I'm hoping I did it right lol).
Let me know if I need to do something else or make some sort of adjustment.

Thanks,
Sean Barile

**Comment by acodeinprogress** [comment]
Hey @SeanBarile,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
