### PR TITLE
Add Chelsie's Advice

### PR DESCRIPTION
**Pull request by chelsiedaugherty**
Here is some advice I'd like to share.

Also, there is a message that says "Can't automatically merge. Don't worry, you can still create the pull request." Can you explain what this means?

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @chelsiedaugherty,

It looks like we have a merge conflict marker `=======` in our index.html. There are also a lot of lines that were added in. This leads me to believe that they are duplicates that showed up in both your branch and the master branch when you tried to resolve the merge conflict. You can see these things by checking out the [Files Changed](https://github.com/skillcrush/105-practice/pull/202/files) tab near the top of this page.

If you could remove all the extra code, that would be fantastic! Once you do, all you have to do is add, commit, and push and your changes will join your pull request here.

xoxo,
Sharon

**Comment by chelsiedaugherty** [comment]
Hello, 

I believe I fixed the merge conflict in my last commit. It no longer has the message "Can't automatically merge. Don't worry, you can still create the pull request." It now says "This branch has no conflicts with the base branch." Is there something else I still need to do?

**Comment by acodeinprogress** [comment]
Hey @chelsiedaugherty,

Unfortunately the merge conflict marker and the extra links are still showing. Go ahead and check out the index.html file by looking at the [Files Changed](https://github.com/skillcrush/105-practice/pull/202/files) tab near the top of this page to see what I mean. The changes are highlighted in green.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @chelsiedaugherty,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
