### PR TITLE
joys-advice

### PR DESCRIPTION
**Pull request by joyago**
Validated HTML and CSS, no errors!  Would love to know what you think of the styling.

### CODE REVIEW

**Comment by redrambles** [comment]
Hello @joyago !

This is close! If you look at your [change set here](https://github.com/skillcrush/105-practice/pull/160/files) - you'll see that there are a few files that need to be removed, as they have a tilde (~) at the end of the extension - `advice/joyago-advice.html~` and `css/joyago-advice.css~`. Once you have removed both of those files, you will need to add a link in the main index.html file that points to your advice file, so that others can find your words of wisdom once your code is merged in. :) If you aren't sure how to do this, open up the index.html file and look at the other student links for reference. 

Once you are done with that, you will need to add `git add -A`, commit `git commit -m "your message here"` and then push up your branch once more `git push origin joys-advice`, which will automatically update your pull request. Then we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann

**Comment by joyago** [comment]
Ok, all done and I was able to figure out why I was getting a tilde document and will make sure that doesn't happen again.  Thanks!

**Comment by acodeinprogress** [comment]
Hey @joyago,

Awesome! Thanks for making that change!

Now there is one last step. We would like for you to include a link in the index.html file that points to your advice page. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by joyago** [comment]
Ok, I think I see where I went wrong.  I tried to add the link via github instead of on git and then added, commiting and pushing the file.  Please tell me this worked this time :)   I was stuggeling a bit with Git and GitHub but with all this practice, I think/hope I've gotten the hang of it!  Thanks again

**Comment by acodeinprogress** [comment]
Hey @joyago,

Aha! I think I see the problem. You created a new branch called `patch-1` and made your changes there.

In order for your changes to show on this pull request, you'll need to make them on your joys-advice branch on your computer and then push to your joys-advice branch on GitHub.

xoxo,
Sharon

**Comment by joyago** [comment]
I'm not sure how or where I created a branch called patch-1, it's not on my computer and I didn't add that.  I'm thinking when I tried to update the index.html via GitHub instead of doing it on Git?
I did type git status locally however and see that I never added or committed the change I did make, so lets try this one more time, hopefully for the last time :)   I just pushed  the doc

Thanks, Joy

**Comment by acodeinprogress** [comment]
Hey @joyago,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
