### PR TITLE
Add laronda's advice page

### PR DESCRIPTION
**Pull request by larondasue**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @larondasue !

This is great! The only thing is that I'm noticing that you are pointing to a stylesheet `css/laronda-u.css` from your advice file - but this css file isn't part of your pull request. Does it still need to be added, committed and then pushed up?

Once you add and commit that stylesheet - push up your `advice` branch once more, which will automatically update this pull request. Then we should be all set to merge in your code!

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by larondasue** [comment]
Thanks for the email but I'm confused. Is my css file on my computer only
and not on any of the git branches? I opened the advice branch to add &
commit but got an error message:

larondaulrich@larondas-MacBook-Air:*~/Documents/105-practice/css*$ git add
laronda-u.css

larondaulrich@larondas-MacBook-Air:*~/Documents/105-practice/css*$ git
commit laronda-u.css "Add css page for laronda-u-advice"

error: pathspec 'Add css page for laronda-u-advice' did not match any
file(s) known to git

**Comment by acodeinprogress** [comment]
Hi @larondasue,

When using commit, you don't want to specify the file that you want to commit since you've already done that with the add command.

Instead, the commit command should look like this:
`git commit -m "Add css page for laronda-u-advice"`

Once you do that, you should be able to push to GitHub and your work should join your pull request here.

xoxo,
Sharon

**Comment by larondasue** [comment]
Thanks! I fixed that but I keep getting stuck with error messages &
sometimes I can't figure out how to even get out of the screen on the
terminal, not even using Q was working. I would have to close the terminal
and re-open it & go back to start over the steps. Now I just keep getting
stuck with different error messages.

Should I start all over again? I am considering ignoring the advice page I
wrote out and throwing my computer out the window. Or deleting all the
files & branches and starting over.

I am still stuck at the Finishing the Workflow step of the Github Lesson 10.

larondaulrich@larondas-MacBook-Air:*~*$ cd Documents/105-practice

larondaulrich@larondas-MacBook-Air:*~/Documents/105-practice*$ ls

README.md   *advice*/     *css*/        *index.html**

larondaulrich@larondas-MacBook-Air:*~/Documents/105-practice*$ git remote
add upstream git@github.com:skillcrush/105-practice.git

fatal: remote upstream already exists.

larondaulrich@larondas-MacBook-Air:*~/Documents/105-practice*$ git remote -v

origin git@github.com:larondasue/105-practice.git (fetch)

origin git@github.com:larondasue/105-practice.git (push)

upstream git@github.com:skillcrush/105-practice.git (fetch)

upstream git@github.com:skillcrush/105-practice.git (push)

larondaulrich@larondas-MacBook-Air:*~/Documents/105-practice*$ git fetch
upstream

Enter passphrase for key '/Users/larondaulrich/.ssh/id_rsa':

larondaulrich@larondas-MacBook-Air:*~/Documents/105-practice*$ git branch -a

  advice

* master

  remotes/origin/HEAD -> origin/master

  remotes/origin/Resolve

  remotes/origin/advice

  remotes/origin/master

  remotes/upstream/Resolve

  remotes/upstream/master

larondaulrich@larondas-MacBook-Air:*~/Documents/105-practice*$ git merge
upstream/master

fatal: You have not concluded your merge (MERGE_HEAD exists).

Please, commit your changes before you merge.

larondaulrich@larondas-MacBook-Air:*~/Documents/105-practice*$


Frustratedly,
Laronda

**Comment by redrambles** [comment]
Hey @larondasue,

You did a great job and your code is all merged in! Yay!

Cheers,
Ann :)

**Comment by larondasue** [comment]
Thanks so much, Ann!!! I felt like I had to go back to it and give it some
more effort after you looked so hurt when I told you I was not enjoying the
github class, like I insulted a friend of yours.

Cheers to you!

**Pull request merged**
