### PR TITLE
Anita's files

### PR DESCRIPTION
**Pull request by anitafchin**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @anitafchin !

This is a good start! We just need you to make a few changes before we can merge this in.

1) Please move your css file into the 'css' directory- and your advice file into the 'advice' directory.

2) A few lines were accidentally deleted from the main index.html file - so let's bring it back to its most recent version and then add your link to your advice file to it (while leaving the rest of the code intact). To do that, you will want to:
a) Fetch from upstream `git fetch upstream`
b) Checkout your master branch `git checkout master`
c) Merge in upstream: `git merge upstream/master`
d) Move back into your advice branch `git checkout advice`
e) Now let's do something a little different. Instead of merging in the index.html file from the freshly updated master branch - let's _replace_ the index.html file inside the advice branch with the version on the master branch: `git checkout master index.html`

This will 'undo' all accidental deletions in that file. Now you can go ahead and add your link once more somewhere in that long list.

Once that is done - let's add with `git add -A` - then commit as per usual `git commit -m "Your message here"` and then finally push up your advice branch, which will automatically update your pull request: `git push origin advice`

Then we should be all set to merge in your code. Let us know if you have any questions!

Cheers,
Ann :)

**Comment by anitafchin** [comment]
Thanks Ann

**Comment by acodeinprogress** [comment]
Hey @anitafchin,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Comment by anitafchin** [comment]
HI Sharon,

I got this one sorted out!

Anita

**Pull request closed without merging**
