### PR TITLE
James Hickey Add

### PR DESCRIPTION
**Pull request by jghickeyiii**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @jghickeyiii,

It looks like this is the same pull request except on a different branch. Would you like us to close this one or your previous one?

xoxo,
Sharon

**Comment by jghickeyiii** [comment]
Previous one

James G. Hickey

**Comment by acodeinprogress** [comment]
Hey @jghickeyiii,

I went ahead and closed your other pull request. We'll need to add in one more thing before we can merge this in:
We would like for you to include a link to your advice page in the index.html file. 

If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @jghickeyiii,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
