### PR TITLE
added css and html

### PR DESCRIPTION
**Pull request by cyrellj**
just sharing my two cents

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @cyrellj,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by cyrellj** [comment]
@acodeinprogress I pushed the changes by adding a link to my advice page on the index.html! However I am seeing a conflict on the branch if I am not mistaken?

**Comment by acodeinprogress** [comment]
Hey @cyrellj,

That is correct! You can try fixing that up if you'd like or we can take care of it for you. Just let us know what you'd like to do!

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @cyrellj ,

I went ahead and fixed this up so your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
