### PR TITLE
Add Jesse's Advice

### PR DESCRIPTION
**Pull request by Jperez6**
Some advice i would like using a landing page type style.

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @Jperez6,

This looks great!

I see that you added an image to the project. Unfortunately we cannot accept images in this repository - as it would quickly become too large. You can definitely link to existing online images, though! :)

Please remove your `img` directory with the images inside, and update your image links in your advice page. 

Then you'll need to run a slightly different git command (git add -A), commit, and push, your changes will join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by Jperez6** [comment]
What is the difference between git add .
And
git add -A

**Comment by acodeinprogress** [comment]
Hey @Jperez6 !

`git add .` adds all of the files that you changed but it doesn't remove deleted files from Git. `git add -A` "adds" ALL the changes that you made, including deleting any files that you deleted.

I hope this helps!

xoxo,
Sharon

**Comment by Jperez6** [comment]
What would be a good scenario for using each and would it be better to just
do:
git add (filename)
git commit -m "message"

For each file?

**Comment by acodeinprogress** [comment]
Hey @Jperez6!

I prefer to use `git add -A` to catch all of my changes, including any deleted files/folders but you can reserve this command for just those uses and use `git add .` as your normal add command.

Normally there's no need to do `git add [filename]` but you could use it if you edited multiple files and only want to commit certain ones in a certain commit.

I hope this helps!

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @Jperez6,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
