### PR TITLE
105 practice branch

### PR DESCRIPTION
**Pull request by Cynamingrl**
Resubmitting my Advice page.

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @Cynamingrl,

This is nearly perfect!

The last step is removing our merge conflict markers from the index.html file. If you're not sure where they are, you can see them by checking the [Files Changed tab](https://github.com/skillcrush/105-practice/pull/606/files) near the top of this page.

xoxo,
Sharon

**Comment by Cynamingrl** [comment]
Hi Sharon!

 

Question…Once I’ve removed the conflict markers, do I “merge the branches on the command line or  <https://help.github.com/en/articles/pushing-commits-to-a-remote-repository/> push your changes to your remote repository on GitHub and  <https://help.github.com/en/articles/merging-a-pull-request/> merge your changes in a pull request.” I couldn’t remember what to do so I looked it up on GitHub.

 

Thanks,

Kim

**Comment by acodeinprogress** [comment]
Hey @Cynamingrl,

Once you make those adjustments to your code, you'll need add, commit, and push your code up to GitHub. They'll automatically join your pull request here and then we can get it merged in.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @Cynamingrl,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
