### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by jyatar**

### CODE REVIEW

**Comment by jyatar** [comment]
test

**Comment by jyatar** [comment]
test

**Comment by redrambles** [comment]
Hey @jyatar !

Thanks for your pull request! There are a few things that we need to address before we can merge this in.

1) Your advice file (`joy-y-advice.html`) is inside a directory of the same name (`joy-y-advice.html`) - but we need it to be inside the `advice` directory instead. Make sure that you are on your advice branch and then please move your `joy-y-advice.html` _file_ inside the advice directory and delete the (now empty) `joy-y-advice.html` _directory_.

2) Once we're good there, let's work on the index.html file. Right now there are merge conflicts still present in the file, and many new lines of code have been added as part of the process. Let's address that by restoring the index.html file to the version that exists on the upstream (Skillcrush) remote:

`git checkout upstream/master index.html`

This will replace your local version of the index.html file that exists in your advice branch with a copy of the version of the file as it is on Skillcrush's repository - which means it will be up to date with the upstream repo. Next, open the file in your text editor of choice and add a link to your advice page somewhere in that list of links.

Once this is done - add your changes with `git add -A` - then commit as per usual and finally push up your advice branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code. Let us know if you have any questions!

Cheers,
Ann :)

**Comment by redrambles** [comment]
Hey @jyatar ,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Pull request closed without merging**
