### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by AimeeT8**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @AimeeT8,

Congratulations on making your first pull request!

It looks like some conflict markers were left in the index.html file by accident. You can see them if you look at the [Files Changed ](https://github.com/skillcrush/105-practice/pull/1664/files) tab near the top of this page.

Once those are removed, you'll need to add, commit, and push again and then we can merge in your code.

xoxo,
Sharon

**Comment by AimeeT8** [comment]
Thanks. I deleted the conflict markers, added, committed and pushed the changes.

**Comment by acodeinprogress** [comment]
Hey @AimeeT8,

Thanks for making that change! If you take another look at the  [Files Changed](https://github.com/skillcrush/105-practice/pull/1664/files) tab near the top of the page, you'll see that a lot of extra lines were added to the index.html file and there is still a merge conflict added at the end of all of those lines. You'll want to delete all of the green lines (except for the link that you added in for your advice page) and then follow the same steps to add, commit, and push.

xoxo,
Sharon

**Comment by AimeeT8** [comment]
Okay thanks, I think I have fixed everything.

**Comment by redrambles** [comment]
Hey @AimeeT8 !

Thanks for making those changes - we're all good. Your code is merged in! :) 

Cheers,
Ann :)

**Pull request merged**
