### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by Brenda-CW**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @Brenda-CW !

This is nearly good to do - we just need you to move your `brenda-w-advice.html` file from inside the root of the project directory - where it is now - to inside the `advice` directory. Once you move the file, add that change with `git add -A` -then commit as per usual and push up your advice branch once more.

Then we should be all set to merge in your code. Let us know if you have any questions!

Cheers,
Ann :)

**Comment by Brenda-CW** [comment]
Okay - I've done that.   ...just to be clear, I moved the folder in my
finder.  I looked at all the Git documentation and didn't see a way to use
the terminal to move the file.  Is that right?

**Comment by redrambles** [comment]
Hey @Brenda-CW !

Yes it's totally fine if you moved your file into the correct folder (advice) using the Finder. Now if you run `git status`, you should see that Git has picked up that change. You will need to add and commit it and then push up your advice branch once more so that we can get the change on our end.

Then we should be all set. Let us know if you have any questions!

Cheers,
Ann :)

**Comment by Brenda-CW** [comment]
I already added and committed on Friday before I emailed you.  When I ran
git status today it says there is nothing to commit, so today I tried to
push and got the error message below.  I had gotten this same error
before.  Code sample below starts from Friday based on your instructions.


BRENDAs-MacBook-Air:105-practice BzFiles$ git add -A

BRENDAs-MacBook-Air:105-practice BzFiles$ git commit -m "Moved Advice.html
into advice folder"

[advice 7ad2850d] Moved Advice.html into advice folder

 2 files changed, 43 insertions(+)

 rename brenda-w-advice.html => advice/brenda-w-advice.html (100%)

 create mode 100644 css/brenda-w.css

BRENDAs-MacBook-Air:105-practice BzFiles$ git status

On branch advice

nothing to commit, working tree clean

BRENDAs-MacBook-Air:105-practice BzFiles$ git push origin advice

To https://github.com/Brenda-CW/105-practice.git

 ! [rejected]          advice -> advice (non-fast-forward)

error: failed to push some refs to '
https://github.com/Brenda-CW/105-practice.git'

hint: Updates were rejected because the tip of your current branch is behind

hint: its remote counterpart. Integrate the remote changes (e.g.

hint: 'git pull ...') before pushing again.

hint: See the 'Note about fast-forwards' in 'git push --help' for details.

BRENDAs-MacBook-Air:105-practice BzFiles$

**Comment by redrambles** [comment]
Hey @Brenda-CW !

I merged in your second pull request (it was perfect!) - so I'm going to close this one. :)

Happy coding!

**Pull request closed without merging**
