### PR TITLE
Add AmberC's Advice

### PR DESCRIPTION
**Pull request by WannaLiveTilliDie**
Sharing my advice page.

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @WannaLiveTilliDie,

This looks great so far!

There's just one small change that we'll need to make before this can be merged in. It looks like you deleted a couple other lines of code (that were made by your classmates). We want to preserve everyone's code so we'll need those lines added back in.

You can see them highlighted in pink (with a `-` sign next to the line) if you click on the [Files Changed](https://github.com/skillcrush/105-practice/pull/114/files) tab and scroll down to the index.html file.

Once you add those back in, you can add, commit, and push your code and your changes will join your pull request here.

xoxo,
Sharon

**Comment by WannaLiveTilliDie** [comment]
Hi Sharon,

I must have inadvertently deleted it when I ran into a conflict and tried
to resolve it! Sorry about that. When you have a chance, would you mind
letting me know if that worked? Thank you!

Best,
Amber

**Comment by redrambles** [comment]
Hey @WannaLiveTilliDie,

Thanks for making that change, your code is all merged in! :)

Cheers,
Ann

**Comment by WannaLiveTilliDie** [comment]
Thank you, Ann!!

Best,
Amber

**Pull request merged**
