### PR TITLE
added advice page

### PR DESCRIPTION
**Pull request by airialtokyo**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @airialtokyo !

This is good! The only thing we need is for you to place your `robert-d-advice.html` file into the `advice` directory. Once you've made that change, go ahead and add with `git add -A` - then commit as per usual and push up your advice branch once more, which will automatically update this pull request. 

Then we'll be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by airialtokyo** [comment]
I’m sorry I don’t understand what you mean what exactly should I be doing? I thought the advice page was included? Can you please tell me what I should do step by step sorry

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by acodeinprogress** [comment]
Hi @airialtokyo,

Currently your advice file is in the root folder of this project. Instead, it should be located in the advice folder that we've provided.

You can simply use your Finder or File Explorer to move the file. Once you do that, you'll want to run `git add -A`, commit, and then push.

I hope this helps!

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @airialtokyo,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
