### PR TITLE
Updated master list with link to new advice from LaTanya. Added latan…

### PR DESCRIPTION
**Pull request by LLsDAFC**
…ya_l advice file.

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @LLsDAFC,

I see that you linked your HTML file to a CSS file but I don't see that that CSS file exists.

Would you mind creating that file or removing the link?

xoxo,
Sharon

**Comment by LLsDAFC** [comment]
Hi Sharon!! I couldn't get my stylesheet to link, so I just did internal
styles since it was a 1-pager. I will remove that link from the HTML file
and upload the corrected one.

Best,
Tanya

**Comment by LLsDAFC** [comment]
Sharon - I made the update, but I'm not sure it pushed to the right place.
Do I need to start over (starting from re-clone 105-practice) or is there
another way I should update it?

Best,
Tanya

**Comment by redrambles** [comment]
Hey @LLsDAFC !

Did you mean to add your stylesheet and remove the styles that you added inside your advice file? Or did you want to keep those styles and just remove the link to your external stylesheet? 

Cheers,
Ann :)

**Comment by LLsDAFC** [comment]
Keep the styles and remove the link.

**Comment by redrambles** [comment]
Hey @LLsDAFC !

Ok! So all you'll need to do then is remove `<link rel="stylesheet" type="css/text" link=".../css/latanya-l.css">` from inside the `<head>` section of your `advice/latanya_l_advice.html` file - save, add and commit as per usual and then push up your branch again with `git push origin advice`. Then we should be all set to merge in your code!

Home stretch!!! Let us know if you have any questions!

Cheers,
Ann :)

**Comment by redrambles** [comment]
Hey @LLsDAFC,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Comment by LLsDAFC** [comment]
Thanks Ann!

**Pull request closed without merging**
