### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by betweenbrackets**
Updates to include ruby-m-advice.html and  ruby-m-style.css

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @betweenbrackets !

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that long list. :)

Once you add your link, add and commit your changes and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by betweenbrackets** [comment]
Hey Ann!

I think I did it! Added the link to my advice page on the index page.
Added. Committed. Merged. Resolved conflict. Merged. Pushed. Pulled! (Gah!)

I also tweaked my advice page a wee bit in the meantime.

Cheers,
Ruby

**Comment by redrambles** [comment]
Hey @betweenbrackets !

We got your link, thanks! The only thing is that there are still some conflict markers that remain in the file - see here: https://github.com/skillcrush/105-practice/pull/1028/files#diff-eacf331f0ffc35d4b482f1d15a887d3bR563

Once you remove the conflict markers, add and commit your changes and push up your advice file once more. Then we should be all set!

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by betweenbrackets** [comment]
Hey @redrambles !

I made the changes but I don't think I am seeing them. (??)

On my local, I removed the markers. I added, committed, and pushed to the remote repo. On the remote repo, I made a pull request. 

My latest commit was minutes ago. I'm not seeing that from my GitHub profile. 

Am I missing a step?

Thanks!
Ruby =)

**Comment by acodeinprogress** [comment]
Hey @betweenbrackets,

Are you making sure to make your changes on your advice branch and then push to your advice branch on your computer? Each pull request is for a specific branch so if you pushed to a different branch on GitHub, your changes won't show up here.

Also, for future reference, you shouldn't need to make a pull request on your own repo. :D

xoxo,
Sharon

**Comment by betweenbrackets** [comment]
Hey Sharon!

Gosh. I have been so trying to get my local updated, merged, and pushed!
Been at it on and off for a few days. I feel victory when I get all the
upstream changes integrated, and not so much when I again get the message
that my current branch is behind its remote counterpart. I've attached
screen shots of my terminal output. Me and Google are going in circles at
this point. Help?

Thank you!

**Comment by redrambles** [comment]
Hey @betweenbrackets !

We're not getting the screenshots here - do you mind sending them in to questions@skillcrush.com? We can continue the conversation there!

**Comment by betweenbrackets** [comment]
Done. =)

**Comment by redrambles** [comment]
YAYYYYYYYYYYYY!!!!

**Pull request merged**
