### PR TITLE
adding advice branch css and html

### PR DESCRIPTION
**Pull request by RashelF**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @RashelF !

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that long list. :)

Once you add your link, add and commit your changes and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by RashelF** [comment]
Which long list? I have added my rashel-f-advice to the list of all the other students html. Do I add it to Bash? Sorry, I’m confused.

**Comment by acodeinprogress** [comment]
Hey @RashelF,

You'll want to open up the index.html file and add a <a> link that will take a user to your advice page. Once you add that in, you'll need to follow Ann's instructions above - add, commit, and push.

Then we can get this merged in!

xoxo,
Sharon

**Comment by RashelF** [comment]
I swear I added that already but I just searched my name and didn't find
it. I feel like that has happened before with this Git course. Okay, I'll
add the link to HTML and do the push again and cross my fingers.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by RashelF** [comment]
I don't know why I'm struggling with this so much. I've added screenshots
that show that my HTML link is in the advice folder, that its working and
that when I tried to add the command in Bash it said there was nothing to
add, commit or push. I tried the add command like this as well: git add
rashel-f-advice.html and it said it didn't match any files. Is that where
it's going wrong? Or is doing the git add -A okay?



<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by acodeinprogress** [comment]
Hey @RashelF,

Those screenshots don't seem to have come through properly. Can you please email them to questions@skillcrush.com?

xoxo,
Sharon

**Comment by redrambles** [comment]
Hey @RashelF - 

I know that we have been trying to communicate about this issue via e-mail. How is it going with this at this point?

**Comment by RashelF** [comment]
I haven’t attempted it again recently. The last few time I tried I was getting the same error. I can try again but I feel like talking to someone is the best way for me to figure out what I’m doing wrong.

**Comment by redrambles** [comment]
YAY!!

**Pull request merged**
