### PR TITLE
Add's Suzanne's advice

### PR DESCRIPTION
**Pull request by summerofsoz**
Adding some advice I'd like to share with future Skillcrushers

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @summerofsoz !

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. If you're not sure how to do this, feel free to take a look at other students links for reference. :)

Once you add your link, add and commit your changes and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by summerofsoz** [comment]
@redrambles Hi Ann. I added my link but can't tell if it updated my pull request?? How do I check?

**Comment by acodeinprogress** [comment]
Hey @summerofsoz,

If you click on the [commits](https://github.com/skillcrush/105-practice/pull/536/commits) tab near the top of your page, all of your commits that have been pushed up to this branch will show. I don't see that any changes have been made. Did you make sure to make the changes on your suzanne-105-practice branch on your computer and then push to the suzanne-105-practice branch on GitHub?

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @summerofsoz,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
