### PR TITLE
Added Jenn C advice page, image folder, and css

### PR DESCRIPTION
**Pull request by jcameron2486**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hi @jcameron2486,

I see that you added an image to the project. Unfortunately we cannot accept images in this repository - as it would quickly become too large. You can definitely link to existing online images, though! :)

Please remove your `img` directory with the images inside, and update your image links in your advice page. 

Then you'll need to run `git add -A`, commit, and push, your changes will join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by jcameron2486** [comment]
Hi @acodeinprogress,

I wondered about that when I did it seeing as no one else had done that before, but decided to take a chance.

I have modified to a link and removed the directory / file and pushed the changes. Let me know if there are still any issues.

Jenn

**Comment by acodeinprogress** [comment]
Hey @jcameron2486,

Thanks for making those changes! It looks like you may have tried fixing a merge conflict and ended up leaving those in the index.html.

You'll need to take the additional step of removing those conflict markers before we merge this in.

Then you can add, commit, and push again and we can get your changes merged in!

xoxo,
Sharon

**Comment by redrambles** [comment]
Hey @jcameron2486,

Thanks for making those changes!! You did a great job and your code is all merged in! Yay!

Cheers,
Ann :)

**Pull request merged**
