### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by LizzSoup**
Adding Lizz's advice changes!

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @LizzSoup !

This is really good! I only have two little requests:

1) We still need a link to your advice page in the main index.html file. Most students add their link either to the top or to the bottom of that long list. :)

2) Your advice page is linking to `lizz-s-style.css` in the head of the document - but your stylesheet is located at `css/lizz-s-style.css`. When you correct that link, your styles will apply as expected.

Once you make those changes, add and commit and then push up your advice branch once more - which will automatically update this pull request. Then we should be all set to merge in your code! :)

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by LizzSoup** [comment]
Thanks, Ann :)

I planned to fix the css link once I moved it to the css folder, and
totally forgot - and then I completely forgot to add and commit the updated
index.html.

It looks like the changes updated on Github, so hopefully it's looking
better. Should I have forked my changes first before pushing them to git,
or is version control not necessary for un-merged pull requests? Like
learning a new dance, I'm still figuring out when to do which steps!

**Comment by LizzSoup** [comment]
Hi @redrambles - it's been a few days and I wanted to check in to see if my changes were okay. 
I see that there are conflicts on this branch, and saw in slack that it's common and shouldn't be an issue. Hopefully that's correct, and if not, let me know what I need to do to fix it up :)

**Comment by redrambles** [comment]
Hey @LizzSoup,

Yes! Sorry about the delay - your changes are fabulous, and your code is merged in! Yay!!! :)

Cheers,
Ann :)

**Comment by LizzSoup** [comment]
Woohoo!!!! 💫 Pas de problème ! Merci beaucoup

**Pull request merged**
