### PR TITLE
advice on skillcrush

### PR DESCRIPTION
**Pull request by Rahina2**
piece og advice for newbies.

### CODE REVIEW

**Comment by Rahina2** [comment]
advice for newbies.

**Comment by acodeinprogress** [comment]
Hey @Rahina2,

This looks great so far! There are just a couple small changes that we'll need to make.

It looks like you changed another student's advice file. You can see these changes highlighted in pink with minus signs at the beginning of each removed line if you look at the [Files Changed tab](https://github.com/skillcrush/105-practice/pull/128/files) near the top of this page. We'll need that file restored back to its original code.

Some similar changes were made in the index.html file. Two students' links were removed so we'll need those put back as well.

Once you make those changes, you'll need to add, commit, and push your code to GitHub. Then we can get it merged in.

xoxo,
Sharon

**Comment by Rahina2** [comment]
My correction pull request.

**Comment by acodeinprogress** [comment]
Hey @Rahina2,

It looks like there is still some information missing from that file. Want to give this another try?

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @Rahina2,

I just saw that you had another pull request that was merged in so I'm going to go ahead and close this pull request.

Great job!

xoxo,
Sharon

**Pull request closed without merging**
