### PR TITLE
Added gary-s html and css files

### PR DESCRIPTION
**Pull request by Simnett-G**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @Simnett-G!

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that long list. :)

Once you add your link, add and commit your changes and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by Simnett-G** [comment]
Hi Ann,

Think that's all done now.

When I opened the file the link was already there! I wonder if I'd simply
not saved it?

Anyway, hopefully all is ok now.

Thank you,

Gary.

**Comment by Simnett-G** [comment]
Hi Ann, 
I don't understand why I have a conflict here.
Screenshot 2020-04-05 at 14 49 50

**Comment by acodeinprogress** [comment]
Hey @Simnett-G,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
