### PR TITLE
Added Rosie Pi advice link

### PR DESCRIPTION
**Pull request by rosie-pi**
Please review.

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @rosie-pi,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by redrambles** [comment]
Hey @rosie-pi !

How's it going with this? Did you need some help?

Cheers,
Ann :)

**Comment by rosie-pi** [comment]
Hi @acodeinprogress and @redrambles, I believe the last step has been resolved. Please let me know. Thanks for your patience. :)

**Comment by acodeinprogress** [comment]
Hey @rosie-pi,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
