### PR TITLE
Edited html and css files

### PR DESCRIPTION
**Pull request by brii-codes**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @brii-codes !

Love what you did with your page!!! There's just a few things we need to address before we are good to merge this in.

1) Unfortunately we cannot accept images as part of pull requests, as our repo would soon get too large. You are more than welcome to display an image that is hosted somewhere online, however! Please remove the 'img' directory. 

2) The `css/style.css` file was accidentally deleted. This is a file that many students link to as a 'default' of sorts, if they didn't want to create their own css file (which is totally fine!) - so we need it. Please add the style.css file back to the css directory. (You can recreate it and copy/paste the contents from the master branch, if you need to - or you can check it out directly like this: `git checkout master css/style.css`)

3) We still need a link to your HTML file in the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that long list. :)

Once you make these changes, add with `git add -A`, commit as per usual and then push your advice branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by brii-codes** [comment]
Hi Ann, I believe everything has been fixed and now up to date! please let me know.

**Comment by acodeinprogress** [comment]
Hi @brii-codes,

This is almost ready to be merged in!

The last step is removing the img folder and file from the repo. Once you do that, you can follow the same steps of adding, committing, and pushing and then this should be ready to go!

xoxo,
Sharon

**Comment by brii-codes** [comment]
Hi Sharon !

should be all set to now !

**Comment by redrambles** [comment]
Hey @brii-codes !

Thanks so much for making those changes, your code is all merged in!

Cheers,
Ann :)

**Pull request merged**
