### PR TITLE
Added kimberley-t Advice page and merged with master

### PR DESCRIPTION
**Pull request by KimberleyDTL**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @KimberleyDTL !

This is good! The only thing is that there is a `t-advice.html` folder that has been added that we do not need. Please delete that folder, and then add the change with `git add -A` - then commit as per usual, and push up your advice branch once more, which will automatically update this pull request. Then we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by KimberleyDTL** [comment]
Hi Ann,

 

I did all the things mentioned below but I’m not sure that I’m seeing any changes in Github?   I want to make sure that I don’t miss the window to close this.  I thought I’d done everything right last night. ☹

**Comment by redrambles** [comment]
Hey @KimberleyDTL !

Ok! So first make sure that you have added and committed your changes by running `git status`. If there is anything to add and commit, please do so. Then you'll want to push up your branch again, and we will see the change on GitHub. Keep us posted!

Cheers,
Ann :)

**Comment by KimberleyDTL** [comment]
> Hey @KimberleyDTL !
> 
> Ok! So first make sure that you have added and committed your changes by running `git status`. If there is anything to add and commit, please do so. Then you'll want to push up your branch again, and we will see the change on GitHub. Keep us posted!
> 
> Cheers,
> Ann :)

Hi Ann,

I ran Git Status on both the master branch and the advice branch and both were clean.  I saw under all the comments here the following comment so I ran Git Push Origin Advice.  I think last time I pushed Master instead.  Maybe that was the problem? Fingers crossed it worked this time! 

Add more commits by pushing to the advice branch on KimberleyDTL/105-practice.

**Comment by acodeinprogress** [comment]
Hey @KimberleyDTL,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
