### PR TITLE
Added Stacie's advice

### PR DESCRIPTION
**Pull request by staciet**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @staciet !

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that long list. :)

Once you add your link, add and commit your changes and then push your advice branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by staciet** [comment]
Hi Ann,

I actually added my link to the middle of the list! I know I'm weird but I
didn't want to be at the top and when I saw it wasn't alphabetical I
decided to pick somewhere in the middle. My mind is a mystery. Let me know
if you can't find it and I will move it to the top.

Thanks,
Stacie

**Comment by redrambles** [comment]
Hey @staciet !

Haha- my mind is a mystery too - totally relate! However- the issue here isn't where your link is placed in the index.html file (in the middle is just fine) - it's that this particular change hasn't made it up with your pull request. If you have a look at the diff view of what is included in your pull request over here (https://github.com/skillcrush/105-practice/pull/1473/files) - you'll see that the only file we have is your advice file -and we don't see any changes to the index.html file. If this change was made locally - in the advice branch - make sure that it has been added and committed (use `git status` to see if anything is pending there). If `git status` returns clean, it may not have been pushed up - so try pushing up your advice branch once more `git push origin advice`. We'll go from there!

Cheers,
Ann :)

**Comment by staciet** [comment]
Hi Ann!

I see what you mean. I have pushed the file. Let me know if that worked.

Stacie

**Comment by acodeinprogress** [comment]
Hey @staciet,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
