### PR TITLE
added michelle advice

### PR DESCRIPTION
**Pull request by ml-nguyen**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @ml-nguyen,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by ml-nguyen** [comment]
Hi Sharon, I went ahead and made the changes you requested. I think I did them correctly, but now I see some merge conflicts. It looks like another Skillcrusher edited the index.html in the meantime so it conflicts with my changes. Am I the only who can resolve this conflict or can you resolve this conflict?

**Comment by ml-nguyen** [comment]
Okay...after much troubleshooting, I was able to resolve the merge conflict. I'm not sure what exactly what I did, but I'm proud that I figured it out! Hahaha. It was definitely good practice.

**Comment by acodeinprogress** [comment]
Hey @ml-nguyen,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
