### PR TITLE
Created my verison advice html and css

### PR DESCRIPTION
**Pull request by edev87**
Some advice that I thought would be helpful to share.

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @edev87 !

This is a good start! We just need a few little changes in order to get this merged in.

1) Your `ernest-advice.html` file is in the root of the project folder - but we need it to be in the `advice` folder.

2) We cannot accept images as part of the pull request, unfortunately, as our repo would soon become too large. You are more than welcome to link to a hosted image, however! :) 

3) We are missing a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. If you're not sure how to do this, feel free to take a look at other students links for reference. :)

Once you make these changes, add and commit them and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by edev87** [comment]
Im a little confused on how to move my html file from the root folder into
the correct folder. Can you assist me with this or get me started in the
right direction?

**Comment by acodeinprogress** [comment]
Hi @edev87,

You can do this using the file/folder gui on your computer. If you're on a Mac, this would be called Finder and if you're on a PC, it would be called File Explorer. You can simply drag the file from the root folder into the advice folder.

xoxo,
Sharon

**Comment by edev87** [comment]
I moved my html file to the correct folder now I am trying to merge my new
branch with master, but I am having trouble writing the commit message. I
am at the stage in the screenshot attached. I am using a mac, do you know
how to write the commit message at this stage? I tried typing straight in
the terminal but it appears I need to do something different in order to
write to the terminal normally as I would usually do.

**Comment by acodeinprogress** [comment]
Hey @edev87,

I don't see that your screenshot is attached here. Can you please email it to questions@skillcrush.com so that we can have a look?

xoxo,
Sharon

**Comment by redrambles** [comment]
Hey @edev87,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Pull request closed without merging**
