### PR TITLE
Advice Branch to Add

### PR DESCRIPTION
**Pull request by chaudhryna**
Please pull my branch into the 105-practice repo.

Thank you!

Nancy

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @chaudhryna !

This is looking great! We just have a few conflict markers that we need you to remove inside the index.html file.

Once you make that change, add and commit and then push up your advice branch once more - which will automatically update this pull request. Then we should be all set to merge in your code! :)

Let us know if you have any questions!

Cheers,
Ann :)s

**Comment by chaudhryna** [comment]
Ok.  I think I finally have this correct.  You said it will automatically update the pull request.  Is there a way that I can check that?

Thank you!

**Comment by redrambles** [comment]
Hey @chaudhryna,

Thanks for making those changes - your code is merged in!! :)

And you can always look at the status of your pull request here:  https://github.com/skillcrush/105-practice/pull/1017/files

Cheers,
Ann :)

**Comment by chaudhryna** [comment]
Fantastic!

Thank you!

Nancy

**Pull request merged**
