### PR TITLE
jl4syth advice addition

### PR DESCRIPTION
**Pull request by jl4syth**
My advice to share.

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @jl4syth !

This is great - but unfortunately we cannot accept images in this repository - as it would quickly become too large. You can definitely link to existing online images, though! :)

Please remove your 'advice-img' directory with the images inside, and update your image links in your advice page - add your changes with `git add -A`, then commit and push up your branch, which will automatically update this pull request.

Then we should be all set to merge in your code! :) Let us know if you have any questions.

Cheers,
Ann

**Comment by jl4syth** [comment]
Shoot thank you! I will fix this today.

Lauren



*Lauren Forsyth, MS, ATC, CES*
Assistant Athletic Trainer
Sports Medicine

Intercollegiate Athletics
170 Simpson Center (SAHPC), 2227 Piedmont Ave., Berkeley, CA 94720
O: 510-664-4376  F: 510-643-0792  C*: 510-502-2366*  *E: *
lforsyth@berkeley.edu  *W*:  CalBears.com <http://www.calbears.com/>

Follow us on Facebook <http://www.facebook.com/calathletics> | Twitter
<http://www.twitter.com/calathletics> | YouTube
<http://www.youtube.com/calathletics>

**Comment by jl4syth** [comment]
I have removed the pictures files and added links.

**Comment by redrambles** [comment]
Hey @jl4syth !

Thanks so much for making those changes - your code is all merged in! :)

Cheers,
Ann

**Pull request merged**
