### PR TITLE
personalized

### PR DESCRIPTION
**Pull request by kprimavera**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @kprimavera !

Congrats on making your pull request! The only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that long list. :)

Once you add your link, add and commit your changes and then push your advice branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by kprimavera** [comment]
Hi Ann.  I'm really confused.  I'm not sure where to find the main index.html file to add my link.  Also, I don't even know where to find my link.

**Comment by acodeinprogress** [comment]
Hi @kprimavera,

If you look directly in the 105-practice folder, there is a file called index.html. That is the file that you want to edit.

The link that you add will need to be the name of your advice file. It should follow the format of the other links in the index.html file.

Does that help clarify?

xoxo,
Sharon

**Comment by kprimavera** [comment]
Hello. I added my link but when I got to the part where I had to push everything my terminal stoped. it crashed and wouldn't let me go further.  How can I delete the repo on my GitHub to start all over? I've been stuck on this for 2 days.

**Pull request closed without merging**
