### PR TITLE
christydavis1123-advice.html

### PR DESCRIPTION
**Pull request by cdavis1123**
just practicing and submitting a pull request for my changes.

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @cdavis1123,

Awesome job here! We'll just need you to make a few small changes before we can get this merged in.

1. We would like for your advice HTML file to be in the advice folder.
2. Your CSS file should also be in the css folder.
3. You'll need to open up the index.html file in your text editor and add a link that will take the user to your advice page.

Once you make those changes, you'll need to run a slightly different git command (`git add -A`), commit, then push, your changes will join your pull request here.

xoxo,
Sharon

**Comment by cdavis1123** [comment]
So I don’t need to do another pull request? I did the steps as instructed. 

Thanks for your feedback! 
Christy

**Comment by acodeinprogress** [comment]
Hey @cdavis1123,

Sorry for the confusion!

It looks like you moved the location of the index.html from the root folder to the advice folder and the location of the README.md file from the root folder to the css folder. We want those to remain in the root folder so we'll need for you to move those back. Once you do that, you'll need to open the index.html file in your text editor and add a link that will take the user to your advice page if they click on it.

Once you've done that, you can run the same `git add -A` command, then commit and push. Just as you suggested, you don't need to make another pull request as long as you do your work on the same branch! 

xoxo,
Sharon

**Comment by cdavis1123** [comment]
Ok I hope I finally got it! 
Thanks for all your help!
Christy

**Comment by redrambles** [comment]
Hey @cdavis1123,

You did a great job and your code is all merged in! Yay!

Cheers,
Ann :)

**Pull request merged**
