### PR TITLE
Clara's Advice

### PR DESCRIPTION
**Pull request by CRenauro**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @CRenauro,

Congrats on making your first pull request!

There are a few changes that we'll need for you to make here before we can get this merged in:

1. We would like for you to include a link to your advice page in the index.html file. 
2. Your advice file should be in the advice folder instead of the root folder of your project. You can simply move it into the right folder and that will fix the issue.

Once you do those things, all you have to do is run `git add -A`, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by CRenauro** [comment]
Thank you Sharon, changes have been made.

**Comment by redrambles** [comment]
Hello @CRenauro !

We aren't seeing any changes on our end. Do you remember making the changes in your advice branch, and then adding and committing them? If so - can you try pushing up your advice branch once more please with `git push origin advice` ?

Thank you! :)

Cheers,
Ann :)

**Comment by CRenauro** [comment]
Hi Ann-

The files were changed earlier today and I moved the advice file into the advice folder.


I just tried git push origin clara-r-advice.html and I received an error.

> On Sep 22, 2020, at 2:55 PM, Ann Cascarano <notifications@github.com> wrote:
I don’t know what to do next.

Sincerely,
Clara

**Comment by redrambles** [comment]
Hello @CRenauro !

Ok! So the syntax for the push command is:
`git push <which_remote> <which_branch>`

Instead of `git push origin clara-r-advice.html`, try `git push origin advice`. 

Let us know how this goes!

Cheers,
Ann :)

**Comment by CRenauro** [comment]
Hi Ann-

Forgive me for not following your directions exactly. It seems like it worked this time.



Thank you,
Clara

**Comment by redrambles** [comment]
Hey @CRenauro !

No worries!! Thanks for making those changes, your code is all merged in! yay!!

Cheers,
Ann :)

**Pull request merged**
