### PR TITLE
advice contribution

### PR DESCRIPTION
**Pull request by kimbermoulton**
contribution for project

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @kimbermoulton,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by kimbermoulton** [comment]
Hi! Sorry for the delay, I've made the changes and pushed them through

**Comment by acodeinprogress** [comment]
Hey @kimbermoulton,

I'm not seeing any changes here. Did you make sure to make the changes on your kimberedit branch and then push up to the kimberedit branch on GitHub?

xoxo,
Sharon

**Comment by kimbermoulton** [comment]
I think I got it this time! I hope... hehe

**Comment by acodeinprogress** [comment]
Hey @kimbermoulton,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
