### PR TITLE
Styled and added webpage to advice list

### PR DESCRIPTION
**Pull request by boykode**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @boykode,

This is a great start! Just a few things that we need before we can merge this in.

1) You linked to a CSS file from your advice file `css/maxine-b-advice.css` but this file isn't present in your pull request. Does it still need to be added and committed?

2) We are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that long list. :)

Once you make these changes, add with `git add -A`, commit as per usual and then push your advice branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by boykode** [comment]
Hi Ann,

Thank you for catching those errors and being so thorough in how to
correct! Unfortunately, I made changes a couple days ago and committed a
couple of typos.

I went back into my code today to correct the typos and attempted to push
the branch, but I've received an error message. From my interpretation of
the hints provided, I must perform another pull request. Should I go
through the process top to bottom once again with forking/SHSS etc? Is
there something I'm not seeing on my end?

Thanks so much for your help and looking forward to working towards a
solution :)

- Maxine

**Comment by boykode** [comment]
My apologies, I will attach a screenshot of the message received. If there
is any other documentation I can provide please let me know!

**Comment by redrambles** [comment]
Hey @boykode ! 

No need to open up a new pull request - we can work with this one. The screenshot didn't come through here, though - so why don't we continue our convo at 'questions[at]skillcrush.com' ? You'll be able to send us all the screenshots you like there, and we'll work through the changes that are needed so that we can get this pull request accepted.

Cheers,
Ann :)

**Comment by redrambles** [comment]
Hey @boykode !

Thanks for making those changes - your code is all merged in! 🎉 

Cheers,
Ann :)

**Pull request merged**
