### PR TITLE
color

### PR DESCRIPTION
**Pull request by ju-l**
Here are my changes

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @ju-l,

This looks great! I just have a couple small requests before I merge this in.

1. We would like for you to include a link to your advice page in the index.html file.
2. It looks like you altered someone else's advice file instead of creating your own. We want to preserve everyone's work so you'll need to restore that other file and then create a separate file for your work. You can see the changes that were made by looking at the Files Changed tab near the top of this page.

Once you make those changes, you'll want to run a slightly different git command (`git add -A`), then commit and push and it will join your pull request here. Then, we can get it all merged in.

xoxo,
Sharon

**Comment by ju-l** [comment]
First of all, let me apologize for messing with someone else's work I don't even know how I did this. I did hit a wall on this project and got looking at the other files in the folder to get some insight. I then abandonned the project for a number of days and went back to it and finished it in a bit of of rush, without checking everything properly.
Ok so, I am going to need help with this. I am trying to restore the natalie-advice html file still, but I am having difficulties. I looked at the files changed tab at the top of the page and I copy/pasted the code there on a new atom file titled natalie-advice.html. I then removed all the lines that had my name on it leaving just natalie's content and I saved in the advice folder. When i open it in my browser i don't get much at all. half the text is missing and the css doesn't display at all. I ran the code in the w3 validator and it came out invalid...What does this mean?

**Comment by ju-l** [comment]
ok nevermind my first message. I was able to restore the natalie-advice file.

**Comment by acodeinprogress** [comment]
Hey @ju-l,

Did you happen to get an error message when you pushed up to GitHub? The problem here is that you made your changes on your experiments branch but then you pushed them to your master branch. Instead, we want to push to our experiments branch with this command:
`git push origin experiments`

Then your changes should automatically update this pull request without you needing to take any extra steps.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @ju-l,

Awesome! It looks like your changes came across!

There's just one last thing that we'll need to do. I'm still seeing some changes to the natalie-advice file. You can see what the changes were by looking at the [Files Changed tab](https://github.com/skillcrush/105-practice/pull/35/files) near the top of this page. Once that's fixed up, you can add, commit, and push to the experiments branch and your changes will automatically show up here again.

xoxo,
Sharon

**Comment by ju-l** [comment]
I don't know how to fix this further. I looked at the files changed tab, but I can't figure out what needs to be different i just don't know what to look for...

**Comment by acodeinprogress** [comment]
Hey @ju-l,

If you take a look at the file in that tab, you'll see that some lines are highlighted in pink/red and others are highlighted in green. The ones in red are the lines that were removed and the ones in green are the ones that you added.

If you added the same line but with something as small as an extra space, you would see the original line in red and the same line, but with the extra space that you added, in green. Does that help?

xoxo,
Sharon

**Comment by ju-l** [comment]
Yes, that helped me a lot. Ok so I restore the file exactly how it was before. I saved it onto my 105-practice  folder on my computer. I am confused as to how and where to send the folder to? pull?push? and where to?

**Comment by redrambles** [comment]
Hello @ju-l !

Ok! If you have restore your file, you will first want to make sure that you are in your experiments branch. Presuming we are all good there, running `git status` should reveal that Git spots the change to the file. If that's correct, you'll want to add and commit that change and then push up your experiments branch once more, which will automatically update this pull request.

Then we should be all set!

Let us know if you have any more questions!

Cheers,
Ann

**Comment by acodeinprogress** [comment]
Hey @ju-l,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
