### PR TITLE
Carolyn's advice

### PR DESCRIPTION
**Pull request by carinahuff**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hi @carinahuff,

Congrats on making your first pull request!

It looks like you nested your advice file in a folder with the same name as your advice file. You'll need to move your advice file out of that folder and then directly into the advice folder. Once you do that, you can delete the extra folder.

Once you make those changes, you can run `git add -A`, then commit and push your work up to GitHub. Then we can merge in your changes.

xoxo,
Sharon

**Comment by carinahuff** [comment]
I think I did what you asked.  Unclear whether or not I did the commit part right or if I needed to go back and redo the whole merge upstream process.  Please let me know.

**Comment by acodeinprogress** [comment]
Hi @carinahuff,

Hmmm I'm still seeing that extra advice file when looking at the [Files changed](https://github.com/skillcrush/105-practice/pull/1275/files) tab near the top of the page.

Try deleting the folder/file and then run `git add -A` and then commit and push.

xoxo,
Sharon

**Comment by redrambles** [comment]
Hey @carinahuff !

Ok- we're almost set here! We just need to get rid of that extra HTML file in the root of the folder before we can merge this in:

1) Delete the `carolyn-ih-advice.html` file any way you prefer (either via the Terminal / Git Bash or by dragging it to the Trash / Bin). We just want to keep your .html file that you added to the `advice` directory - but we want to remove the one that is in the root of the folder.

2) Once that file is gone, please add the change in the Terminal by running `git add -A` - then commit as per usual (`git commit -m "Your message here"`) and then push up your advice branch once more (`git push origin advice`) - which will automatically update this pull request.

Then we should be all set to merge in your code. Let us know if you have any questions!

Cheers,
Ann :)

**Comment by redrambles** [comment]
Hey @carinahuff ,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Pull request closed without merging**
