### PR TITLE
Added Alain's advice page

### PR DESCRIPTION
**Pull request by adanielcode**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @adanielcode,

Congratulations on making your first pull request!

I noticed that your advice and styles files are in the main directory of the project. Instead, they should be in their respective folders - advice and css.

There are also a lot of changes to the index.html file - the only change that should show is the addition of your link to your advice file.

Once you make those changes, you'll need to run `git add -A`, commit, and push your work to GitHub. They'll join your pull request here and then we can get this merged in.

xoxo,
Sharon

**Comment by adanielcode** [comment]
I sent that pull request in by mistake. I think I've resolved the issues. Please let me know.

**Comment by acodeinprogress** [comment]
Hi @adanielcode,

I'm still seeing a lot of changes to the index.html file and your advice and css files haven't been moved yet.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @adanielcode,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
