### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by shamham**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @shamham,

Congrats on making your first pull request!

It looks like you included some merge conflict markers as part of this pull request. You'll need to make sure to remove them before this can be merged in.

Once you've done that, you'll need to add, commit, and push your work up to GitHub and we can get this merged in.

xoxo,
Sharon

**Comment by shamham** [comment]
Hi there, I actually had a question on this. It looks like it's asking me
to choose between adding my link, and removing A BUNCH of other student's
links below it. Can you let me know how I should resolve this? See attached
screenshot.

**Comment by acodeinprogress** [comment]
Hi @shamham ,

You'll want to keep your link as well as all the other students' links. You can just remove the conflict markers and leave the rest.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @shamham,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
