### PR TITLE
advice works edit

### PR DESCRIPTION
**Pull request by medusamills**
Hi! I completed this assignment! Thanks!!

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @medusamills !

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. If you're not sure how to do this, feel free to take a look at other students links for reference. :)

Once you add your link, add and commit your changes and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by medusamills** [comment]
Hi! Just letting you know that I got your message and it is on my agenda today. I got a new job on Monday, launching a political campaign as the Social Media Manager, so I've been consumed for several days doing that. But, I will get this corrected. Thanks so much!!! --M

Sent from Yahoo Mail on Android 
 
  On Mon, Apr 8, 2019 at 9:14 AM, Ann Cascarano<notifications@github.com> wrote:   
Hey @medusamills !

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. If you're not sure how to do this, feel free to take a look at other students links for reference. :)

Once you add your link, add and commit your changes and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by medusamills** [comment]
Hi! I corrected the index.html file by adding the link to Misti's Advice. Thanks!

**Comment by redrambles** [comment]
Hey @medusamills,

You did a great job and your code is all merged in! Yay!

Cheers,
Ann :)

**Pull request merged**
