### PR TITLE
I've added my personal advice page with css to the main page

### PR DESCRIPTION
**Pull request by melanienewell**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @melanienewell !

I love your advice!!! This is all really good - the only thing that is missing is a tiny little `<br>` tag at the end of your link on the advice page, so that the next link sits on its own line. Other than that, it's perfect!

Once you have made your change, please add and commit as per usual and push up your advice branch once more, which will automatically update this pull request. Then we should be all set to merge in your code!

Let us know if you have any questions.

Cheers,
Ann :)

**Comment by melanienewell** [comment]
Oopsy! Power of collaboration :) thanks! I updated the line and I believe it's all good to go now!

**Comment by melanienewell** [comment]
Ok thanks!

I edited that line of code in Github and saved (committed?) the changes. Do
I still need to re-submit a pull request or is it still active? I checked
my local git status and it says everything is up to date with the origin.

Let me know,

Melanie N.

**Comment by redrambles** [comment]
Hey @melanienewell !

This is perfect! When you pushed up your branch, this pull request was updated - and we got our `<br>` tag now. :) All set - I'm merging in your code. :)

Cheers,
Ann :)

**Pull request merged**
