### PR TITLE
Added Jasmine's new advice

### PR DESCRIPTION
**Pull request by Jasmine582**
Hi acodeinprogress,

Yikes! There was a commit issue and I hope I resolved it. If not then I will repeat this process.

Jasmine

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @Jasmine582,

I noticed that you didn't add an advice page or any css. If you could add those things, that would be great! Once you do that, you can add, commit, and push your work and it will join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by Jasmine582** [comment]
> Hey @Jasmine582,
> 
> I noticed that you didn't add an advice page or any css. If you could add those things, that would be great! Once you do that, you can add, commit, and push your work and it will join your pull request here.
> 
> Let us know if you need any help!
> 
> xoxo,
> Sharon

**Comment by acodeinprogress** [comment]
Hey @Jasmine582,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Comment by Jasmine582** [comment]
OH NO! I had an error and I thought I fixed it. Cool this gives me more
practice. :)

**Pull request closed without merging**
