### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by mlem567**
Another pull request from Mike Lem

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @mlem567,

Congrats on making your first pull request!

There are a couple changes that you'll need to make here before we can merge this pull request:

1. There is an extra advice file in the root folder of this project
2. In the index.html file, there is some extra code in the middle of the file that look like this that will need to be removed:
```</div>
        </div>
    </section>
  </body>```

Once you make those changes, you'll need to run `git add -A`, commit, and push your work to GitHub. Your changes will join your pull request here and then we can get this merged in!

xoxo,
Sharon

**Comment by mlem567** [comment]
Hi Sharon 
I removed that html code and pushed the changes. 
Thanks
Mike

**Comment by acodeinprogress** [comment]
Hey @mlem567,

I don't see that those changes are showing up here.

Did you make sure to make both of those requested changes on your advice branch and then push to your advice branch? If not, you'll need to do that.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @mlem567,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
