### PR TITLE
Meg S's advice

### PR DESCRIPTION
**Pull request by Meg1212**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @Meg1212 !

This is a good start! We just need a few more things before we're ready to merge this in.

1) Your advice file is `advice/meg-s-advice/meg-s-advice.html` - but we really just want it to be directly inside the 'advice' directory - and not nested inside another 'meg-s-advice' directory.  You can move your `meg-s-advice.html` file inside the advice directory and delete the (now empty) `meg-s-advice` directory.

2) We are missing a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that long list. :)

Once you move your file, delete the folder and add your link, add your changes with `git add -A`, commit as per usual and then push your advice branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by Meg1212** [comment]
Hi,
I think I fixed the problem with my git advice files.  But now, I seem to
be struggling with my git add and commit.  I received this error message.
(screenshot attached) I feel like I screwed something up and I can' figure
it out.  I'm really struggling with Git!

-Meg Sedivy

**Comment by redrambles** [comment]
Hey @Meg1212 !

The screenshot unfortunately didn't make it across on this platform - would you like to continue this conversation [via email](questions@skillcrush.com)? No worries, we'll work through this together!!

Cheers,
Ann :)

**Comment by Meg1212** [comment]
Hi Ann,

I can try sending the screen shot again. And yes, I am good continuing
through email.

Thanks
Meg

**Comment by acodeinprogress** [comment]
Hey @Meg1212,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
