### PR TITLE
Add Amandas Advice

### PR DESCRIPTION
**Pull request by neelyab**
Some advice I'd love to share.

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @neelyab,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by neelyab** [comment]
Oh yes, I totally forgot! I just added and committed it.

Thanks!
Amanda

Sent from my iPhone

On Oct 18, 2019, at 10:28 AM, Sharon <notifications@github.com> wrote:

Hey @neelyab <https://github.com/neelyab>,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the
index.html file. If you could add that in, all you have to do is add,
commit, and push your changes and they will join your pull request here.
Once you do that, we can get it all merged in.

xoxo,
Sharon

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/skillcrush/105-practice/pull/709?email_source=notifications&email_token=ALDZUAINI7ILGCC6SZSD26LQPHBXLA5CNFSM4JCH4UOKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEBUVA5Y#issuecomment-543772791>,
or unsubscribe

**Comment by acodeinprogress** [comment]
Hey @neelyab,

I'm not seeing those changes. Did you make sure to make them on your experiments branch on your computer and then push to your experiments branch on GitHub?

xoxo,
Sharon

**Comment by redrambles** [comment]
Hey @neelyab,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Pull request closed without merging**
