### PR TITLE
added my advice page and css

### PR DESCRIPTION
**Pull request by emaggen**
hi! i've added my advice page and css

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @emaggen !

This is a good start! We are still missing your styles, which should be in a file that you create inside the /css directory.

Once you add your styles, add and commit your changes and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by emaggen** [comment]
Hi! not sure what happened but my css style file was already added to my branch. Can you see it now?

**Comment by acodeinprogress** [comment]
Hey @emaggen,

We see it now! Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Comment by emaggen** [comment]
Thank you so much! I’m still a little shaky learning the github flow. I will try to read the GitHub guide to understand it better!

Emily

**Pull request merged**
