### PR TITLE
 Advice html page link added to index.html

### PR DESCRIPTION
**Pull request by OpheliaB24**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @OpheliaB24,

We see a link to your `advice/ophelie-b-advice.html` inside the main index.html file - great! However we don't have the file itself inside the advice directory. Does it still need to be added an committed? Once you have that done, push up your advice branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code. Let us know if you have any questions!

Cheers,
Ann :)

**Comment by redrambles** [comment]
Hey @OpheliaB24 !

Thanks for adding that file - we are nearly there! The last little issue now is that your `ophelie-b-advice.html` file is sitting in the root of the project directory, but we need it to be inside the `advice` directory. Please move it inside the advice directory, then add your changes with `git add -A`, commit as per usual and push up your advice branch once more, which will update this pull request once more.

Then we should be all set to merge in your code. Nearly there!!

Cheers,
Ann :)

**Comment by OpheliaB24** [comment]
Hi Ann,

Thanks for your email.
I'm confused! I guess this is not locally that you need
ophelie-b-advice.html file to be sitting inside the advice directory, right?
If yes, I did it!
But if not, I'm not sure what to do.

Thanks for your help

Ophelie

**Comment by acodeinprogress** [comment]
Hi @OpheliaB24,

It looks like in the process of making that change, you added a bunch of other files. When you click on the [Files Changed](https://github.com/skillcrush/105-practice/pull/1520/files) tab near the top of this page, the end result should only show 3 files there - your advice file, your css file, and the index.html file.

Once you get everything fixed up on your computer, you'll want to run (git add -A), then commit and push and your changes will join your pull request here.

xoxo,
Sharon

**Comment by OpheliaB24** [comment]
Hi Sharon,

Thanks for your email.
In the attached screenshot, I have another problem.
I deleted the unwanted files from the root in the project directory and I
checked my HTML/CSS, and all work on webserver.
Again, I don't know what to do sorry.

I'm getting used to working with the command line but it is always quite
challenging!!

Many changes
Ophelie

**Comment by acodeinprogress** [comment]
Hi @OpheliaB24,

It is definitely challenging but totally worth the challenge!

Once you made your changes, did you make sure to push them up to to your advice branch on GitHub?

xoxo,
Sharon

**Comment by OpheliaB24** [comment]
Hi Sharon,

Thanks again for your response.
I pushed my changes again up to the advice branch on GitHub as I didn't
remember but then I got more issues. 😵
I tried to find help online to fixe it but I'm stuckkkkk!!!

Thanks
Ophelie

**Comment by redrambles** [comment]
Hey @OpheliaB24 !

Ok no worries! At this point, this is what I suggest that you do.

1) Drag your advice file and your css file (if you created a custom stylesheet) outside of their respective folder(s) and place them temporarily on the desktop.

2) Move back into your master branch `git checkout master`. 

3) Fetch from upstream and merge into your master branch so that you have the most recent code:
`git fetch upstream`
`git merge upstream/master`

4) Move back into your advice branch and forcibly bring it up to date with the upstream/master branch:
`git checkout advice`
`git reset --hard upstream/master`

5) Pop in your advice html file that you temporarily placed on the desktop into the advice directory - and same with your custom css file into the css directory if it exists.

6) Open up the index.html file and add a link to your advice file somewhere in that list of links.

7) Add your changes with `git add -A` and commit as per usual `git commit -m "Your message here"`

8) Push up your advice branch with a force push (because we changed history with the reset command, which was safe to do in this context because you are the only person working your advice branch) `git push --force-with-lease origin advice`

This will automatically update your pull request, and we should be all set to merge in your code.

I know that this is a lot of steps, but let us know if you have any questions. You got this! :)

Cheers,
Ann :)

**Comment by acodeinprogress** [comment]
Hey @OpheliaB24,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
