### PR TITLE
Added Eddymer Diaz advice page, a link on the main page to my personal …

### PR DESCRIPTION
**Pull request by Eddymerd**
…advice, and customized colors in CSS file

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hi @Eddymerd,

This looks great! The only problem is that it looks like you overwrote someone else's file to create your own file. We want to preserve everyone's work so you'll either need to reset and redo your changes or restore the other student's file.

Once you fix that up, you can run `git add -A`, commit, and push. Your changes will join your pull request here and we can get that merged in.

xoxo,
Sharon

**Comment by Eddymerd** [comment]
I synced my files with the upstream files. Please let me know if it's okay now. Thanks!

**Comment by redrambles** [comment]
Hey @Eddymerd !

Syncing with upstream is great - but it won't solve our issue with respect to the file that was edited. No worries - I can walk you through it!

The easiest way to bring this file back to it's earlier version would be to grab the version of the file that exists in your master branch. In order to do this, let's run the following:

`git checkout master advice/megan-r-advice.html`

You should see something like 'Updated 1 path' as a response in the Terminal. If you run `git status`, you will see that this file has been modified. Great! We have essentially modified it to look like its original self again. Let's add that change with `git add -A` - and then commit as per usual - and then push up the advice branch once more. That will automatically update this pull request, and then we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by acodeinprogress** [comment]
Hey @Eddymerd,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
