### PR TITLE
Added my index.html in the advice page and the corresponding css in t…

### PR DESCRIPTION
**Pull request by ealmario**
Some advice I would like to share.

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @ealmario!

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. If you're not sure how to do this, feel free to take a look at other students links and see if you can add one of your own!

Once you add your link, add and commit your changes and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by ealmario** [comment]
Hello!

All right will edit and merge. Thank you! :D

**Comment by ealmario** [comment]
Hello,

I got confused? Attached is the screenshot.

I need help. Haha.

Thanks!
[image: Screen36.jpg]

**Comment by redrambles** [comment]
This is great, @ealmario - thanks for adding the link in the main index.html file!

Your code is all merged in. :)

Cheers,
Ann

**Comment by ealmario** [comment]
Hello,

I need to clarify this though: does that mean I can push directly to the
upstream repo from Git Bash? I received errors from the first pull request
that's why I did a second.

For the second pull request, I pushed to the forked repo first then
requested the pull from there.

Which one's the way?

Sorry for this. Got confused.

Thanks!

**Comment by redrambles** [comment]
Hello! 

If your upstream branch is pointing to Skillcrush's repository, then no, you cannot push there because you do not have write access. You can fetch from there, though, and merge in the code into your master branch - and then from your master branch into your topic branch. This is all you need to do in order to stay in sync with an evolving code base.

In order to update a pull request, you only need to push to your repository, using the same branch that pull request was created from. So, if you created a pull request based of your 'advice' branch, for example - and then you make a new commit locally on your advice branch and push it up with `git push origin advice` - your pull request will automatically be updated. 

You had opened a new pull request from your master branch the second time - which is why there ended up being 2 pull requests from you.

Does this help clarify?

**Comment by ealmario** [comment]
Hello!

Yes it does! Thank you very much.

**Pull request merged**
