### PR TITLE
Practice 105

### PR DESCRIPTION
**Pull request by ke-pixel19**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @ke-pixel19,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @ke-pixel19,

Sorry for the confusion.

We would like for you to edit the index.html file and add a link that will take the user to your advice page.

Once you do that, you can add, commit, and push again. :)

xoxo,
Sharon

**Comment by ke-pixel19** [comment]
Hi Sharon,
I went to the index.html in my text editor and I thought that I had the link in there.  I did an add, commit and push in Git.  Other than that, I have no idea where to add the link.  I am really confused on what to do.

Thanks,
Kerstin

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by acodeinprogress** [comment]
Hey @ke-pixel19,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
