### PR TITLE
Added advice html and css files

### PR DESCRIPTION
**Pull request by axthomas29**
Here is my advice I would like to share!

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @axthomas29 !

Hey @username !

This is amazing - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. If you're not sure how to do this, feel free to take a look at other students links for reference.

Once you add your link, add and commit your changes and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by axthomas29** [comment]
Thank you so much Ann!

I do have in the top right corner of the header page a link to the main
HTML. It says "HOME". I wasn't sure if it blends in too much. I will
probably change that to make it more visible for people :)

Thanks for letting me know! I really appreciate it!

Best,
Alexandra

**Comment by axthomas29** [comment]
Here is my updated code! Let me know if you need me to make any changes!!

Thanks again!! :)

**Comment by acodeinprogress** [comment]
Hey @axthomas29,

Ann's suggestion was a bit different. We would like for you to open the index.html file and add a link in there that goes to your advice page. If you're not sure how to do that, there are plenty of examples of other students' links in that file.

xoxo,
Sharon

**Comment by axthomas29** [comment]
Oh I see! Haha sorry about that! Yes, I now understand what you mean.
Thanks!!!

Best,
Alex

**Comment by axthomas29** [comment]
I added the hyperlink to my advice page to the main html. Sorry again for the misunderstanding! Thank you!

**Comment by redrambles** [comment]
Excellent! Thank you for adding that link, @axthomas29 - your code is all merged in! :)

**Comment by axthomas29** [comment]
Wonderful!! Thank you! :)

**Pull request merged**
