### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by Cvaguila**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @Cvaguila,

Congrats on making your first pull request!

There is just one small change that we'll need to make here:
I see that you have an extra advice file called your-name-advice.html which is located in an extra folder called cindy-v-advice.html. You'll need to remove that extra folder and extra file and then this will be good to go!

Once you make those changes, you'll need to run `git add -A`, commit, and push. They'll join your pull request here and then we can get it merged in.

xoxo,
Sharon

**Comment by Cvaguila** [comment]
Hi Skillcrush! 

Yeah! This is great news. I just have one question. When I commit and add a comment, would I put “deleted a file” or “added new advice” not sure what I should write for my comment, since I am completing a different task than before? 

Thank you, 
Cindy

**Comment by Cvaguila** [comment]
Never mind. I went thru my notes and commented the changes that were made. I pushed it through. Hope it worked and you are able to merge it on your end. 

Cindy

**Comment by acodeinprogress** [comment]
Hey @Cvaguila,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Comment by Cvaguila** [comment]
Hi Skillcrush!!! 


That’s great news! Thank you!!! 

I will continue with the lesson. 

Happy Holidays! 

Cindy Aguila

**Pull request merged**
