### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by G-Rock1974**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @G-Rock1974 !

This is a good start! We need to address a few things - but once those are taken care of, we'll be able to merge in your code.

1) Unfortunately we cannot accept images as part of the pull request, or our repo would soon get too large. You are more than welcome to link to an existing image somewhere on the net, though! Please remove the `img/information_Tech_img.jpg` file. 

2) Your `gary-w-advice.html` file is in the root of the project folder - but we need it to be in the `advice` directory. Please move it into your advice directory (in any way you like) - and then edit the path to your css file in the 'head' of your html file - which will now need a `..` at the beginning of the path in order to properly connect. (`..css/gary-w-advice.css`)

3) You have accidentally removed a few links from other students in the main index.html file - see here: https://github.com/skillcrush/105-practice/pull/1385/files#diff-eacf331f0ffc35d4b482f1d15a887d3bL17

We want to keep all of those links, so please add them back in. You can copy/paste them into the file if you like - and make sure to keep your link too, of course. Also make sure your link is now pointing to the new location of your advice file - inside the advice folder. :)

Once you have made these changes, please add with `git add -A` - commit as per usual `git commit -m "Your message here"` and then push up your advice branch once more `git push origin advice` - which will automatically update this pull request. Then we should be all set to merge in your code! :)

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by G-Rock1974** [comment]
I'm not able to make corrections because my root file is deleted.

**Comment by acodeinprogress** [comment]
Hey @G-Rock1974,

What do you mean when you say that your root file is deleted? We can go ahead and close this pull request if you would like.

xoxo,
Sharon

**Comment by G-Rock1974** [comment]
Yes- please close


Sent from Yahoo Mail for iPhone


On Wednesday, August 19, 2020, 12:38 PM, Sharon <notifications@github.com> wrote:




Hey @G-Rock1974,

What do you mean when you say that your root file is deleted? We can go ahead and close this pull request if you would like.

xoxo,
Sharon

**Pull request closed without merging**
