### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by BMBrosch**
Requesting a pull request to complete this assignment that have been fighting with. 
Thank you

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @BMBrosch !

This is good! We just need two more things from you before we can merge in this code.

1) Please place your `Barry-B-advice.html` inside the 'advice' directory. Right now it is in the root of the project directory.

2) Please include a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that long list. :)

Once you make those changes, add and commit them and then push up your advice branch once more - which will automatically update this pull request. Then we should be all set to merge in your code! :)

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by BMBrosch** [comment]
I did that several times. I wonder why it’s not pushing... hmm

**Comment by acodeinprogress** [comment]
Hi @BMBrosch!

Are you making sure that you're making your changes on your `advice` branch and then pushing them to your `advice` branch on GitHub?

xoxo,
Sharon

**Comment by BMBrosch** [comment]
Okay. I’m lost stuck here. 

This is the list of errors I keep getting and I can’t find a solution:
I can’t seem to get the files to update / merge. 

bmbrosch@BarryMonsterAir 105-practice % git checkout
M	index.html
D	megan-r-advice.html
bmbrosch@BarryMonsterAir 105-practice % git merge upstream/master
error: Your local changes to the following files would be overwritten by merge:
	index.html
Please commit your changes or stash them before you merge.
Aborting
bmbrosch@BarryMonsterAir 105-practice % git commit -m "Added barry's advice"
On branch advice
Changes not staged for commit:
	modified:   index.html
	deleted:    megan-r-advice.html

Untracked files:
	advice/barry_B_Advice.html

no changes added to commit
bmbrosch@BarryMonsterAir 105-practice % git commit
On branch advice
Changes not staged for commit:
	modified:   index.html
	deleted:    megan-r-advice.html

Untracked files:
	advice/barry_B_Advice.html

no changes added to commit
bmbrosch@BarryMonsterAir 105-practice % open .
bmbrosch@BarryMonsterAir 105-practice % git commit -m "Barry's advice"
On branch advice
Changes not staged for commit:
	modified:   index.html
	deleted:    megan-r-advice.html

Untracked files:
	advice/barry_B_Advice.html

no changes added to commit
bmbrosch@BarryMonsterAir 105-practice % git branch -a
* advice
  master
  remotes/origin/HEAD -> origin/master
  remotes/origin/advice
  remotes/origin/master
  remotes/upstream/master
bmbrosch@BarryMonsterAir 105-practice % git fetch upstream
Enter passphrase for key '/Users/bmbrosch/.ssh/id_rsa': 
Received disconnect from 140.82.114.3 port 22:11: Bye Bye
Disconnected from 140.82.114.3 port 22
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
bmbrosch@BarryMonsterAir 105-practice % git push origin advice
Enter passphrase for key '/Users/bmbrosch/.ssh/id_rsa': 
To github.com:BMBrosch/105-practice.git
 ! [rejected]        advice -> advice (non-fast-forward)
error: failed to push some refs to 'git@github.com:BMBrosch/105-practice.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
bmbrosch@BarryMonsterAir 105-practice %

**Comment by acodeinprogress** [comment]
Hi @BMBrosch,

Ok so you'll need to make sure to commit any changes that you've made to your repo on your computer before you can integrate the changes from GitHub.

Go ahead and try that then try merging in the upstream and then push up to GitHub. 

xoxo,
Sharon

**Comment by BMBrosch** [comment]
As far as I know I am. I’ll check later when O get home

**Comment by BMBrosch** [comment]
I thought I and I kept getting errors

**Comment by BMBrosch** [comment]
Oh boy. I messed this one up. 
I apparently over wrote my 105-practice file with my 105-project..


Any tips on how to fix this mess?

**Comment by BMBrosch** [comment]
Okay. I am completely lost.I have been working this one section for a week and I’m about to drop all this class stuff. 

I’m not understanding an bit of this. 

This is the new error:
bmbrosch@BarryMonsterAir 105-practice % git commit
On branch advice
Untracked files:
	advice/barry_B_Advice.html

nothing added to commit but untracked files present
bmbrosch@BarryMonsterAir 105-practice % git merge
fatal: No remote for the current branch.
bmbrosch@BarryMonsterAir 105-practice % git checkout
bmbrosch@BarryMonsterAir 105-practice % git merge
fatal: No remote for the current branch.
bmbrosch@BarryMonsterAir 105-practice % git push origin advice
Enter passphrase for key '/Users/bmbrosch/.ssh/id_rsa': 
To github.com:BMBrosch/105-practice.git
 ! [rejected]        advice -> advice (non-fast-forward)
error: failed to push some refs to 'git@github.com:BMBrosch/105-practice.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
bmbrosch@BarryMonsterAir 105-practice %

**Comment by redrambles** [comment]
Hey @BMBrosch !

Ok - no worries! You can try this over again. What I suggest that you do is clone the fork for this repository (`https://github.com/BMBrosch/105-practice`) somewhere else on your computer - that isn't also under version control. Perhaps on your Desktop or similar. Then you can move into the repository and create a new branch - something other than 'advice' - maybe 'advice2' - and the move to that branch. You can do both of these actions with one command: `git checkout -b advice2`.

Then you should open the whole folder inside your text editor of choice - and create a new file inside the advice folder. You can copy the contents of what is in the file for this pull request into that new file if you like (https://github.com/skillcrush/105-practice/pull/964/files). Once you're done with that, pop into the index.html file and then add the link to your advice page there.

Then once everything is saved - add and commit these changes and push up your `advice2` branch (`git push origin advice2`).

Then pop into GitHub and open a new pull request based off of your `advice2` branch. We'll receive that new pull request and should be all set to merge in your code. :)

Hope this helps - keep us posted! You got this!

Cheers,
Ann :)

**Comment by acodeinprogress** [comment]
Hey @BMBrosch,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Comment by BMBrosch** [comment]
What do you mean you haven’t heard from me? I have been waiting for a response to my pull request and have not gotten a thing back. I’ve been waiting for a response or something.

**Comment by BMBrosch** [comment]
okay I'm back to fighting with this stupid file. 
This is the new error message I get. 
nothing added to commit but untracked files present
bmbrosch@BarryMonsterAir 105-practice % git push origin advice2
error: src refspec advice2 does not match any
error: failed to push some refs to 'origin'
bmbrosch@BarryMonsterAir 105-practice % 

I am so not understanding any of this and will let this fail

**Pull request closed without merging**
