### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by Angel-IglesiasP**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hi @Angel-IglesiasP,

Congrats on making your first pull request!

There is just one teeny tiny change that you'll need to make before we can get this merged in.

Your advice file has an extra `.html` at the end, so that your file has the name of `angel-i-advice.html.html`

You'll need to rename the file so that it doesn't have the extra `.html` and looks like this instead: `angel-i-advice.html`

Once you do that, you'll need to `git add -A`, then commit, and push. Your updates will join your pull request here and then we can merge this in.

xoxo,
Sharon

**Comment by Angel-IglesiasP** [comment]
Hello, Sharon! Thanks for the feedback. I just change the name, added and
committed the new HTML file. Please let me know if my pull request needs
any other changes.

Hope you are having a great day,
Angel

**Comment by redrambles** [comment]
Hey @Angel-IglesiasP !

We didn't get the change up here - looks like you might have forgotten to push up your changes to your 'advice' branch. Can you try running `git push origin advice` so that we can get your updates?

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by Angel-IglesiasP** [comment]
Hi, Ann! I just pushed the advice branch. Hope this time it works!
Thank you for your constant feedback!

Hopping you have a great weekend,
Angel ;)

**Comment by acodeinprogress** [comment]
Hey @Angel-IglesiasP,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
