### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by cerazo87**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @cerazo87 !

This is good!! The only thing we need you to change is to delete the `advice/your-name-advice.html` file that snuck into your pull request. :) Once the file is deleted, add that change with`git add -A` - commit as per usual, and then push up your advice branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by acodeinprogress** [comment]
Hi @cerazo87,

You're almost there!

It looks like you may have deleted the wrong file. You should delete the your-name-advice.html file and instead keep the charlene-e-advice.html file.

Go ahead and make that change and then run `git add -A`, commit, and push!

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
(Sorry, I accidentally hit the "close and comment" button instead of the "comment" button!)

**Comment by acodeinprogress** [comment]
Hey @cerazo87,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
