### PR TITLE
Rich's advice

### PR DESCRIPTION
**Pull request by rich2d2**
Hope my advice is helpful

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hi @rich2d2,

Awesome job so far! There are just a couple small changes that you'll need to make before we can merge this in.

1. I see that you added an image to the project. Unfortunately we cannot accept images in this repository - as it would quickly become too large. You can definitely link to existing online images, though! :) Please remove your image and update your image links in your advice page. 
2. You added two CSS files here - one is located in the css folder, which is perfect. The other is located in our main project folder. We'll want to delete the one in the main project folder.
3. Lastly, we would like for you to include a link to your advice page in the index.html file.

Once you make those changes, you'll need to run a slightly different git command (`git add -A`), commit, and push, and your updated work will join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by rich2d2** [comment]
Hi thanks for the feedback. When I make the corrections do I start over and fork the original repo, clone, and branch? I am a bit uncertain where I start to make the corrections.

Thanks
Rich

**Comment by redrambles** [comment]
Hey @rich2d2 !

No need to fork or clone again! Just make sure that you are working on your advice branch for this project and then go ahead and make the changes that Sharon outlined. Once those are done, add and commit your changes and push up your advice branch once more, which will automatically update this pull request. 

Then we should be all set to merge in your code! :)

Cheers,
Ann :)

**Comment by acodeinprogress** [comment]
Hey @rich2d2,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
