### PR TITLE
Added changes amber p advice

### PR DESCRIPTION
**Pull request by AmPrince86**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hi @AmPrince86,

Congrats on making your first pull request!

There is just one small change that we'll need for you to make before merging this in. If you take a look at the index.html file, you added a <a> that links to your advice file but you didn't add any text to it.

Once you add that in, you'll just need to add, commit, and push you work and then we can get it merged in.

xoxo,
Sharon

**Comment by AmPrince86** [comment]
Hi Sharon,

Omg l did this so many times l forgot to add my name Amber haha thank you. Fixed it and l believe l push the commits to github🤞🏾

A. Prince

**Comment by AmPrince86** [comment]
Hi Sharon,

I fixed it and pushed the commits. Thank you

**Comment by redrambles** [comment]
Hey there! 

We didn't get the pushed changes here. Remember that in order to affect this pull request - you'll need to make your changes in your 'advice1' branch - and then once you've added and committed them - push up your advice1 branch again `git push origin advice1`. Then we will get your updates and if all is well, we'll merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by AmPrince86** [comment]
Hi Sharon,

I went to my commits and there two the first from june 9th and june 11th and on june it shows l made the changes. Let me know if you see it? 


A. Prince

**Comment by AmPrince86** [comment]
Hi! I made 2 commits and in the recent commit my changes appeared in the index.html.

**Comment by AmPrince86** [comment]
Hi, There's a conflicting file in the index.html but when I go into the index.html from the command line I don't see it.

**Comment by acodeinprogress** [comment]
Hey @AmPrince86,

Looks like that came through and you're good to go! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Comment by AmPrince86** [comment]
Thank you Sharon!

A. Prince

**Pull request merged**
