### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by kahmasai**
Would like to add my, "Kuta H" advice page and css to 105-practice

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @kahmasai !

Everything is good here except that unfortunately we cannot accept images as part of student pull requests, as the repository would soon get too large. You are free to link to a version of the image that is hosted somewhere on the internet, though, of course! :)

Once you have removed the image, please add with `git add -A`, commit as per usual and then push up your `advice` file once more, which will automatically update this pull request.

Then we should be all set to merge in your code!

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by kahmasai** [comment]
Thank you Ann! I removed the img & pushed the changes up to the repo - just
after - I saw a conflict error with teh index file, I fixed it & them added
& committed that change & then pushed up to the repo once more. Not I just
see my commit comment of "adding hte index file to resolve conflict" - see
screenshot.

Please let me know if all is good & if the pull req. was automatically
updated.

Tks!!!

**Comment by kahmasai** [comment]
Hi @redrambles! I hope this latest push will make it! fingers crossed!
Best,
Kuta

**Comment by acodeinprogress** [comment]
Hi,

Unfortunately, I'm still seeing the img folder and image inside of it as part of your repo. You will need to delete the img folder from this project, including the file inside of it.

Also it looks like you removed other students links to their advice files from the index.html file. You can see exactly which links were removed by checking out the [Files Changed](https://github.com/skillcrush/105-practice/pull/1072/files) tab near the top of this page.

xoxo,
Sharon

**Comment by kahmasai** [comment]
Hi Sharon!

Thank you! I really hope i fixed the issue - I deleted the img again, but
this time from the command line - I deleted it from my finder window
before, made the same change to my css & advice.html files & updated the
index file after bringing my master branch up to date with
the upstream repo, pushed my advice branch up again & didn't get a merge
conflict error like before.

Fingers crossed !!

Here's a scrennshot of my command line for this last update -  if it helps
to ref in case there's any more conflicts.

Best,
Kuta

**Comment by kahmasai** [comment]
I just saw that I didn't run "git rm" & then commit ( I kept running "git
add") - I removed the img & folder again & pushed my advice branch back up
- I see finally the img folder is gone in my commits on the remote repo -
see screenshot att. Now hopefully this is good to go!

**Comment by acodeinprogress** [comment]
Hey @kahmasai,

Great work here!

It looks like when you fixed a merge conflict, you accidentally added in some duplicate code. If you look at your index.html file in the Files changed tab again, we can see that we have some extra green lines (the only green line we should have is your own link). We also have a merge conflict marker left in there.

We'll need to remove those duplicate links before this can be merged in. Or we can fix up the issue for you.

Let us know what you would like to do!

xoxo,
Sharon

**Comment by kahmasai** [comment]
Hi Sharon,

Thank you for reviewing  & advising on this for me! I want to accept your offer to fix & merge the code. I think I have the jist of this lesson & will look forward to more practice on this in the future!!

And I'm so sorry for all the multiple questions & pushes on this one!!!

Best,
Kuta

**Comment by acodeinprogress** [comment]
Hey @kahmasai,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Comment by kahmasai** [comment]
Praise the lord @acodeinprogress!!

Thank you so much!!! I was really holding my breath on this😊. Onto the next !!

 Xoxo!

**Pull request merged**
