### PR TITLE
styled content for advice sheet

### PR DESCRIPTION
**Pull request by mschlattmann**

### CODE REVIEW

**Comment by mschlattmann** [comment]
Add Marlena's Advice

**Comment by acodeinprogress** [comment]
Hey @mschlattmann,

This looks great! There's just one small fix that we'll need you to implement before we can get this merged in. 

It looks like you may have tried to fix a merge conflict and accidentally added in two links that we already have on our page. If we were to merge in your pull request as is, we would have those links showing twice on our page.

You can find them by looking at the [Files Changed](https://github.com/skillcrush/105-practice/pull/634/files) tab near the top of this page and scrolling down the index.html file where they are highlighted in green. There are three lines highlighted, one of which is your advice link, which we'll want to keep. But we'll want to get rid of the other two.

Once you remove them, you can add, commit, and push your work and your changes will join your pull request here.

xoxo,
Sharon

**Comment by mschlattmann** [comment]
Hi Sharon, 

So sorry about that! I've made the changes and have committed them to my local repo. I'm having a hard time figuring out how to push the changes to the current pull request. In the terminal I used the command "git push origin advice-project" but got an error message, attached the screen shot here. How do I push changes to a current pull request? Do I need to create a new pull request instead? 

Thank you for your help! 
Marlena

Screen Shot 2019-09-22 at 4 39 24 PM

**Comment by acodeinprogress** [comment]
Hey @mschlattmann,

This means that you may have done some work up GitHub that you haven't yet pulled down to your computer. Do you remember making any changes to any files or anything on the GitHub website?

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @mschlattmann,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
