### PR TITLE
new

### PR DESCRIPTION
**Pull request by SVWessel**
my advice

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @SVWessel,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by SVWessel** [comment]
I think I did this right? Can you let me know?

**Comment by redrambles** [comment]
Hey @SVWessel !

We aren't seeing any changes on our end. Do you remember if you added and committed your change and then pushed up your testing branch?

**Comment by SVWessel** [comment]
[image: image.png]

There seems to be an upstream branch, but it won't let me push to it?

**Comment by acodeinprogress** [comment]
Hi @SVWessel,

Unfortunately your image isn't coming through. You can try emailing it to us at questions@skillcrush.com.

xoxo,
Sharon

**Comment by redrambles** [comment]
Hey @SVWessel,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Pull request closed without merging**
