### PR TITLE
Added link to advice page

### PR DESCRIPTION
**Pull request by justinehofer**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @justinehofer,

Congratulations on making your first pull request!

I see that you nested another 105-practice folder inside of the main 105-practice folder and you've copied over the index.html file to that folder. Instead, you'll need to delete that folder and the extra index.html file.

Once you've done that, you'll be back in the right place to continue with these instructions in the lesson:
8. Download the your-name-advice.html file. Unzip and extract the file.
9. Rename the your-name-advice.html file to add your first name and last initial to the file name. For example, if your name is Jane Hopper, you’ll rename the file as jane-h-advice.html.  
10. Move your advice HTML file to the advice directory inside the 105-practice directory.
11. Preview the advice HTML file in your browser to see what it looks like before editing it.
12. Open the advice HTML file with your text editor. Replace the three mentions of “Skillcrush” with your first name! Add your own advice to this page for future Skillcrushers to see! Save your changes when complete.
13. **Bonus:** The CSS style for this page is plain. Feel free to create your own CSS file in the css directory to style your advice page! Name your CSS file with your first name and last initial. On the advice HTML page, don’t forget to change the stylesheet link to the link to your custom style sheet. 
14. In the main directory, open the index.html file in your text editor.
15. Add a link to your advice HTML page with the other students’ links. For example, Jane Hopper would write: `<a href="advice/jane-h-advice.html" target="_blank">Jane H's Advice</a><br>`. Save the file when finished.
16. Navigate back to your command line to add and commit your changes.
17. Push the changes on your branch to your repo: git push origin advice.

Once you've done that, we can go ahead and merge this in!

xoxo,
Sharon

**Comment by justinehofer** [comment]
Hi @acodeinprogress - Nested folder has been deleted as well the extra index.html file. Thank you.

**Comment by acodeinprogress** [comment]
Hi @justinehofer,

I'm still seeing the extra 105-practice folder here with an index.html file nested inside of it.

You'll need to delete that folder and run `git add -A`, then commit and push. Once you do that, you'll need to follow the directions in the original 105-practice folder and then add, commit and push.

xoxo,
Sharon

**Comment by justinehofer** [comment]
Hi @acodeinprogress,

I restarted this assignment and submitted a new Pull Request: #1335

**Pull request closed without merging**
