### PR TITLE
J star Advice

### PR DESCRIPTION
**Pull request by Jame0753**
initial upload of j-star advice

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @Jame0753!

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. If you're not sure how to do this, feel free to take a look at other students links for reference. :)

Once you add your link, add and commit your changes and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by Jame0753** [comment]
HI Ann,
I did this project at work and wanted to finish it this weekend. I thought
I could clone the project from github but when I cloned and downloaded it
to my computer, it was the original version, without my advice. Where would
the page with my advice be? I'm having a hard time finding it.

I wanted to do the same thing with the test project from the final
assignment, that way I can work from home and at work and push and pull
from the same repo.

**Comment by Jame0753** [comment]
I think I may have figured it out. I was in the wrong project

**Comment by Jame0753** [comment]
nope, it didn't work. But i will make a comment in slack

**Comment by redrambles** [comment]
Hey @Jame0753,

You did a great job and your code is all merged in! Yay!

Cheers,
Ann :)

**Pull request merged**
