### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by annakmca**
Adding my advice page to skillcrush 105 practice repo

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @annakmca,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by annakmca** [comment]
I'm sorry It's taken me so long to get back to this, I was working on my portfolio website and when I looked at this and tried to fix it I couldn't figure out how and decided to come back to after I finished that, which took longer than I thought it would! 

I think I fixed it and got the index.html merged so the link to my advice page would show up, I was a little confused and I'm not completely positive I did it right, but I think it worked. Can you see it from that end? Sorry again I'm struggling and slow!

Anna

**Comment by redrambles** [comment]
Hey @annakmca,

Thanks for making those changes. Your code is all merged in! Yay!

Cheers,
Ann :)

**Comment by annakmca** [comment]
Yay, thank you!

**Pull request merged**
