### PR TITLE
Mariahl advice

### PR DESCRIPTION
**Pull request by mlafey**
Here's my addition for review/approval.

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @mlafey!

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. If you're not sure how to do this, feel free to take a look at other students links for reference. :)

Once you add your link, add and commit your changes and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by mlafey** [comment]
Hi Ann,

I think I must be missing a step then, but I'm not quite sure where. I
checked the index.html that I believe is the one I submitted changes for
and my link is the last one <a href="advice/mariahl-advice.html" target=
"_BLANK">M's Advice</a><br>. I also checked my branch in GitHub and it's
listed there too
https://github.com/mlafey/105-practice/tree/mariahl-advice/advice. Is there
somewhere else I should be looking/I should have added it to?

Thanks so much,
Mariah

**Comment by redrambles** [comment]
Hi again!

Ok - I am not seeing your link in the index.html page - if you look at the [code that is contained within your pull request ](https://github.com/skillcrush/105-practice/pull/524/files) - you can see that there are only two files - the advice html file and the css file - but the index.html file where your list should be present is not there. Is it possible that the change wasn't pushed? If you run 'git status' locally, is there anything that remains to be added and committed? Can you show us the result of `git status` as well as `git log --oneline -10` in the Terminal / GitBash - both performed on your `mariahl-advice` branch, please?

**Comment by mlafey** [comment]
Hi Ann,

Apologies for the delayed response. I checked the status and it turns out
the repo needed to be added/committed so I tried to do that, but I did
something wrong as the terminal won't make the updates. I have to admit,
I'm now feeling pretty lost/confused...

Thanks,
Mariah

**Comment by acodeinprogress** [comment]
Hey @mlafey ,

You have a couple options here:
1.  We can close this pull request and you can try this assignment over.
2. You can email us a screenshot with some info and we'll help you get this sorted out that way!

xoxo,
Sharon

**Comment by mlafey** [comment]
While I’m open to giving this a second shot, I would like to try and work with what I have so far. Please let me know what additional screenshots you need. 

Thank you

**Comment by redrambles** [comment]
Hey there! 

Ok! First, let's make sure that you are inside your `mariahl-advice` branch. Then, can you show us a screenshot of the result of:

`git status` 

as well as 

`git log --oneline -5` ?

We'll go from there!

P.S - It's a bit tricky to add screenshots in the comments here - so if you prefer, we can continue this conversation at 'questions@skillcrush.com'.

**Comment by mlafey** [comment]
Hi Ann,

Moving this convo to skillcrush email per your request. I've gone ahead and
taken the steps you requested, please find the screenshot attached.

Thank you
[image: 105 practice-terminal-2.png]
,
Mariah

**Comment by acodeinprogress** [comment]
Hey @mlafey,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
