### PR TITLE
Added Jessica M Advice file 

### PR DESCRIPTION
**Pull request by jessmonserrate**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @jessmonserrate,

Congrats on making your first pull request!

It looks like you overwrote another student's file instead of creating your own individual file.

We want to preserve everyone's work so we'll need for you to restore that other student's file and then create your own separate file. You can see the changes you made by clicking on the [Files Changed](https://github.com/skillcrush/105-practice/pull/1751/files) tab near the top of the page.

Once you fix that up, you can add, commit, and push and your changes will join your pull request here.

xoxo,
Sharon

**Comment by jessmonserrate** [comment]
Hi Sharon-  If I understood what I was looking at correctly, it looks like I inadvertantly removed content from index.html- I have fixed that and committed the file now.  Has this resolved the issue?  Or have I misunderstood?

Thanks,
Jessica

**Comment by acodeinprogress** [comment]
Hey @jessmonserrate,

The index.html file looks perfect!

The problem is the thejessica-m-advice.html - unfortunately, that file already existed so what you did ended up overwriting the original work in that file. So you'll need to restore that file to its original state and then create your own advice file with a different name.

Does that help clarify?

xoxo,
Sharon

**Comment by redrambles** [comment]
Hey @jessmonserrate ,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Pull request closed without merging**
