### PR TITLE
Added advice and linked to main directory

### PR DESCRIPTION
**Pull request by cwadrian**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hi @cwadrian,

Congratulations on making your first pull request!

There is just one small change that you'll need to make here.

Your advice file is currently located in a folder called cindy-a-advice.html. Instead, it should be located in the advice folder. Once you do that, the cindy-a-advice.html folder will be empty and you can delete it.

Then, you'll want to run `git add -A`, commit, and then push your work up to GitHub. Your changes will join your pull request here and then we can get this merged in!

xoxo,
Sharon

**Comment by cwadrian** [comment]
Hi Sharon,

Thank you! I think I did what you said, hopefully it worked.

Thanks,
Cindy

**Comment by acodeinprogress** [comment]
Hey @cwadrian,

I'm not seeing any changes here. Did you make sure to make your changes on the advice branch and then push to the advice branch on GitHub?

xoxo,
Sharon

**Comment by cwadrian** [comment]
Hi Sharon,

I thought I did, I re-did the steps and hopefully I did it correctly this
time!

Thank you,
Cindy

**Comment by acodeinprogress** [comment]
Hi @cwadrian,

Hmmm I'm still not seeing any updates here. Can you please share a screenshot of your terminal where you ran the add, commit, and push commands so that we can see what happened?

xoxo,
Sharon

**Comment by cwadrian** [comment]
Hi Sharon,

I'm still a little turned around on a few Git commands so I'm sure I'm
missing a step or something. Thanks for your help! I have attached my
screenshot.

**Comment by acodeinprogress** [comment]
Hey @cwadrian,

I'm not able to see a screenshot here. Could you email it to us and we'll go from there?

xoxo,
Sharon

**Comment by cwadrian** [comment]
Ah, gotcha!

Cindy

**Comment by acodeinprogress** [comment]
Hey @cwadrian,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
