### PR TITLE
added link to my advice page

### PR DESCRIPTION
**Pull request by sarah-lou-moore**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @sarah-lou-moore !

We got your link in the index file, but no advice page. Did you perhaps forget to add and commit it? Once you do, push up your advice branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code. Let us know if you have any questions!

Cheers,
Ann :)

**Comment by sarah-lou-moore** [comment]
Hi Ann,

I'm very confused about why it didn't work and I don't really understand
how to fix it. Please help :( I tried to follow the steps again in lesson 4
of 6 - "Finishing The Forking Workflow" but I ended up just updating the
index.html file again.

**Comment by sarah-lou-moore** [comment]
I think it's all resolved now? :)

**Comment by acodeinprogress** [comment]
Hi @sarah-lou-moore,

This is nearly perfect! The only issue left is that it appears as though you've deleted a couple links from another students in the index.html file. You can see which ones were removed (they are highlighted in pink) by clicking on the [Files changed tab](https://github.com/skillcrush/105-practice/pull/914/files) near the top of this page.

Once you add those back in, you can follow the same add, commit, and push process and then we can get this merged in.

xoxo,
Sharon

**Comment by sarah-lou-moore** [comment]
Hi Sharon,

So sorry about deleting other student's work! II've added the links back in
and committed the changes but now I can see there is another merge conflict
in the index.html file? How do I resolve this?

Thanks,
Sarah

**Comment by redrambles** [comment]
Hey @sarah-lou-moore !

No worries! We can help with that conflict - but first we need to see the changes. Can you push up your branch with `git push origin advice` so that we can see the changes you made in your latest commit? We'll go from there!

Cheers,
Ann :)

**Comment by sarah-lou-moore** [comment]
Hi Ann,

I just checked Github and it looks like the changes I made to the commit 3
days ago are showing now and the conflict is resolved, please do let me
know if it's still incorrect though?

Thank you!
Sarah

**Comment by redrambles** [comment]
Hey @sarah-lou-moore ,

Yes!!  You did a great job - thanks for making those changes. Your code is merged in! :)

Cheers,
Ann :)

**Pull request merged**
