### PR TITLE
practice1 example

### PR DESCRIPTION
**Pull request by dcarty01**
Hopefully submitting a pull request correctly.

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @dcarty01  - this is great!

The only change we need you to make is to make sure to link to your own stylesheet in the `<head>` of your advice page. 

Once you have made this change - add and commit it and then push up your `practice1` branch once more, which will automatically update this pull request. 

Then we should be all set to merge in your code. Let us know if you have any questions!

Cheers,
Ann :)

**Comment by dcarty01** [comment]
Hi Ann, I have pushed my branch again.  Please let me know if there is anything wrong.  Thank you

**Comment by acodeinprogress** [comment]
Hey @dcarty01,

There's just one more small change we'll need for you to make.

It looks like you added an advice file called untitled.html. You'll need to delete that file and then run a slightly different git command (`git add -A`), then commit and push.

Once you do that, we can get this merged in.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @dcarty01,

Great job! Looks like you were able to delete that file so now your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
