### PR TITLE
Added rebecca-r advice

### PR DESCRIPTION
**Pull request by Becca7Marie**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @Becca7Marie!

This is a good - we just need a few more things before we can merge this in.

We do have your `advice/rebecca-r-advice.html` file - which is great! However, we have a `Rebecca-r-advice.html` _folder_ inside the advice folder that we don't need. Please remove it. 

Also, we still need a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that long list. :)

Once you have removed the folder and added your link, add these change with `git add -A`. Then  your changes as per usual and push your advice branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by Becca7Marie** [comment]
Hi Ann! Thank you for your feedback, still trying to navigate using the terminal. I went in and removed the folder that I had inside of the Advice Folder and added myself to the html list of names. I did git add -A and then git pushed origin advice. I hope this solved it! Let me know if I need to do anything else! Thank you :)

**Comment by redrambles** [comment]
Hey @Becca7Marie !

Ok! Something isn't quite right because we didn't get your latest changes. Are you sure you made them on your advice branch?  What is the result of `git status`? Is your working directory clean? If so - can you try running `git push origin advice` once more please?

We'll go from there!

Cheers,
Ann :)

**Comment by acodeinprogress** [comment]
Hey @Becca7Marie,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
