### PR TITLE
Casey advice

### PR DESCRIPTION
**Pull request by CaseyPitman**
Here's my advice to newbies.

### CODE REVIEW

**Comment by CaseyPitman** [comment]
Hope this looks good.

**Comment by acodeinprogress** [comment]
Hey @CaseyPitman,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by CaseyPitman** [comment]
How's that?
-Casey

**Comment by redrambles** [comment]
Hey @CaseyPitman !

Sorry for the delay! Everything is great here, your code is merged in! :)

Cheers,
Ann :)

**Pull request merged**
