### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by Alacher2**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @Alacher2 !

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that long list. :)

Once you add your link, add and commit your changes and then push your advice branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by Alacher2** [comment]
Good morning,

I was looking at the index.html file and my advice is already linked. I
also previewed it in my browser and it is there as well. It's all under
Amber L's Advice. I'm not sure if I need to remerge my information or not.

**Comment by redrambles** [comment]
Hey @Alacher2 !

Perhaps there are changes that still need to be added and committed - or your last commit wasn't pushed up - because this is your change set for your pull request: https://github.com/skillcrush/105-practice/pull/1711/files

As you can see we have your advice file, but there is no change to the index.html file where your link would be. If you've already  made that change locally in your `advice` branch -then it just needs to be added and committed (if not already done) and pushed up (`git push origin advice`). 

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by Alacher2** [comment]
I created a new file and redid all the steps and sent a new pull request. Hopefully all my code is in order now. Please let me know. Thank you.

**Comment by acodeinprogress** [comment]
Hi @Alacher2 ,

I'm still not seeing the changes here. Did you make sure to push your changes to the same branch as this pull request?

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @Alacher2,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Comment by Alacher2** [comment]
Sorry, I actually already submitted a new one that got approved. Thank you
for all your help!

**Pull request closed without merging**
