### PR TITLE
Clonetest

### PR DESCRIPTION
**Pull request by marymackgr**
Some fresh advice!

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @marymackgr!

This is great - there are just two things that we need before we can merge this in:

1) Please place your 'marymack-advice.html' file inside the 'advice' directory.

2) Please add a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. If you're not sure how to do this, feel free to take a look at other students links for reference. :)

Once this is done - please add and commit your changes and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by acodeinprogress** [comment]
Hey @marymackgr,

Thanks for making those changes! There are just a couple more things that we'll need to do:

1. It looks like we have two advice files now - one is in the advice folder and one is in our main folder. Let's go ahead and delete the one that is in our main folder.
2. We would like for you to include a link to your advice page in the index.html file. 

Once you make those changes, you'll need to run a slightly different git command (`git add -A`),  commit, and push your changes and they will join your pull request here. Then we can get it all merged in.

xoxo,
Sharon

**Comment by redrambles** [comment]
Hey @marymackgr,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Comment by marymackgr** [comment]
Hi Ann,

Please see my screenshot attached. I apologize that I am so confused!
Thanks for your help.

**Pull request closed without merging**
