### PR TITLE
LeeAnns advice  clone

### PR DESCRIPTION
**Pull request by Lee-AnnC**
Some advice i would like to share

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @Lee-AnnC - this is a great start!

We need you to make a few small changes and then we'll be all set to merge this in.

1) There is an extra file in your pull request (`advice/debug.log`) that we don't need - please remove it.

2) We still need a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. If you're not sure how to do this, feel free to take a look at other students links for reference. :)

Once you have done these things, add and commit your changes and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by Lee-AnnC** [comment]
Good Morning Ann,

Thank you for the feedback.
Im not sure what you mean here...
(We still need a link to your advice page from the main index.html file, so
that folks can find your words of wisdom, once your code is merged in)
...when you say link my advice page from the main html? Could you please
explain.

Warm regards
Lee-Ann

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=oa-4885-b>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=oa-4885-b>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Lee-AnnC** [comment]
Hi Ann,

This going to sound like a very strange question but in this project can
you see the css styling that i put in?
I had a lot of problems seeing the styling. I could only see it in code-pen
and not in other browsers. i asked for help in slack and jacob and Bethany
could see the code where i could not...I have attached what i get shown in
my browsers. Do you know why i cant see it in chrome or anything else?

Regards
Lee


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=oa-4885-b>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=oa-4885-b>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by acodeinprogress** [comment]
Hey @Lee-AnnC,

To clarify Ann's comment, we want you to edit the index.html file. Once you're in that file, you should see a bunch of links that go to other students' advice files. We'll need you to add one that goes to your advice file.

The reason why your CSS doesn't seem to be connecting is because the link isn't quite correct. Since your advice file is in the advice folder, we'll need to tell our computer that we want to go back a folder (in computer language, this is `../`) before navigating to our css folder and then our CSS file.

Want to give those changes a try and then add (`git add -A`), commit, and push your work up to GitHub!

xoxo,
Sharon

**Comment by Lee-AnnC** [comment]
Good Morning ladies,

I have battled with getting my css to show on all browsers except code-pen.
i have tried to go out the folder (../) but it still does not show.
Please could you have a look to see where i am going wrong. I coded it
eventually in code-pen and could see my changes but when i open in chrome
or other browsers i cant see anything.

Regards
Lee


<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=oa-4885-b>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=oa-4885-b>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Lee-AnnC** [comment]
Hi there Ladies,

With the issue with my css not showing. I have tried (cd../) and it still
doesn't work.
Please can you tell me what i am doing wrong?

Thanking you in advance
Lee

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=oa-4885-b>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=oa-4885-b>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Lee-AnnC** [comment]
Hi there,
All changes made successfully :-)

**Comment by acodeinprogress** [comment]
Hey @Lee-AnnC,

I'm not seeing any changes here. Did you make sure to make them on your experiments branch and then push up to your experiments branch on GitHub?

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @Lee-AnnC,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Comment by Lee-AnnC** [comment]
Hi there Sharon,
 I have made all the changes, i just cant remember how to go back in git.
I cant remember how to get to my experiments branch to be able to add the
changes to be able to push them up.

Tried to log in this morning and keep getting this error below, so cant go
back to the lessons.
Error establishing a database connection

Regards
Lee

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Lee-AnnC** [comment]
Hi there Sharon,

I updated the file on github. Please can you have a look and see if its
correct.
I can now get back into skillcrush but not sure how to update it from the
terminal if i need to.
Sorry kinda lost at the moment.

Regards
Lee

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Pull request closed without merging**
