### PR TITLE
Adding Trevor E Advice

### PR DESCRIPTION
**Pull request by trevans3**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey Tyler!

Ok! So for some reason - your pull request involves a git submodule and a whole lot of files, because some directories were renamed.  :) No worries - we'll just have to do a little 'surgery' here in order to fix the issue. What I would suggest in this particular instance is to find your advice html file and then pull it out of the project folder and store it temporarily on the Desktop. If you have created a custom CSS file - do the same with that file (put it on your Desktop).

Once you have that (or those) file(s) safely tucked away, we are going to reset back to the commit just before you made your first one:

`git reset --hard 20ad6ba`

Once that is done, open up your project folder in the Finder or File Explorer - depending on your system. You will see an 'advice' folder, a 'css' folder, a README.md file and an index.html file. (You may also see the usually 'hidden' .git folder and .gitignore file). 

Find your html advice file that you squirreled away on your Desktop and drop it into the 'advice' directory. If you also squirreled away your css file, grab it and toss it into the 'css' directory.

Once you are good there - open up the main index.html file using your text editor and add a link somewhere in that long list that will point to your particular advice file inside the 'advice' directory. Save the file.

Then - back in the Terminal - add everything with `git add -A` - then commit as per usual `git commit -m "Your message here"` - and then finally push up your advice branch once more - which we will need to do using a force push given that we changed our branch history with the reset command: `git push --force-with-lease origin advice`

There you go! Then your pull request should be in good shape. It's important to know that although we are working in a team setting here and force pushing is usually a big no-no - we can do it safely in this instance because the change in history only involves your branch, which isn't being worked on by anyone else.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by trevans3** [comment]
Hi Ann! Sorry for the delay, but I think I have it all squared up now based on the directions you provided. I'm not exactly sure what happened when I originally tried to push my version back over. I appreciate you helping me getting back on track. Thanks!

Have a good one -
Trevor

**Comment by acodeinprogress** [comment]
Hi @trevans3,

It looks like there are still a large number of changed files as part of this pull request. You can see them by clicking on the [Files Changed](https://github.com/skillcrush/105-practice/pull/1384/files) tab of this page.

Did you make sure to follow all of the steps in Ann's previous comment? If so, could you share a screenshot of your terminal so that we can see exactly which commands you ran?

xoxo,
Sharon

**Comment by trevans3** [comment]
I first ran _git reset --hard 20ad6b_a, then I decided to re do _STEP 4 OF 6: START THE FORKING WORKFLOW_  from scratch. Then followed the directions Ann provided. However, I closed out the git bash app since then, but I did take a screenshot of the _git push --force-with-lease__ command to send it back to GH. Is there a way to look at the history of commands? 

Screenshot (12)

**Comment by acodeinprogress** [comment]
Hey @trevans3,

We would need to verify the commands that you ran before force pushing to make sure that everything went well.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @trevans3,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
