### PR TITLE
Added my own advice page & CSS Styles

### PR DESCRIPTION
**Pull request by Eddymerd**
:)

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @Eddymerd!

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. If you're not sure how to do this, feel free to take a look at other students links for reference. :)

Once you add your link, add and commit your changes and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by Eddymerd** [comment]
Link has been added! :) Do I resubmit a request? What is the appropriate next step?

**Comment by acodeinprogress** [comment]
Hi @Eddymerd,

Your changes are automatically connected to this pull request since you did your work on the same branch.

If you take a look at the index.html file in the [Files Changed tab](https://github.com/skillcrush/105-practice/pull/787/files), you'll notice that we have more red lines that green lines. Red lines mean that we deleted a line and green lines mean that we added a line. If you see a red line and a green line that are nearly identical, that means that you made a change to a line. But if we only have red lines and no corresponding green line, that means that we just deleted the line.

Go ahead and try adding back in the lines that were taken out so that we can include all students links in our index.html file.

Then you'll need to follow the same steps of adding, committing, and pushing.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @Eddymerd,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
