### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by kyle-wolt**

### CODE REVIEW

**Comment by kyle-wolt** [comment]
I'm sure I've done something wrong but I am completely stuck and don't even know what is happening. I'm hoping you can help.

**Comment by kyle-wolt** [comment]
Also not sure if I've been resolving the conflicts correctly.

**Comment by acodeinprogress** [comment]
Hi @kyle-wolt,

Congrats on making your first pull request!

It looks like you added some duplicate links to this project. You can see them listed in the index.html file by clicking on the [Files Changed tab](https://github.com/skillcrush/105-practice/pull/1392/files) near the top of this page.

We want to keep this code as clean as possible before we can merge this into the main codebase. Once you fix that up, you can add, commit, and push and your changes will join your pull request here.

xoxo,
Sharon

**Comment by kyle-wolt** [comment]
I'm sorry but I have no idea what I'm doing. I'm not sure what I was supposed to do based on your comment. I'm hoping I can get rid of this pull request and start a new one. 

I've read over the Working With Teams section several times trying to understand how to fix what I've already done but I don't see what step I need to start over from.

**Pull request closed without merging**
