### PR TITLE
105 practice upload

### PR DESCRIPTION
**Pull request by KWestfall**
practice advice file

### CODE REVIEW

**Comment by redrambles** [comment]
Hello @KWestfall !

This is great - we just need you to make a few small changes before we can merge this in.

1) Unfortunately we cannot accept image as part of this pull request, as the repository would quickly become too large. You are free to link to any existing hosted image online, of course - but we do need you to remove that image file.

2) Please add a link to your advice page inside the main index.html file. Most students will add theirs either at the beginning or at the end of the long list. :)

Once you have made these changes, please add with `git add -A`, then commit `git commit -m "your message here"` and push up your files `git push origin advice`, which will automatically update this pull request. Then we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann

**Comment by KWestfall** [comment]
Thanks for the feedback! I will make the changes and resubmit.

**Comment by KWestfall** [comment]
Ack! What did I do !?!?

**Comment by acodeinprogress** [comment]
Hey @KWestfall,

You didn't mess anything up! This looks great! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
