### PR TITLE
Personalized Changes

### PR DESCRIPTION
**Pull request by e-eastman**
Got a bit lost, not sure if I did this last step right...

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @e-eastman !

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that long list. :)

Once you add your link, add and commit your changes and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by e-eastman** [comment]
Hi, thank you for this. I did add my link to the file, but I wasn’t clear
in the directions if I was just working with my own advice html file with
the commit stuff or also include the index.html file. I will go back and
re-read that section and try to figure it out, this git stuff is more than
my brain can grasp!

- Erica

**Comment by e-eastman** [comment]
Hi Ann, sorry for two replies. I went back to the lesson I am thoroughly
lost. I'm pasting in some of my Terminal interaction below as I tried to go
back and do this lesson "right", but I'm not sure what that is and keep
getting error messages. If you're able to give me something more specific
in terms of the git commands needed or where I'm going wrong, that would be
great because I'm trying to go through the directions again and again and
it's just not working.

Thanks,

Erica



Macintosh:105-practice ericaeastman$ git remote -v

origin git@github.com:e-eastman/105-practice.git (fetch)

origin git@github.com:e-eastman/105-practice.git (push)

upstream git@github.com:skillcrush/105-practice.git (fetch)

upstream git@github.com:skillcrush/105-practice.git (push)

Macintosh:105-practice ericaeastman$ git fetch upstream

Enter passphrase for key '/Users/ericaeastman/.ssh/id_rsa':

Macintosh:105-practice ericaeastman$ git branch -a

  advice

* master

  remotes/origin/HEAD -> origin/master

  remotes/origin/advice

  remotes/origin/master

  remotes/upstream/master

Macintosh:105-practice ericaeastman$ git checkout master

A advice/amanda-j-advice.html

A advice/jason-al-advice.html

A advice/jena-s-advice.html

A advice/loria-d-advice.html

A advice/rena-z-advice.html

A css/amanda-j-advice.css

A css/jena-s-advice.css

A css/loria-d-advice.css

M index.html

Already on 'master'

Your branch is ahead of 'origin/master' by 1 commit.

  (use "git push" to publish your local commits)

Macintosh:105-practice ericaeastman$ git push origin advice

Enter passphrase for key '/Users/ericaeastman/.ssh/id_rsa':

Enter passphrase for key '/Users/ericaeastman/.ssh/id_rsa':

Enumerating objects: 5, done.

Counting objects: 100% (5/5), done.

Delta compression using up to 4 threads

Compressing objects: 100% (3/3), done.

Writing objects: 100% (3/3), 313 bytes | 313.00 KiB/s, done.

Total 3 (delta 2), reused 0 (delta 0)

remote: Resolving deltas: 100% (2/2), completed with 2 local objects.

To github.com:e-eastman/105-practice.git

   9fe8680..488905c  advice -> advice

Macintosh:105-practice ericaeastman$ git checkout master

A advice/amanda-j-advice.html

A advice/jason-al-advice.html

A advice/jena-s-advice.html

A advice/loria-d-advice.html

A advice/rena-z-advice.html

A css/amanda-j-advice.css

A css/jena-s-advice.css

A css/loria-d-advice.css

M index.html

Already on 'master'

Your branch is ahead of 'origin/master' by 1 commit.

  (use "git push" to publish your local commits)

Macintosh:105-practice ericaeastman$ git merge upstream/master

error: Your local changes to the following files would be overwritten by
merge:

  advice/amanda-j-advice.html advice/jason-al-advice.html
advice/jena-s-advice.html advice/loria-d-advice.html
advice/rena-z-advice.html css/amanda-j-advice.css css/jena-s-advice.css
css/loria-d-advice.css index.html

Macintosh:105-practice ericaeastman$ git checkout advice

error: Your local changes to the following files would be overwritten by
checkout:

index.html

Please commit your changes or stash them before you switch branches.

Aborting

Macintosh:105-practice ericaeastman$

**Comment by acodeinprogress** [comment]
Hey @e-eastman,

It looks like your changes went through so we are able to merge this in! [Great job!](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
