### PR TITLE
Added Rena Z's advice page

### PR DESCRIPTION
**Pull request by renazh**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hi @renazh,

Congrats on making your first pull request!

I noticed that you didn't add an advice page. If you could add that to this repo, that would be great! Once you do that, you can add, commit, and push your work and it will join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by renazh** [comment]
Hi Sharon, I'm having a bit of trouble with this. I went back to redo the
"working with teams" lesson, step 5, and since other students have added
their links to the index.html I am getting a conflict message. I don't want
to delete their work. Is there a way to cancel the merge? This is a
screenshot of my terminal:

**Comment by renazh** [comment]
Hi, I was able to cancel the merge with the "git merge --abort" command but I am still having trouble adding my advice page.

**Comment by renazh** [comment]
Sorry for the multiple messages! I have added my advice page onto my 105-practice repo but I don't see it in the pull request.

**Comment by redrambles** [comment]
Hey @renazh !

Thanks for making that change - we got your file and your code is merged in! Yay!!

Cheers,
Ann :)

**Pull request merged**
