### PR TITLE
Scott's Advice

### PR DESCRIPTION
**Pull request by s-underwood785**
Some advice I'd like to share!

### CODE REVIEW

**Comment by s-underwood785** [comment]
Edited my background so I figured I'd follow these steps again for another pull request!

**Comment by acodeinprogress** [comment]
Hey @s-underwood785,

This looks great so far!

I see that you added an image to the project. Unfortunately we cannot accept images in this repository as it would quickly become too large. You can definitely link to existing online images, though! :)

Please remove your image file and update your image links in your advice page. 

Then you'll need to run a slightly different git command (git add -A), commit, and push, your changes will join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @s-underwood785,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Comment by s-underwood785** [comment]
Oh shoot I completely forgot about this because I was working on the
milestone project! Now that I'm done with the milestone project I'll get on
it. Thanks Sharon!

-Scott

**Pull request closed without merging**
