### PR TITLE
Adding Nick J advice page

### PR DESCRIPTION
**Pull request by nickjamesmn**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @nickjamesmn!

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that long list. :)

Once you add your link, add and commit your changes and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by nickjamesmn** [comment]
Hi Ann, 

I attempted to update this, but I'm running into trouble... If you're able to view the screenshot I'm trying to attach here, maybe you can point out what I'm doing wrong? It's asking me for a password, I tried to enter the ssh we copied from github.. Would I need to follow all the steps over again from that lesson to get it right? I found there was definitely quite a bit of information to take in with this lesson... Thank you for your help and patience... 
Screen Shot 2020-04-06 at 9 34 04 PM

**Comment by acodeinprogress** [comment]
Hi @nickjamesmn,

Let's start by confirming what our origin repo is set to with this command: `git remote -v`

Please send a screenshot of what you see!

xoxo,
Sharon

**Comment by nickjamesmn** [comment]
Screen Shot 2020-04-09 at 6 31 54 PM

Thanks, Sharon! 

Nick

**Comment by redrambles** [comment]
Hey @nickjamesmn !

Thanks for that screenshot - everything looks ok with your remotes!

So what I'm seeing is that you created a CSS file - which is great! - but it hasn't yet been added or committed. That's ok - we can get to that. I'm not seeing any changes made to the index.html file, though. Can you check to see if when you added your link in the file, perhaps you forgot to save it in your text editor? If not - you might have lost that change and will need to add your link again. Once you do and you save your file in the text editor - the next time you run `git status`, you should see both your css file and the index.html file listed. You will want to add both with `git add -A` - and then commit them with `git commit -m "Your message here"` and finally push up your advice branch once more `git push origin advice` - which will automatically update this pull request.

Then we should be all set to merge this in. Let us know if you have any questions!

Cheers,
Ann :)

**Comment by nickjamesmn** [comment]
Hi! Hopefully it worked this time around...

**Comment by acodeinprogress** [comment]
Hey @nickjamesmn,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
