### PR TITLE
added koy's advice page

### PR DESCRIPTION
**Pull request by kscali**
Some advice I want to share is just to BELIEVE in yourself!

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @kscali,

This looks great so far! It looks like the last step that we need is for you to add a personal stylesheet with some styles to make your page look snazzy! 

Once you add that file and some styles, you can add, commit, and push your work to GitHub. Then we can get your code all merged in.

xoxo,
Sharon

**Comment by kscali** [comment]
I made some changes but can't seem to replicate a new pull request. I repeated the steps a few times. I'm wondering if it's because this pull is open? Hopefully the changes have been committed and the pull request is approved. Thanks!

**Comment by acodeinprogress** [comment]
Hey @kscali,

No need to make a new pull request. All you have to do is make your changes on this same branch and make sure to push to the same branch on GitHub. Then this pull request will automatically be updated with your changes.

It looks like a couple things happened when you made your changes. and we'll need to undo these things:
1. I see that you added an image to the project. We like to keep our repository as simple and clean as possible so we cannot accept images. You can host the image online and then include a link in your code to the image. If you could remove the image and the img folder that you also added, that would be great!
2. It looks like you changed the index.html file to use your stylesheet and you changed some of the content. We shouldn't be removing or changing any of the content in this file. The only thing we should do is add a link to our individual advice page. I see that you also added a <br> to someone else's link, which is totally fine.

Once you make those changes, you'll need to run a slightly different git command (git add -A), commit, and push.

xoxo,
Sharon

**Comment by kscali** [comment]
Hopefully this will fix the issues. Thanks.

**Comment by acodeinprogress** [comment]
Hey @kscali,

This is looking better! But the way the index.html file was changed back wasn't exactly how it was set up before. You can see exactly how it was (and exactly what you changed) if you look at the [Files Changed tab](https://github.com/skillcrush/105-practice/pull/36/files) near the top of this page.

It also looks like your image file and folder weren't deleted. If you deleted it on your computer, then it's just a matter of running the correct Git command. We'll need to make sure that we run `git add -A`. If we use `git add .`, the file and folder won't be deleted from Git.

xoxo,
Sharon

**Comment by kscali** [comment]
Fixed the index file.

**Comment by acodeinprogress** [comment]
Hey @kscali,

Awesome! Now all that's left is getting rid of that image folder and your image file.

Once that's done, remember to run `git add -A`, then commit and push!

xoxo,
Sharon

**Comment by kscali** [comment]
Honestly I don't know what you are talking about. I've deleted the image folder and file awhile ago. I have also run the git add -A and git commit , git push commands from my skillcrush-branch. I don't know where the conflict is and it is getting frustrating. I have no image folder. I've run the git add -A from the 105-project folder as well as the my-skillcrush-repo in my 105-project folder. I see no image file or folder. I don't know what else you want me to do. 
project105snip
reposnip

**Comment by acodeinprogress** [comment]
Hey @kscali,

Ah! Ok, so the image folder is inside the advice folder. If you look at the [Files Changed tab](https://github.com/skillcrush/105-practice/pull/36/files) near the top of this page, you'll see it listed as the first thing.

Are you able to spot it in that folder?

xoxo,
Sharon

**Comment by kscali** [comment]
Ok. Hopefully (fingers crossed) everything should be okay now. Thanks for the assistance.

**Comment by acodeinprogress** [comment]
Hey @kscali,

Perfect! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
