### PR TITLE
Updated HTML and CSS for advice page

### PR DESCRIPTION
**Pull request by sadunn4**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @sadunn4!

This is a great start! We just need two more things before we'll be ready to merge this in:

1) Your `symone-d-advice.html` file is in the root of the project directory - but we need it to be inside the `advice` directory. Please move it there.

2) We are missing a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that long list. :)

Once you move your file and add your link, add with `git add -A`, commit your changes as per usual and then push your `advice` branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by sadunn4** [comment]
Hi - I believe I made the proper changes. Can you confirm?

**Comment by acodeinprogress** [comment]
Hi @sadunn4,

Congrats on making your first pull request!

It looks like you deleted some links that other students added to this project. You can see them listed in the index.html file by clicking on the Files Changed tab near the top of this page.

We want to preserve everyone's work so we'll need for you to add those back in before we can merge this into the main codebase. Once you fix that up, you can add, commit, and push and your changes will join your pull request here.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @sadunn4,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
