### PR TITLE
Becks105branch

### PR DESCRIPTION
**Pull request by tbecks513**
Completed webpage with hosted images.

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @tbecks513,

This looks great so far! I just have a few small requests before I merge this in:

1. I see that you added some images to the project and an images folder. We like to keep our repository as simple and clean as possible so we cannot accept images. You can host the images online and then include a link in your code to the image. If you could remove the images and the images folder, that would be fantastic!
2. We would like for you to add a link to your advice page in the index.html file.

Once you make those changes, you'll want to run a slightly different git command (git add -A), commit, and push, your changes will join your pull request here.

xoxo,
Sharon

**Comment by tbecks513** [comment]
Hi Sharon,

I'm not sure what image folder you are referring to... Here is the link to
my contribution-
<https://github.com/tbecks513/105-practice/tree/becks105branch>which is a
different branch, so I'm not sure I did that correctly.. git has been very
confusing to me. My images are linked from Imgur- not my own folder.

What would I be linking to the index file?

Thanks for helping me.

**Comment by acodeinprogress** [comment]
Hey @tbecks513,

The `images` folder is inside the `advice` folder. You can see it here: https://github.com/tbecks513/105-practice/tree/becks105branch/advice

If you take a look at the index.html file, you'll see a lot of things like:
`<a href="advice/sharons-advice.html">Sharon's advice</a>`
These are all links to student advice pages. We would like you to add one that links to your advice page.

Does that help?

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @tbecks513,

Thanks for making those changes!

It looks like there are still a couple things we'll need to do before this can be merged in:

1. There is an extra advice file with no content and no .html extension. It's in the advice folder called `becksnailsit`
2. We'll need you to open up the index.html file and add a link to your personal advice page.

Once you do those things, you'll need to run `git add -A` again then commit and push.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @tbecks513,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
