### PR TITLE
Add Tina Jurén's advice

### PR DESCRIPTION
**Pull request by TinaJuren**
Some advice for a long lasting relationship with code

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @TinaJuren,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by TinaJuren** [comment]
Hi @acodeinprogress 

Thank you Sharon - now there is a link to my advice page in the index.html file.  

Tina

**Comment by acodeinprogress** [comment]
Hey @TinaJuren,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Comment by TinaJuren** [comment]
Hi @acodeinprogress,

Thank you Sharon, it was fun and I learned a lot during this lesson!

/ Tina

**Pull request merged**
