### PR TITLE
personalized advice page

### PR DESCRIPTION
**Pull request by ToyaMitchell**
Added my name and some bright colors

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @ToyaMitchell,

Great job so far! There are just a few changes that we'll need you to make before we can get this merged in.

I see that you added two CSS files - one with the .css extension and one without. Your styles were added to the one without the .css extension. You'll need to move those styles to your latoya-styles-advice.css file.

We would like for you to include a link to your advice page in the index.html file. 

If you could make those adjustments, all you have to do is run a slightly different git command (`git add -A`), commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by ToyaMitchell** [comment]
Hi,
I had the link in my html, did I save my css file wrong?

html>
    <head>
        <meta charset="utf-8">
        <link rel="stylesheet" type="text/css"
href="../css/latoya-styles-advice.css">
        
        <title>LaToya's Advice For Newbies</title>
    </head>

**Comment by acodeinprogress** [comment]
Hey @ToyaMitchell,

There are a couple things. If you take a look at the [Files Changed](https://github.com/skillcrush/105-practice/pull/448/files) tab near the top of this page, you'll see that you added two CSS files - one called latoya-styles-advice.css and the other called latoya-styles-advice

Your styles are in the latoya-styles-advice file rather than the latoya-styles-advice.css file.

We'll need you to move your styles to the latoya-styles-advice.css file and then delete the latoya-styles-advice file.

After that, you'll need to edit the index.html file and add a link that directs to your advice page so that others can access it easily from the main page of our project.

Once you make those changes, you'll need to run `git add -A`, the commit, and push. Then we can get your code merged in.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @ToyaMitchell,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Comment by ToyaMitchell** [comment]
Sorry! Do I need to clone the repository again?

**Pull request closed without merging**
