### PR TITLE
customized my advice page and styled it with a css file

### PR DESCRIPTION
**Pull request by joelmroy**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @joelmroy,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by joelmroy** [comment]
I am completely lost on how to redo this through git. I do have that link in the index.html file but I dont think I merged the files through git properly?

**Comment by redrambles** [comment]
Hello @joelmroy ! Did you make the changes to your index.html file while inside your 105-practice branch? What is the result of 'git status' ?

**Comment by redrambles** [comment]
Hey @joelmroy,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Pull request closed without merging**
