### PR TITLE
My advice html and css files

### PR DESCRIPTION
**Pull request by vegmer**
I added the html and css files for this exercise. 

I hope they are ok!

Thanks!

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @vegmer !

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. If you're not sure how to do this, feel free to open up the index.html file and look at other students' links. 

Once you add your link, add and commit your changes and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by vegmer** [comment]
Oops, sorry! I totally forgot about that step. I think it's done now, please let me know if there are any issues.

Thanks!

**Comment by redrambles** [comment]
Hey @vegmer,

Thanks for adding that link - your code is all merged in! 

Cheers,
Ann :)

**Comment by vegmer** [comment]
Wow! So fast! Thanks!!

**Pull request merged**
