### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by zululisbe**
Hi, 
How did I do?
I think that I have moved the advice file into the advice directory, the styles and link have also been added.
Zoe

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @zululisbe,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by zululisbe** [comment]
Hi Sharon,

Thank you for the feedback.
I think I am getting a little muddled, I have added a link to index.html (Zoe’s advice) is this the link you are talking about or is there another link I have to add?

Z

**Comment by redrambles** [comment]
Hi there!

If you added a link to the main index.html file (the file with the long list of links) - then you'll want to make sure that:

1) You made the change in your `advice` branch
2) You've added and committed that change

And then all that remains is for your to push up your advice branch once more `git push origin advice` so that it can update this pull request and we can see the change on our end. 

Then we'll be all set to merge in your code. :)

Let us know if you have any more questions!

Cheers,
Ann :)

**Comment by zululisbe** [comment]
Hi Anne,

Thank you for the feed back, I seem to have become terribly muddled and I am going to try and go through all the steps again.

Merry Christmass!
Z

**Pull request closed without merging**
