### PR TITLE
Updated text and style

### PR DESCRIPTION
**Pull request by lnsummers**
Let's try giving the document some style!

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @lnsummers !

This is great! We just need you to make a few small changes and then we'll be ready to merge this in.

1) Unfortunately we cannot accept image files as part of student pull requests, or this repository would get much too large too quickly. You are free to use any image you find on the internet and link to it as a background instead. So please delete your `image/blue-bubble.jpg` file.

2) We need you to add a link to the main index.html file that will point to your advice page, so that folks can find your words of wisdom, once your code is merged in. If you're not sure how to do this, feel free to take a look at other students links for reference. :)

Once you make these changes, please add them with `git add -A`, then commit (`git commit -m "your message here"`) and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by lnsummers** [comment]
Thanks, Ann. I've made the changes, let me know if it all works out!

LS

**Comment by redrambles** [comment]
Hi @lnsummers !

Ok - I'm not seeing any changes on my end. Do you remember making the changes in your 'changes' branch, and added (git add -A), committed (git commit -m "your message here") first? You'll need to do this so that when you push up your 'changes' branch, your pull requested is updated and we will be able to see the edit.

Keep us posted and let us know if you have any questions! :)

Cheers,
Ann

**Comment by lnsummers** [comment]
I believe I just made the changes in my master branch. So should I check
out my changes branch, make the changes, merge with master, add & commit?
Or checkout changes branch, make changes, add & commit.

LS

**Comment by acodeinprogress** [comment]
Hey @lnsummers,

Each pull request is specific to the branch that it was made on. So if you made your changes on master, they won't show here until they are also on your changes branch. What you can do to get them on here is merge your master branch into your changes branch.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @lnsummers,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
