### PR TITLE
practicing for 105 lesson

### PR DESCRIPTION
**Pull request by AimeeT8**
practicing how to submit a pull request for 105 lesson

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @AimeeT8 !

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. If you're not sure how to do this, feel free to take a look at other students links for reference. :)

You have also added an additional, empty style file called 'css/aimee-style.css'. Please delete this file - you are already using 'css/aimeeadvice.css'.

Once you add your link and delete that file, please add using `git add -A`, then commit your changes and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by AimeeT8** [comment]
I have made these changes and pushed the branch up for approval. Thanks!

**Comment by acodeinprogress** [comment]
Hey @AimeeT8,

You're on the right track! It looks like when you added a link to the index.html file, you added a <link> to your CSS page. Instead, we'd like to add an <a> link to your HTML page.

This will need to go in the <body> and if you need some examples, you can take a look at other students work.

Once you make that change, you'll need to follow the same steps to add, commit, and push and then we can get this merged in.

xoxo,
Sharon

**Comment by AimeeT8** [comment]
Okay thanks. I think I understand what I did wrong. I added a link in the
HTML file to my specific HTML file and then I pushed it back up to github.
Please let me know.
Thank you for your help,
Aimee

**Comment by redrambles** [comment]
Hey @AimeeT8,

You did a great job and your code is all merged in! Yay!

Cheers,
Ann :)

**Pull request merged**
