### PR TITLE
added back zach's advice

### PR DESCRIPTION
**Pull request by JessieG57**
Hi Ann & the rest of the team-

I added back the line with Zach's advice that I had originally deleted.  However, I do see that it is a duplicate, because he had already added it back in.  Also, I couldn't find my name, so instead of adding it above my name, I added it to the end of the file.  Please give me any feedback on this.  Thanks!

### CODE REVIEW

**Comment by JessieG57** [comment]
Not sure if I am supposed to "close pull request" - ahhh!

**Comment by JessieG57** [comment]
Hi Sharon-

I am really confused now.  To add the line back in that I deleted, I
actually created a new branch called Take2.  And I *did *create an advice
page and styled it with CSS....but all of that was on the Take1 branch.  I
am starting to get lost with all of this now and am not sure how to make it
all come together!  So, am I supposed to go back to Take1 and add the line
back in there, then submit the pull request for that branch?  And in that
case will my advice page and CSS show up?

**Comment by acodeinprogress** [comment]
Hey @JessieG57,

When we create a pull request, it is only for one branch. So if we make changes on another branch, the changes won't show up on our original pull request. In order to have all of our changes on one pull request, we'll need to make them all on one branch.

Does this help clarify?

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @JessieG57,

I see that you're still working on your other pull request so I'm going to go ahead and close this one.

xoxo,
Sharon

**Pull request closed without merging**
