### PR TITLE
Marcellas advice

### PR DESCRIPTION
**Pull request by MarcellaWonderweapon**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @MarcellaWonderweapon !

This is good! The only thing we need is for your `marcella-w-advice.html` file to be inside the `advice` directory. Right not it is inside the root of the project directory.

Once you have moved the file, add your changes with `git add -A`, then commit as per usual and push up your advice branch one more. This will automatically update your pull request, and we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by MarcellaWonderweapon** [comment]
Ok! I think it should work now!

**Comment by redrambles** [comment]
Hey there!

We are getting closer!! We do have a `advice/marcella-w-advice.html` file now (yay!) - but we _also_ have a `marcella-w-advice.html` file that is still in the root of the repository. Please remove it:

`rm marcella-w-advice.html`

And then add your changes with `git add -A` - commit as per usual and push up your advice branch once more. Then we should be good to go!

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by MarcellaWonderweapon** [comment]
Hi there, 

I removed the file. Then I pushed it with git push origin advice. Was that the right thing to do?

Cheers, Marcella

**Comment by acodeinprogress** [comment]
Hi @MarcellaWonderweapon,

It looks like in that process, you also deleted the index.html file, which we want to keep.

You'll need to add the index.html file back into this project before we can merge this in.

Once you do that, you'll want to add, commit, and push your work and it will join your pull request here.

xoxo,
Sharon

**Comment by MarcellaWonderweapon** [comment]
Hi Sharon, 

Neverending project 😅 I did it, did it work?

Cheers, Marcella

**Comment by redrambles** [comment]
Hey @MarcellaWonderweapon !

So sorry for the delay - yes it worked!! You are good to go, your code is merged in! 🎉

Cheers,
Ann :)

**Pull request merged**
