### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by sam-an-an**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @sam-an-an !

This is great - we just need you to make a few changes in the main index.html file (see here: https://github.com/skillcrush/105-practice/pull/1190/files#diff-eacf331f0ffc35d4b482f1d15a887d3bL6)

You removed '105' from the `<title>` and the `<header>` but we do want this to stay, so please add it back. :) There are also a few conflict markers that remain that we'd like you to remove.

Once these small fixes are made - add and commit your changes and push up your advice branch once more, which will automatically update this pull request. Then we should be all set to merge in your code. :)

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by sam-an-an** [comment]
Hello,
Thanks for the feedback, I've made the changes to the header and and title.

I do have a question regarding conflict markers - I was having trouble with
the "merge conflict" section of this course because my text editor was not
highlighting the conflicts (the way the lesson was explaining it would)
when I opened my html file after a conflict occurred. I'm attaching a
screenshot of the part of that assignment that I am referring to, for
reference.

I am not sure then how to check for the conflict markers. I am using
sublime text 3. Please let me know if there is something I am
misunderstanding or if there is a setting I'm not aware of. Once I can
actually see the conflict markers, I can finish this assignment as you
explained.

Thanks for your time!

Sam Angiulo

**Comment by sam-an-an** [comment]
Hello,

Sorry, I actually didn't even need to bring up the other issue I was having with conflict markers because I was able to find them in this index file- they were just not where I had thought they were. I was able to figure it all out in general. 

Hopefully this all worked this time, please let me know if it did. Thanks!

**Comment by acodeinprogress** [comment]
Hey @sam-an-an,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
