### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by Joseph-T87**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @Joseph-T87 !

This is nearly perfect!!! The only thing is that when you added your link to the index.html file, you accidentally deleted another student's link. See here: https://github.com/skillcrush/105-practice/pull/1404/files#diff-eacf331f0ffc35d4b482f1d15a887d3bL17

We need you to add that student's link back in - then save the file, add and commit the change and push up your advice branch once more. This will automatically update your pull request and we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by Joseph-T87** [comment]
I deleted her name because there were conflict markers and when I added it again
 I got the same conflict markers. I'm not sure why I'm getting them. 
Screenshot (43)

**Comment by acodeinprogress** [comment]
Hi @Joseph-T87,

A merge conflict just means that you updated the same lines as someone else did as part of this project and Git doesn't know which to keep.

You can see in your screenshot that there are two copies of her name - one in the top section and one in the bottom section. You'll want to remove just one of those and leave the other one.

Give that a try and then add, commit, and push and then we should be able to get this merged in!

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @Joseph-T87,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
