### PR TITLE
mellgibson advice

### PR DESCRIPTION
**Pull request by MellTGibson**
Hello, please check out my advice page, I added a background image. The image came out a little fuzzy probably because it was a smaller image. Any feedback?

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @MellTGibson !

This is great! We only need you to make a few small changes so that we can merge this in.

1) We are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. If you're not sure how to do this, feel free to take a look at other students links.

2) Unfortunately, we cannot accept any images in this repository, or it would quickly get too large. You are more than welcome to link to an existed hosted (online) image, however! We'll need you to delete that image file and modify the link in your advice page.

Once you have made those changes - you'll need to add with `git add -A`, then commit as per usual and push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by MellTGibson** [comment]
Hello, 
I have made the changes as per Ann's suggestions above, can you please review and let me know if all is ok now? Thank you

**Comment by MellTGibson** [comment]
Hi Ann,

I have made the above changes, as you have suggested and have requested a
new pull request.

Are you able to check if  I have done this correctly?

I hadn't heard back from any of the tutors yet and am thinking I may have
missed a step or did something wrong.

Many thanks,
Mellony

**Comment by redrambles** [comment]
Hey @username,

Thanks for making those changes - your code is all merged in! Yay!

Cheers,
Ann :)

**Comment by MellTGibson** [comment]
Thank you!!

**Pull request merged**
