### PR TITLE
Added tiata advice page

### PR DESCRIPTION
**Pull request by devtiata**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @devtiata,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by devtiata** [comment]
Hey Sharon, 
I just checked and it should be in there. I mean, it IS in there. 

advice/tiata-m-advice.html

Please let me know if you still aren't finding it! Thank ya!

**Comment by acodeinprogress** [comment]
Hi @devtiata,

I do see that file. Now you'll want to make sure that others can easily access that file. 

You can open up the index.html file in your text editor and add in a link that will take the user to your advice file.

Want to give that a try?

xoxo,
Sharon

**Comment by devtiata** [comment]
@acodeinprogress Thank you so much!

**Comment by acodeinprogress** [comment]
Hey @devtiata,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
