### PR TITLE
Experiments

### PR DESCRIPTION
**Pull request by kmilliner888**
Some advice I would like to share.

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @kmilliner888,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by kmilliner888** [comment]
I thought this was the advice page...? I'm confused. Which is funny because
that's what the page is all about. Not sure what page I'm linking the
kmilliner-advice.html page to?

**Comment by acodeinprogress** [comment]
Hey @kmilliner888,

We have a main page called index.html. On that page, you'll find links to everyone's advice file. We would like for you to edit the index.html file as well and add a link that goes to your advice page. That way, when others look at the main page, they can easily go to your page and see your great advice!

xoxo,
Sharon

**Comment by kmilliner888** [comment]
Sharon, can you let me know if my committed changes were received? I updated my advice page, and added the link to the main page. Let me know, not seeing the commits.

Thanks!
Kaylen

**Comment by acodeinprogress** [comment]
Hey @kmilliner888,

I'm not seeing any changes. Did you make sure to make them on your experiments branch on your computer and then push to your experiments branch on GitHub? If you made them directly on GitHub or on another branch, they won't show up here.

xoxo,
Sharon

**Comment by kmilliner888** [comment]
Not sure where I'm going wrong here. Was I not supposed to push the changes to the index.html file?

**Comment by acodeinprogress** [comment]
Hey @kmilliner888,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
