### PR TITLE
Created Lorraine's advice page and added link to home page

### PR DESCRIPTION
**Pull request by lozy1976**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @lozy1976 !

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that long list. :)

Once you add your link, add and commit your changes and then push your advice branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by lozy1976** [comment]
Hi Ann

Thank you so much for your help.  I'm not sure where I went wrong when
pushing my advice branch up because I had already made the change to the
index.html file.

I've added the link to my advice page again, however when I try to add and
commit the changes I'm getting the following error:

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.

Please can you help?

Kind regards
Lorraine :)

**Comment by redrambles** [comment]
Hey @lozy1976 !

Ok! So what I would do is quit your text editor as well as the Terminal / Git Bash - then open up the Terminal / Git Bash again in your project and run 'git status'. What do you see?

Cheers,
Ann :)

**Comment by lozy1976** [comment]
Hi Ann

I followed your instructions, and I have attached a screenshot of what I
saw.

**Comment by redrambles** [comment]
Hey @lozy1976 !

Looks like that screenshot didn't come through - why don't we continue this conversation at 'questions[at]skillcrush.com'? It will be a lot easier to share screenshots and such. :)

**Comment by redrambles** [comment]
Hey @lozy1976 !

This is great! Thanks for making those changes, your code is merged in!

Cheers,
Ann :)

**Pull request merged**
