### PR TITLE
Commit for this assignment

### PR DESCRIPTION
**Pull request by doskzorak**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey there!

This is great! The only things we need is that you move your html file into the advice directory (it is in the root of the project folder at the moment) - and that you tweak the link to your css file to adjust to the location of the css file relative to where the html file will now find itself.

Once you have made those changes, please add with `git add -A` - commit `git commit -m "Your message here"` and then push up your advice branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code. Let us know if you have any questions!

Cheers,
Ann :)

**Comment by doskzorak** [comment]
I updated the css link, and moved the advice.html into the advice directory. There appears to still be a branch conflict. If there is anything I can do to resolve the conflict, let me know. Otherwise, I will accept any advice on resolving this myself. Thanks!

- Tom

**Comment by redrambles** [comment]
Hey @doskzorak !

Thanks for making those changes! There still needs to be a small change made to your link to the css file in the head of your advice file. Right now you have:
`<link rel="stylesheet" type="text/css" href="/css/tomm-advice.css">`

But you will want it to be:
`<link rel="stylesheet" type="text/css" href="../css/tomm-advice.css">`

Those two little dots (..) at the front of the path indicate that you first need to move outside of the current folder (advice) before you can move into the css folder and find your advice file.

About the conflict - you should have some information in the Terminal / Git Bash about where the conflict exists (most likely in the index.html file, which everyone edits in order to add their link to their advice page). You'll want to open up that index.html file in your text editor and make sure to keep everyone's links - and remove the conflict markers. Then save the file and add it back in with `git add -A` and then commit as per usual `git commit -m "Bringing up to date with upstream"` or message of your choice. 

Then you can go ahead and make the change to the link to your stylesheet in your advice file  - add and commit that change also. 

Once we're good there - push up your advice branch once more, which will automatically update this pull request. Then we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by doskzorak** [comment]
Hey Ann,

Thanks for your patience with me on this. I'm working through the Responsive Websites Course. Let me know if there is anything else I am missing. I updated the link to the CSS file, and tested it so I believe it's working correctly now.

Have a great day,

Tom

**Comment by redrambles** [comment]
Hey @doskzorak ,

Thanks for making those changes - your code is all merged in! Yay!

Cheers,
Ann :)

**Pull request merged**
