### PR TITLE
Added my advice file to the index.html, also added my css file and a gif image

### PR DESCRIPTION
**Pull request by Hafziyah**
Hello 

Kindly peruse my additions.
Thank you.

Best wishes
Hafsat

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hi @Hafziyah,

Congrats on your first pull request!

I see that you added an image to the project. Unfortunately we cannot accept images in this repository - as it would quickly become too large. You can definitely link to existing online images, though! :)

Please remove your `img` directory with the images inside, and update your image links in your advice page. 

Then you'll need to run a slightly different git command (git add -A), commit, and push, your changes will join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by Hafziyah** [comment]
Hello Sharon

Thank you for your email. I have done an overhaul of the css and some minor
changes in the index.html file. I ran the "git add  -A, git commit - m
"Message", git push origin Master and git push origin advice" commands. Is
that okay? I can't see it reflected in Github.

Also, I can see my changes in google chrome but it is not being reflected
in internet explorer. I have run both the index and the style page through
the validator, so I am not very sure where the mistake exist.
Could you please help?

Thank you.

Best wishes
Hafsat

**Comment by redrambles** [comment]
Hey @Hafziyah ,

You did a great job and your code is all merged in! Yay! 

Cheers,
Ann :)

P.S - Don't worry about Internet Explorer - this browser is no longer being supported and hasn't been updated in a long time. As long as it looks good in Microsoft Edge, Chrome and Firefox, you are good to go. :)

**Comment by Hafziyah** [comment]
Thank you so much Ann.

**Pull request merged**
