### PR TITLE
Added Isaac M Advice page and Isaac M Advice CSS

### PR DESCRIPTION
**Pull request by mickey-charles**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @mickey-charles !

This is great! The only little change we need you to make is to move your `isaac-m-advice.html` file into the `advice` directory. Once you've done this, add and commit your change and push up your `advice` branch once more, which will automatically update your pull request. Then we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by mickey-charles** [comment]
Hi Ann,

Thank you for the feedback. Just double checking I've completed this correctly. It is advising there is a conflict with the "index.html" file.

**Comment by acodeinprogress** [comment]
Hey @mickey-charles ,

Regarding the conflict - we can either fix that up or you can give it a try if you want.

Other than that, there is just one last change that you'll need to make here. There is an extra advice file in the main folder of this project. You'll need to delete it from there and then run `git add -A`, commit, and push.

Once you do that, we should be able to get this merged in!

xoxo,
Sharon

**Comment by mickey-charles** [comment]
Hi Sharon,

Re. Conflict - I would like to fix it, but just no sure where to start.

Re. Advice file - I looked through the folder and can't find any doubles of
my advice file. Is that what I'm looking for? Sorry I'm getting a bit
confused with the process.


Any advice would be greatly appreciated.

Thank you

Isaac

**Comment by redrambles** [comment]
Hey @mickey-charles,

You did a great job and your code is all merged in! Yay! Great job handling the requested edits.

Cheers,
Ann :)

**Pull request merged**
