### PR TITLE
Added jackie w's advice

### PR DESCRIPTION
**Pull request by jackieceleste**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @jackieceleste !

This is great - the only change we need is that you place your `jackie-w-advice.html` file inside the `/advice` directory. Right now it is in the root of the directory.

Once you  have made that change, add and commit it and push up your 'advice' branch once more, which will automatically update this pull request. 

Then we should be all set to merge in your code. Let us know if you have any questions!

Cheers,
Ann :)

**Comment by jackieceleste** [comment]
Thank you! I am not sure what I missed, but here is a screenshot of the message I got.

Screen Shot 2020-02-19 at 8 51 38 PM

**Comment by redrambles** [comment]
Hey @jackieceleste !

Ok! So this usually happens either if you are pushing to the same repository from a different computer - or if you made changes directly on GitHub. Either one of these scenarios would result in a commit made on your branch which would not be present in the local repository that you are currently working with. I would recommend that you run `git fetch origin` and then `git merge origin/advice` to sync up your local codebase with whatever changes were made elsewhere. Then have a look at your code and if all is good, go ahead and push up your advice branch again.

Keep us posted!

Cheers,
Ann :)

**Comment by jackieceleste** [comment]
Okay, thank you! I think it worked this time.

**Comment by acodeinprogress** [comment]
Hey @jackieceleste,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
