### PR TITLE
Changed title and added Natalie's name and advice

### PR DESCRIPTION
**Pull request by natalliej7**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @natalliej7!

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that long list. :)

Once you add your link, add and commit your changes and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by natalliej7** [comment]
Hi Ann.  I am a little bit confused, because I added the advice link and
saved my changes before I pushed it and submitted the pull request.  I am
sending you a screenshot of my saved index file code so you can see what I
have.  I can do it again if needed.  If I do need to push it again, I would
stay in the advice branch on the command line and do it, correct?  Might be
a silly question, but I am still figuring all of this out.  Thanks.

**Comment by natalliej7** [comment]
Hi Ann,
Sorry, I should have attached a picture of the command line.  Where I get
confused is that it says I commited the change of adding my advice link to
the index file.  I am attaching the picture of the commit here.

**Comment by acodeinprogress** [comment]
Hey @natalliej7,

This is great! It also looks like you added a link to your personal stylesheet in the index.html. We'll need for you to remove that link (but leave the link to your advice file) before we can merge this in.

Once you make those changes, you'll follow the same steps of adding, committing, and pushing and then we can get this merged in!

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @natalliej7,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
