### PR TITLE
Added my name on advice and added link to janis c advice page on index…

### PR DESCRIPTION
**Pull request by JWYC**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey there! 

This is a great start! There are just two small things we need to take care of.

1) Your advice file is in the root of the project folder, but we need it to be inside the `advice` directory.
2) Your advice file is named `Janis-C-advice.html` but you will want to make sure that your letters are lower case, so that the link to the advice page that you provided in the index.html file connects. Although our local computers / browsers tend to be more forgiving, servers are very strict about case sensitivity.

Here is what I suggest:

1) Run: `mv Janis-C-advice.html advice/janis-c-advice.html` 
This will both move your advice page to the 'advice' directory and rename it to be lower case. The `mv` command is very versatile! 😄 

2) Add this change with `git add -A` - then commit as per usual and then finally push up your `advice` branch once more, which will automatically update this pull request. Then we should be all set to merge in your code!

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by JWYC** [comment]
Hi Ann
is my pull request ok? I think i made all the requested changes. not sure if I resolved all the issues needed for my pull to be accepted?

thanks
Janis

**Comment by redrambles** [comment]
Hey @JWYC !

We don't have any changes on our end. If you have completed the steps I outlined in my previous reply, do you remember then adding them with `git add -A` and then committing them with `git commit -m "Your message here"` ? If you have, then we still need to push up those changes so that we can see them over here: `git push origin advice`. 

Then we should be all set. Let us know if you have any questions!

Cheers,
Ann :)

**Comment by JWYC** [comment]
Hi ann
I use the git push origin master.... 
Think I may have been making my changes on the main trunk and not on the branch advice. I hopped over to the advice branch, then moved the janis-c-advice.html into the advice folder. 
Then i used the git add -A and git commit -m
Then i used git push origin advice
is that correct?
thanks for all the help
janis

**Comment by redrambles** [comment]
Hey @JWYC !

Nice work - thanks for making this change! Your code is merged in. :) 

Cheers,
Ann :)

**Pull request merged**
