### PR TITLE
added html and css to repo

### PR DESCRIPTION
**Pull request by MickSalter**
Some advice I'd love to share

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @MickSalter,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by MickSalter** [comment]
Hey Sharon,
 I think I finally figured out how to include a link. Thank goodness! It's
the little victories. I added, committed and pushed my changes. Fingers
crossed. Thank you so much again for all the help.

Mick

**Comment by acodeinprogress** [comment]
Hey @MickSalter,

Great job! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Comment by MickSalter** [comment]
Hi Sharon,

 Thanks again for everything. I accidentally clicked out of the meeting
without coping the links you sent. Could you please resend them,

Thanks
Mick

**Pull request merged**
