### PR TITLE
Created advice page and styled it

### PR DESCRIPTION
**Pull request by lindswhys**

### CODE REVIEW

**Comment by lindswhys** [comment]
Hopefully all looks good here! Just pull-requesting away!

**Comment by acodeinprogress** [comment]
Hey @lindswhys,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by lindswhys** [comment]
Okay! I'm not sure what that means exactly. Could you help me understand?

Also, when I'm editing my changes, do I change them on my branch that I
created earlier? Or do I create another branch? It sounds like that's what
I should do, just want to make sure.

Thank you!
Lindsy

**Comment by acodeinprogress** [comment]
Hey @lindswhys,

It looks like in the process, you added a bunch of other files. When you click on the [Files Changed](https://github.com/skillcrush/105-practice/pull/355/files) tab near the top of this page, the end result should only show 3 files there - your advice file, your css file, and the index.html file.

Once you get everything fixed up on your computer, you'll want to run a slightly different git command (`git add -A`), then commit and push and your changes will join your pull request here.

xoxo,
Sharon

**Comment by lindswhys** [comment]
I am completely lost! Not sure how I added those other files, and I don't know at all how to remove them. 

Also, I'm still confused, were we supposed to create a completely separate advice page (in addition to the one with ? I think I need to read the instructions more carefully. I didn't fully understand from the directions that there were supposed to be two html and css files--one for the "home page" and one for my advice page. I just did the advice page. I think that's why I got confused when you said to add a link to my advice page.  

ANYWAY, any help on how to remove the extra files I added (and how I got them there in the first place), would be much appreciated! It sounds like maybe I just need to do the entire Git section over again, I think I had too much space in between coding sessions. I feel like I'm missing a ton of info, but it's probably due to my lack of consistency in working on code. The past month has been busy with 4 kiddos, so I would do 2 hours here, then 1 hour like 3 or 4 days later, etc.

**Comment by acodeinprogress** [comment]
Hey @lindswhys,

When learning Git, it can be difficult to start and stop like that. If you want to go ahead and start over, let us know! We can close this pull request and then you can open up a new one once you've gone through the material again.

You should only create one new HTML file - your advice page. Then, we'll also want to edit the index.html file (which already exists) to add one line of code that should link to your advice page. When you open the index.html file, you should see a bunch of similar links that look something like this:
`<a href="advice/sharons-advice.html" target="_blank">Sharon's advice</a><br/>`
You'll need to add one of your own that links to your advice page.

xoxo,
Sharon

**Comment by lindswhys** [comment]
Got it. Thanks so much!

I think I will start over with it. Go ahead and close the pull request and
I'll redo everything.

Thanks again!
Lindsy Eklof

**Pull request closed without merging**
