### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by hallbkeara**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @hallbkeara!

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that long list. :)

Once you add your link, add and commit your changes and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by hallbkeara** [comment]
Hi Ann!

I'm actually sort of confused as to how to do that.. Or more specifically
which step to rewind to and make those changes? I guess I'm just not sure
what you're asking for - even though your feedback seems abundantly clear.
Sorry! Any more guidance would be greatly appreciated.

xo
Keara

**Comment by acodeinprogress** [comment]
Hey @hallbkeara,

Fortunately, we don't have to rewind anything here! All we have to do is add something in.

You'll want to open up the index.html file in your text editor. You should see a bunch of `<a>`s in the code - those are links that each student added to direct the user to their advice page. We'll want for you to add one in that will take the user to your advice page.

Once you do that, you can add, commit, and push your work up to GitHub.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @hallbkeara,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
