### PR TITLE
Meyas 105 practice

### PR DESCRIPTION
**Pull request by Laurel96**
First pull request

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @Laurel96,

As I mentioned in my email, there's just one last step - adding a <link> to the index.html file that will direct the user to your advice page.

Once you do that, you'll need to add, commit, and push your updated code to GitHub. Then we can get this merged in!

xoxo,
Sharon

**Comment by Laurel96** [comment]
Hi Sharron, Thank you for your help, I have added the link and pushed.  Meya x

**Comment by acodeinprogress** [comment]
Hey @Laurel96,

Awesome! Thanks so much for making that change!

In the process of fixing that up, it looks like you left in some merge conflict markers and removed some links to other students' advice files. We'll need for those conflict markers to be removed and for the removed links to be added in again. You can see what was removed (in pink) and what was added (green) by clicking on the [Files Changed](https://github.com/skillcrush/105-practice/pull/712/files) tab near the top of this page.

Once you make those changes, you can go through the same process of adding, committing, and pushing!

xoxo,
Sharon

**Comment by Laurel96** [comment]
Hi Sharon,
Whoops! Not sure how I managed that. I added them back into the html, saved and pushed. However it is still showing as conflicts? when i can see them in the html? 
laurel96 x

**Comment by acodeinprogress** [comment]
Hey @Laurel96,

It looks like when you added in those links, you added in extra ones. Your own advice link should show up in green. Outside of that, we should only see the green lines that match the red lines - meaning that the lines we add in should match the lines that we removed. So if you look at the Files Changed tab again, you can see that we have a lot more green lines that red lines.

You'll also want to make sure to remove those conflict markers that are highlighted in green as well.

xoxo,
Sharon

**Comment by redrambles** [comment]
Hey @Laurel96,

I fixed up the index.html file for you. :) Your code is all merged in! :)

Cheers,
Ann :)

**Pull request merged**
