### PR TITLE
Added advice file

### PR DESCRIPTION
**Pull request by NicoleD1010**
Good morning!  Could we do a pull request, please? Thank you for your help.
Nicole Delacruz

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @NicoleD1010 !

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that list. :)

Once you add your link, add and commit your changes and then push your advice branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by NicoleD1010** [comment]
Thank you, Ann!

 

Is this the link that you mean?  I don't know how to add the link right now.  

file:///C:/Users/nicol/Desktop/105-practice/advice/nicole-d-advice.html

 

Sent: Thursday, February 18, 2021 at 4:09 PM

**Comment by redrambles** [comment]
Hey @NicoleD1010,

Ok! So I think that we have ourselves tangled up a bit here, so I'm going to suggest that you follow the next couple steps which will involve resetting your advice branch to a copy of what the master branch is on upstream and then adding in your code files and finally adding in your link to the main index.html file. It's the fastest/easiest way to get to where we want to go.

1. Make sure that you are inside your advice branch (git status will tell you which branch you are on - and so will git branch).
2. Using the Finder / File Explorer, find your `advice/nicole-d-advice.html` file and temporarily tuck it away on your Desktop.
3. Fetch from upstream `git fetch upstream`
4. Reset your advice branch to be an exact copy of the master branch on the upstream remote. This means that it will exactly match the main codebase as it is at this point in time. `git reset --hard upstream/master`
5. Move your html file from the desktop and place it inside the 'advice' directory
6. Open up the index.html file using your text editor of choice and add a link to your advice file.
7. Run git status. You should see two changes listed - your html file and the index.html file. Add everything with `git add -A`.
8. Commit as per usual `git commit -m "Your message here"`
9. Now we'll need to force push:` git push -f origin advice` - because we changed history with the reset command. This is ok to do in this instance because you are working alone on your own branch - no one else will be affected by this change in history.

Once that force push goes through, this pull request will be updated. At that time we should see on our end that the only changes included in your PR involve your own html file - and a modification to the index.html file (your link) - which is exactly what we want.

Then we should be all set to merge in your code.

Let us know if you have any questions!

**Comment by NicoleD1010** [comment]
Hi, Ann.

I wanted to check with you to see how this task went that I did.  Did I do it right, and everything worked out in GitHub?

 

Nicole Delacruz

 
 

Sent: Tuesday, February 23, 2021 at 5:13 PM

**Comment by NicoleD1010** [comment]
Good morning,  Ann.I am wondering whether you saw my reply email about this GitHub update tgat you had me do. I did the steps that you asked me to do. How did it turn out? Did the pull request go through?Thanks, Nicole Delacruz--Sent from my Android phone with GMX Mail. Please excuse my brevity.On 2/23/21, 17:13 Ann Cascarano <notifications@github.com> wrote:

   
  Hey @NicoleD1010, 
  Ok! So I think that we have ourselves tangled up a bit here, so I'm going to suggest that you follow the next couple steps which will involve resetting your advice branch to a copy of what the master branch is on upstream and then adding in your code files and finally adding in your link to the main index.html file. It's the fastest/easiest way to get to where we want to go. 
   
   Make sure that you are inside your advice branch (git status will tell you which branch you are on - and so will git branch). 
   Using the Finder / File Explorer, find your advice/nicole-d-advice.html file and temporarily tuck it away on your Desktop. 
   Fetch from upstream git fetch upstream 
   Reset your advice branch to be an exact copy of the master branch on the upstream remote. This means that it will exactly match the main codebase as it is at this point in time. git reset --hard upstream/master 
   Move your html file from the desktop and place it inside the 'advice' directory 
   Open up the index.html file using your text editor of choice and add a link to your advice file. 
   Run git status. You should see two changes listed - your html file and the index.html file. Add everything with git add -A. 
   Commit as per usual git commit -m "Your message here" 
   Now we'll need to force push: git push -f origin advice - because we changed history with the reset command. This is ok to do in this instance because you are working alone on your own branch - no one else will be affected by this change in history. 
   
  Once that force push goes through, this pull request will be updated. At that time we should see on our end that the only changes included in your PR involve your own html file - and a modification to the index.html file (your link) - which is exactly what we want. 
  Then we should be all set to merge in your code. 
  Let us know if you have any questions!

**Pull request closed without merging**
