### PR TITLE
Added Corey G advice and link to it on index

### PR DESCRIPTION
**Pull request by coreyg2008**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey there @coreyg2008 !

We successfully got your advice file - yay! And though we do have the link to your advice file in the index.html file - there were several other student links that were accidentally deleted. This usually comes about as a result of resolving a tricky conflict.

No worries - we can guide you through this. In your advice branch, run the following commands:

`git fetch upstream`

`git checkout upstream/master index.html`

This will replace your current index.html with the fresh version of the file as it is on the main codebase.

Open up the file in your text editor of choice and add your link to the bottom of the list.

Save the file - add and commit as per usual and push up your `advice` branch once more, which will automatically update this pull request.

Then we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by coreyg2008** [comment]
Hey Ann,

I have resubmitted the changes

Thanks
Corey

**Comment by redrambles** [comment]
Hey @coreyg2008 ,

Thanks for making this change! All we need now is the link to your file, which you can add to the top or the bottom of the list. Once you've done that, add and commit that change and push up your advice branch one more time.

Then we'll be all set to merge this in!

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by acodeinprogress** [comment]
Hey @coreyg2008,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
