### PR TITLE
Add Shu Hye's Advice

### PR DESCRIPTION
**Pull request by ShuHye**
added a webpage and css for it

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @ShuHye !

This is a good start! We're going to need you to do two more things before we can merge in your code.

1) Your `shuhye-advice.html` file needs to be inside the `advice` folder. Right now it's in the root of the project.

2) We are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. If you're not sure how to do this, feel free to take a look at other students links for reference. :)

Once you move your html file and add your link, add and commit your changes and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by ShuHye** [comment]
Hi, I've done the commit you requested.

**Comment by acodeinprogress** [comment]
Hey @ShuHye,

I'm not seeing any updates here. Did you make sure to do the work on your experiment branch on your computer and then push to the experiment branch on GitHub?

xoxo,
Sharon

**Comment by ShuHye** [comment]
I've either done it or I'm lost now. I will have to review the whole process.

**Comment by redrambles** [comment]
Hey @ShuHye ,

You did it! Thanks for making those changes. Your code is all merged in! Yay!

Cheers,
Ann :)

**Pull request merged**
