### PR TITLE
my first try

### PR DESCRIPTION
**Pull request by Tyrian12**
This is my first try. Hit some hiccups but think I ironed them out

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hi @Tyrian12,

It looks like you added an empty advice file in the root folder. You'll want to follow the instructions on this page: https://learn.skillcrush.com/module-13/make-a-change-then-push-to-your-repo/

In the end, you should have added an advice file (with some HTML in it) inside the advice folder, a personal stylesheet (with some CSS in it) in the css folder, and edited the index.html to include a link that directs to your advice file.

Once you do those things, you'll need to run a slightly different command (`git add -A`), commit, and then push. You'll want to make sure to make those changes on your `new-branch-105` branch and then push to that branch on GitHub. Then we can get that merged in.

xoxo,
Sharon

**Comment by Tyrian12** [comment]
OK thanks I will get on after work and see what went wrong. I thought I followed the instructions in the lesson but maybe I misunderstood something or mistyped something. Thanks

**Comment by Tyrian12** [comment]
Ok I believe I made the changes in my repository, do I need to make another pull request? Or how does that work?

**Comment by redrambles** [comment]
Hey there! If you have made the changes in the 'new-branch-105' branch in your repository - once you have added and committed those changes, you'll need to push up your branch (`git push origin new-branch-105`) which will automatically update this pull request. No need to create another one. :)

Ann

**Comment by Tyrian12** [comment]
OK thanks. I thought I did that. Maybe I need to go back through and redo
this lesson.

Matthew Graham
Flyover State Redneck Barber
www.Instagram.com/flyoverstateredneckbarber

**Comment by acodeinprogress** [comment]
Hey @Tyrian12,

We're not seeing any change other than the addition of a blank file in the main folder.

If you want to go back and try this again, let us know! We can close this pull request and you can try following the instructions on a new branch and then create a new pull request when you're ready!

xoxo,
Sharon

**Comment by Tyrian12** [comment]
Sharon if you would just close this one. I am not sure what I did wrong but
when I pull it up in git everything shows as normal with my HTML, so I am
just going to go back and do the whole thing again.

Matthew Graham

**Pull request closed without merging**
