### PR TITLE
created advice page and added link to index page

### PR DESCRIPTION
**Pull request by abbeycle22**
Some advice to share.

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @abbeycle22 !

Ok! So this is great - but we have a number of additional files that we don't need. If you have a look at your pull request [here](https://github.com/skillcrush/105-practice/pull/883/files) - you'll notice a number of .json and config files and such that we'll need to remove. 

Your advice file, css and link in the index.html are great! We want to keep those three files and remove everything else.

Once you have made those changes, you'll want to add with `git add -A` then commit `git commit -m "Your message here"` and finally push your branch up once more `git push origin master`, which will automatically update this pull request. Then we should be all set to merge in your code! :)

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by abbeycle22** [comment]
Ok. How do I remove them? Take them out of the file?

**Comment by abbeycle22** [comment]
It looks like my son got on my computer and deleted my main file. I do have
it all saved onto github. How do i proceed?

Thank you,
Abbey

**Comment by redrambles** [comment]
Hello @abbeycle22!

Ok - so in that case you would want to clone your copy of the fork (which you would find here: https://github.com/abbeycle22/105-practice) onto your computer, then move back into your project and make the requested changes. :) Once you're all done, add and commit your changes and push up your branch once more, which will update your pull request.

Let us know how it goes!

Cheers,
Ann :)

**Comment by abbeycle22** [comment]
Ok I think I did it right. Please let me know.

thank you,

Abbey

**Comment by redrambles** [comment]
Hey @abbeycle22 !

We didn't get any changes on our end. Do you remember adding your changes with `git add -A` - committing them (`git commit -m "Your message here"`) and then pushing up your branch: `git push origin master` ?

Let us know!

**Comment by abbeycle22** [comment]
I do. But I will try again tonight when I get home from work

**Comment by abbeycle22** [comment]
I checked to make sure i did the push and it said that everything is up to
date. Since the origional file got deleted i need to do it all over again
dont i?

**Comment by redrambles** [comment]
Hey @abbeycle22 !

You don't need to start over, because Git has a record of your files. Because we have a bit of an unusual situation here with some extra files inside a hidden .vs folder, I'll list out the steps that you can take to get back on track. Let us know how it goes!

1) Since your pull request is based off of your master branch, make sure that in your Terminal / GitBash, you are inside this repository and your master branch is checked out.

2) Let's rewind back in time a couple of commits - but keep all of our files in our working directory, so that we then pick and choose what we want to add:
`git reset cadf4a9`

Note that we aren't using '--hard' - we are just letting the 'reset' command use its default setting, which will preserve our files from the subsequent commits in our working directory.

3) Run `git status` - you will see a bunch of red files. Let's add back only the ones we are interested in: the index.html file, your advice html file and your css file.

4) If you run `git status` again, you will see that you have those three files in green - which means they are ready to be committed. Let's do that with `git commit -m "Your message here"`.

5) Now let's push up your master branch once more. You'll need to use the '-f' flag here (for 'force') - because we have changed the history of the branch by going back in time and only adding and committing the files we are interested in. `git push -f origin master`

6) That should do it - this pull request should be updated as a result, and we'll go from there. :)

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by redrambles** [comment]
Hey @abbeycle22,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Comment by abbeycle22** [comment]
Sorry. I have been away from my computer and on vacation. So I start over
from the pull request area right?

I only typically get to do this at work on lunch.

**Comment by redrambles** [comment]
Hey @abbeycle22 !

Yes - so if you follow the steps I outlined above, you can then open up a new pull request. We'll go from there! :)

**Comment by redrambles** [comment]
I can also reopen this pull request if you are ready to follow the steps that I outlined?

**Comment by abbeycle22** [comment]
Ann,

I have been trying to get this to work. But I am wondering since I had to
redownload the files if that is what is throwing me off. Can you delete
what I did and I will just start over. It’s driving me batty.

I don’t know what I am doing wrong and starting over seems the easiest way
to do it.

I may just start over with the other part of the course (new one) that way
maybe something will click and git will be easier for me use.

Sorry for being such a pain in the arse!

Please let me know.

Thank you,
Abbey

**Comment by redrambles** [comment]
Hey @abbeycle22,

Yes of course - no worries - you can start this challenge over whenever you are ready. This pull request is already closed, so there is nothing more to do. You can go ahead and create a new pull request whenever you are ready. :)

Cheers,
Ann :)

**Comment by abbeycle22** [comment]
Ann,

Ok I do not know why I cannot get the other files to leave. I just got some
other stuff to go that I didn't even realize was in my folder. But since I
already have the forked repo it wont let me do another one. :( Now the One
drive file in there has the 105-practice one on there but it has additional
as well AGAIN!!! I dont' know where to go from here. i am so frustrated
it's not even funny. I feel like i'm spinning my wheels then today I
actually get it to do something and it's still wrong.

I am so sorry for all of the trouble. I am following the steps and it just
isn't working for me.

I don't know if you can unfork me on this or not. I just know I tried to
start over (dont really want to do the other, new, course yet) and since
i'm already forked it took me back to the same one. I created a new
repository with a different name and cannot figure out why i cannot fork
that one instead since it has the right stuff in it.

Please advise.

Thank you,
Abbey

**Comment by redrambles** [comment]
Hey @abbeycle22 !

Ok! So what I suggest that you do is delete your forked repository on GitHub and then fork the repo from Skillcrush again. You'll have a fresh, up-to-date forked copy that you can then clone down to your computer, create your branch and add your advice page, css and a link to it in the main index page. Then you'll be all set to create a new pull request and get this project done! 

Cheers,
Ann :)

**Comment by abbeycle22** [comment]
Ok. I’ll see what I can do. I was afraid to delete anything.

**Pull request closed without merging**
