### PR TITLE
revised advice html and css

### PR DESCRIPTION
**Pull request by Ree1010**
comparing

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @Ree1010,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by Ree1010** [comment]
I think it is shown as "Ree's advice"  If you can't find it I will try to add it again. Thanks!! Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Sharon <notifications@github.com> Date: 10/29/18  3:13 PM  (GMT-06:00) To: skillcrush/105-practice <105-practice@noreply.github.com> Cc: Ree1010 <rpicou1010@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [skillcrush/105-practice] revised advice html and css (#76) Hey @Ree1010,
This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.
xoxo,
Sharon

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/skillcrush/105-practice","title":"skillcrush/105-practice","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/skillcrush/105-practice"}},"updates":{"snippets":[{"icon":"PERSON","message":"@acodeinprogress in #76: Hey @Ree1010,\r\n\r\nThis looks great! I just have 1 teensy request before I merge this in.\r\nWe would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.\r\n\r\nxoxo,\r\nSharon"}],"action":{"name":"View Pull Request","url":"https://github.com/skillcrush/105-practice/pull/76#issuecomment-434061590"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/skillcrush/105-practice/pull/76#issuecomment-434061590",
"url": "https://github.com/skillcrush/105-practice/pull/76#issuecomment-434061590",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [skillcrush/105-practice] revised advice html and css (#76)",
"sections": [
{
"text": "",
"activityTitle": "**Sharon**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@acodeinprogress",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"skillcrush/105-practice\",\n\"issueId\": 76,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close pull request",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"PullRequestClose\",\n\"repositoryFullName\": \"skillcrush/105-practice\",\n\"pullRequestId\": 76\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/skillcrush/105-practice/pull/76#issuecomment-434061590"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 402205604\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by acodeinprogress** [comment]
Hey @Ree1010,

If you take a look at the [Files Changed](https://github.com/skillcrush/105-practice/pull/76/files) tab near the top of the page, it shows all the files and all the content that has been changed. We should be able to see the index.html file on that list and that you added a link there that directs to your advice page.

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @Ree1010,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
