### PR TITLE
Adding tricia d's advice

### PR DESCRIPTION
**Pull request by Triciad23**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hi @Triciad23,

Congrats on making your first pull request!

I see that you made quite a lot of changes in the index.html file so it's difficult to tell if anything was deleted or added. As part of this assignment, we just want you to add your own link to that file. I would recommend restoring the file to its previous state and then adding in your own link.

Once you do that, you can add, commit, and push and your changes will join your pull request here.

xoxo,
Sharon

**Comment by Triciad23** [comment]
Hi, honestly I am really confused....All I did do was add my link to the index.html.

**Comment by Triciad23** [comment]
@acodeinprogress I figured out the issue. Even though I only added my link, I had the "prettier" code formatter set up in visual studio code and when I saved it, it reformatted the index.html. As a result it showed me making all of those as changes.  I restored it to the previous format...added my link.. and saved without the "prettier" reformatting.

**Comment by redrambles** [comment]
Hey @Triciad23 ,

Nice work figuring out the issue - and thanks for making the change. Your code is merged in!

Cheers,
Ann :)

**Pull request merged**
