### PR TITLE
Added markie's advice

### PR DESCRIPTION
**Pull request by markie-m**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @markie-m !

This is a good start! We have a link to your advice page in the main index.html file (yay!) but no such `advice/markie-m-advice.html` file exists as part of this pull request. Perhaps it still need to be added and committed? Checking git status will help you confirm.

Once you have added and committed your advice page, please push up your advice branch once more, which will automatically update this pull request. Then we should be all set to merge in your code.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by markie-m** [comment]
Okay, I have been over and over Starting the Forking Workflow and Finishing the Forking Workflow sections of the Working With Teams lesson, and I really hope this is right because I think my brain is getting more scrambled the more time I spend trying to figure out where I'm going wrong. Please tell me I've fixed the issue and my code can finally be merged with the main branch.

**Comment by redrambles** [comment]
Yes it is, @markie-m !

Thanks for making those changes, your code is merged in! 🥳

Cheers,
Ann :)

**Comment by markie-m** [comment]
OMG, thank you for all your help and support, @redrambles ! This is a HUGE relief to get past this hurdle.

**Pull request merged**
