### PR TITLE
advice forking

### PR DESCRIPTION
**Pull request by nzea001**
Some advice I'd like to share.

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @nzea001,

I see that you added an image to the project. Unfortunately we cannot accept images in this repository as it would quickly become too large. You can definitely link to existing online images, though! :)

Please remove your image and update your image links in your advice page. 

Then you'll need to run a slightly different git command (git add -A), commit, and push, your changes will join your pull request here.

Let us know if you need any help!

xoxo,
Sharon

**Comment by nzea001** [comment]
Hello,

Happy Easter! Ok, so I updated  my advice page and did the add, commit,
push. I'm not sure if it was completed and if I'm supposed to see it on
GitHub since it's an open pull request. Thank you I'm advance.

Sincerely,
Natalie

**Comment by redrambles** [comment]
Hello there! 

We do not see any new commits here. Did you delete your image and update the link to it in your advice file - while on your 'advice' branch? If so, once you added and committed that change locally, you'll want to push up your advice branch once more (`git push origin advice`). This will update your pull request and then we should be all set to go.

Keep us posted! :)

Cheers,
Ann

**Comment by redrambles** [comment]
Hey @nzea001,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Pull request closed without merging**
