### PR TITLE
Added shari k's advice

### PR DESCRIPTION
**Pull request by kahn-s**

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @kahn-s !

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. Students will typically add their link to the top or the bottom of that long list. :)

Once you add your link, add and commit your changes and then push your advice branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by kahn-s** [comment]
OK, I’m getting off to a slow start today, and this was a while ago.  Can you remind me what my link might be, and what exactly I am doing?

**Comment by acodeinprogress** [comment]
Hi!

In this project, you added an advice page in the advice folder.

Now you'll want to edit the index.html file and add an <a> to link to the advice file that you've already created.

xoxo,
Sharon

**Comment by redrambles** [comment]
Hey @kahn-s ,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

Cheers,
Ann :)

**Pull request closed without merging**
