### PR TITLE
sheilas advice page

### PR DESCRIPTION
**Pull request by Slipstitch**
An advice page to share

### CODE REVIEW

**Comment by Slipstitch** [comment]
Advice to share

**Comment by redrambles** [comment]
Hey @Slipstitch!

This is great - the only thing we are missing is a link to your advice page from the main index.html file, so that folks can find your words of wisdom, once your code is merged in. If you're not sure how to do this, feel free to take a look at other students links for reference. :)

Once you add your link, add and commit your changes and then push your branch up once more, which will automatically update your pull request. Then we should be good to merge in your code!

Let us know if you have any questions!

Cheers,
Ann

**Comment by Slipstitch** [comment]
Thanks, Ann
Hopefully, I am good to go!

**Comment by acodeinprogress** [comment]
Hi @Slipstitch,

I'm not seeing any changes here. Did you make sure to complete your work on your experiment branch and then push your changes to your experiment branch on GitHub?

xoxo,
Sharon

**Comment by Slipstitch** [comment]
Hi Sharon

I am having some issues with GitHub and my key... I am working with them to
learn how to solve this problem.

I will complete the exercise when I solve the key authentication problem.

Thanks
Sheila

**Comment by redrambles** [comment]
Hey @Slipstitch ,

Thanks for making those changes! You did a great job and your code is all merged in! Yay!

Cheers,
Ann :)

**Comment by Slipstitch** [comment]
Whoopee!!

**Pull request merged**
