### PR TITLE
Added Christina S advice page and link to the page in index.

### PR DESCRIPTION
**Pull request by TrendingUpward83**
Also added .css file for styles.

### CODE REVIEW

**Comment by redrambles** [comment]
Hey @TrendingUpward83 !

This is a great start! We just need a few more things before we can merge this in.

1) Your `christina-s-advice.html` file is in the root of the project, but we need it to be in the `advice` directory. Please move it there.

2) When your file has moved, you will need to its relative path to your personal stylesheet, so that the two can connect.

3) There is an additional `debug.log` file that snuck in as part of this pull request - please remove it.

Once you make those changes, please add with `git add -A` - commit as per usual and push up your advice branch once more, which will automatically update this pull request. Then we should be all set to merge in your code!

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by TrendingUpward83** [comment]
Hi Ann,
I believe I have corrected everything, and I see my commits here. Please let me know your feedback. 
Thanks!
Christina

**Comment by redrambles** [comment]
Hey @TrendingUpward83 !

Thanks so much for making those changes. In terms of the advice file, the css and the link in the index.html , we are all set. However if you have a look at your changed files view here: https://github.com/skillcrush/105-practice/pull/1628/files - you'll notice that there are 4 additional files - a `.suo` two `.json` and a `.sqlite` file that we don't need. Please delete all four files and then add those changes with `git add -A`. Once you're good there, commit as per usual and push up your advice branch one more time, and we'll be all set to merge this in.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by acodeinprogress** [comment]
Hey @TrendingUpward83,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
