### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by carr33678**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @carr33678,

Great work here!

It looks like you created two advice files:

- Lori-c-advice.html
- Lori-C-advice.html

Since you'll only need one advice file here, you can go ahead and delete the extra. I also see a CSS file but it doesn't have any styles in it. Want to go ahead and add some in?

Once you make those changes, you can run `git add -A`, then commit and push your work to GitHub and then we can get that merged in.

xoxo,
Sharon

**Comment by carr33678** [comment]
Ok I deleted the lori-c-advice.html. However, I had to shut down my
computer so my terminal had to restart. I went through the steps "Finishing
the Workflow". So Am i ready to copy the link on my github page? See
attached terminal and github page.

Lori C.

**Comment by acodeinprogress** [comment]
Hey @carr33678,

Thanks for making those changes!

I see that you deleted the empty css file which is great!

There is still an extra advice file present in your project and now it looks like there are some merge conflict markers in the index.html file. You'll want to remove the extra advice file and then delete those conflict markers.

Then you'll run `git add -A`, commit, and push :D

xoxo,
Sharon

**Comment by carr33678** [comment]
I am not sure where this is and how to remove it.

I am getting discouraged with this. :(

 I do not know how it got so messed up. I follow the directions exactly.

Lori

**Comment by acodeinprogress** [comment]
Hi @carr33678,

You have two Lori-C advice files in the advice folder - one has a capital C and one has a lowercase c. Are you able to see both of those files?

xoxo,
Sharon

**Comment by carr33678** [comment]
Yes. I had taken out the one with the lowercase c.

**Comment by redrambles** [comment]
Hey Lori!

Ok - if you have a look at your change set here for your advice branch: `https://github.com/skillcrush/105-practice/pull/1757/files` - you'll see that both your html files are still there. Here's how to fix:

1) Make sure that you are in your advice branch (`git checkout advice`)
2) Using the Finder / File Explorer, open up your 105-practice/advice folder, and locate one of your html files and drag it to the trash.
3) Run `git status` in the command line - you should see that Git has picked up on the deletion. Let's add that change with `git add -A` - and then commit it as per usual: `git commit -m "Your message here"`
4) Finally, push up your advice branch once more: `git push origin advice`


That should do it. Keep us posted and let us know if you have any more questions!

Cheers,
Ann :)

**Comment by carr33678** [comment]
Hi Ann,
Thanks for the reply, I did move on to the next section because I was being
so tripped up by this. When I reviewed your instructions however, going to
Finder I did not see my advice in the 105-coding resource folder. See
attached. Is this necessary I take care of this or can I just move on.

 I went to next section on "Posting website to github".

Lori

**Comment by redrambles** [comment]
Hey @Lori - 

A few things! 

1) For this particular pull request, we are working with the '105-practice' folder (not '105-coding_resources') and we are working on the advice _branch_. 

2) It's fine if you would like to move on and work on something else - you can always circle back and work on this challenge later. If that's what you'd like to do, please let us know and we will close this pull request. You can open a new pull request when you circle back. :)

**Comment by carr33678** [comment]
Thanks Ann,
I just completed the Git class, so I would like to go back and fix this.
1. I opened GIthub 105-practice/advice and only see a Lori-*c* in the
beginning. I scrolled down and did not see any other. Lori*-C . *See
attached.
2. When I opened the 105-practice/advice folder I only see a Lori-*C *(not
a Lori*-c*) I also scrolled through these. See attached
3. Only other thing i saw was a lori-c css (which is in red, not sure why).
See attached.

Hope I can help fix whatever I need to complete this section.

Lori C. or Lori c. ????

**Comment by redrambles** [comment]
Hey @carr33678 - we aren't getting any screenshots in this thread - but if you'd like to share some with us, please reach out at questions@skillcrush.com, where we can see them - and then we'll go from there.

Cheers,
Ann :)

**Comment by carr33678** [comment]
Will do, thanks!

**Comment by acodeinprogress** [comment]
Hey @carr33678,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Comment by carr33678** [comment]
OK Thx

**Pull request closed without merging**
