### PR TITLE
Advice

### PR DESCRIPTION
**Pull request by maddie-sullivan**

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @maddie-sullivan,

Congrats on making your first pull request!

There are a few things we'll need to change before we can merge this in:
1. It looks like you created an extra folder called maddie-s-advice.html rather than placing your advice file in the advice folder that already exists.
2. We have some blank CSS files in the maddie-s-advice.html folder as well. That's totally fine if you don't want to add any CSS but in that case, we don't need to create empty CSS files.
3. We have two advice files - one called your-name-advice.html and one called maddie-s-advice.html. Let's move the maddie-s-advice.html file into the advice folder and then delete the rest of the files inside of the maddie-s-advice.html folder.

Once you make those changes, you'll need to run `git add -A`, the commit and push. Your changes will join your pull request here and then we can get them merged in.

xoxo,
Sharon

**Comment by maddie-sullivan** [comment]
@acodeinprogress thanks for the feedback!

I think I was able to resolve all the changes you noted above and got them committed. Please let me know if anything still looks wrong!

**Comment by acodeinprogress** [comment]
Hey @maddie-sullivan,

I'm not seeing any changes here. Did you make sure to make them on your `advice` branch and then push them to your `advice` branch on GitHub?

xoxo,
Sharon

**Comment by maddie-sullivan** [comment]
@acodeinprogress I don't think I pushed to advice on GitHub and/or I had a conflict I needed to resolve. Looks like the commit is appearing in GitHub and I have resolved the conflict now.

**Comment by redrambles** [comment]
Hey @maddie-sullivan !

Ok - we are getting closer! All we need to do now is delete two extra files that snuck into your pull request: `your-name-advice.html/your-name-advice.html` and `your-name-advice.html/Untitled-1.css`

Once you have deleted both of those files, please add with `git add -A` and then commit as per usual (`git commit -m "Your message here"`) and then push up your advice branch once more (`git push origin advice`). That will update your pull request, and we should be good to go.

Let us know if you have any questions!

Cheers,
Ann :)

**Comment by acodeinprogress** [comment]
Hey @maddie-sullivan,

I see that you merged the master branch into your advice branch but you'll still need to implement the changes that Ann requested above.

Once you do that, we can get your changes merged into the main codebase!

xoxo,
Sharon

**Comment by acodeinprogress** [comment]
Hey @maddie-sullivan,

We haven't heard from you in a while so I'm going to close this pull request. Feel free to submit a new one when you're ready!

xoxo,
Sharon

**Pull request closed without merging**
