### PR TITLE
Janas experiment

### PR DESCRIPTION
**Pull request by Jana993**
Some advice I would like to share

### CODE REVIEW

**Comment by acodeinprogress** [comment]
Hey @Jana993,

This looks great! I just have 1 teensy request before I merge this in.
We would like for you to include a link to your advice page in the index.html file. If you could add that in, all you have to do is add, commit, and push your changes and they will join your pull request here. Once you do that, we can get it all merged in.

xoxo,
Sharon

**Comment by Jana993** [comment]
Dear Sharon, 

I just did.. but seems I created a conflict? :D

**Comment by acodeinprogress** [comment]
Hey @Jana993,

Yes, you can either fix that up yourself or we can take care of it for you. Let us know what you'd like to do!

xoxo,
Sharon

**Comment by Jana993** [comment]
Dear Sharon,

Could you,please, do it? 😇
I’m not working hard on phase two responsive website class and to be honest
don’t even remember what was that task. ((:

Thank you in advance.
Best,
Jana

**Comment by acodeinprogress** [comment]
Hey @Jana993,

All fixed! Your code is all [merged in](https://media.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif).


xoxo,
Sharon

**Pull request merged**
